
console.log('wordbank2.js at your service.');

var bank = [];

bank.push( {"word":"וְ/ וּ / וָ","category":"cj.","frequency":"50524","arr":[["@","and"]]});
bank.push( {"word":" ּהַ","category":"art.","frequency":"24058","arr":[["@","the"]]});
bank.push( {"word":"ל","category":"prp.","frequency":"20321","arr":[["@","to"],["@","for"],["@","regarding"],["@","belonging to"]]});
bank.push( {"word":"בּ","category":"prp.","frequency":"15559","arr":[["@","in"],["@","with"],["@","by"],["@","at"],["@","among"],["@","into"],["@","when"]]});
bank.push( {"word":"אֵ֫ת / אֶת־","category":"prt.","frequency":"10987","arr":[["@concept","direct object particle","particle indicating direct object","definite direct object marker","DDOM","ddom","D.D.O.M.","d.d.o.m."]]});
bank.push( {"word":" ּמִן / מִ","category":"prp.","frequency":"7529","arr":[["@","from"],["@","out of"],["@","since"],["@","than","more than","(more) than"]]});
bank.push( {"word":"עַל","category":"prp.","frequency":"5777","arr":[["@","on"],["@","over"],["@","against"],["@","on account of"],["@","to"]]});
bank.push( {"word":"אֶל","category":"prp.","frequency":"5518","arr":[["@","to"],["@","toward"],["@","against"],["@","at"],["@","unto"],["@","concerning"]]});
bank.push( {"word":"אֲשֶׁר","category":"prt.","frequency":"5503","arr":[["@","who"],["@","which"],["@","that"]]});
bank.push( {"word":"כֹּל","category":"n.m.","frequency":"5415","arr":[["@","all"],["@","every"],["@","whole"],["@","any"]]});
bank.push( {"word":"אָמַר","category":"vb.","frequency":"5316","arr":[["@","to say","say"]]});
bank.push( {"word":"לֹא / לוֹא","category":"prt.","frequency":"5193","arr":[["@","not","no"]]});
bank.push( {"word":"בֵּן / בֶּן","category":"n.m.","frequency":"4941","arr":[["@","son","son of","son (of)"]]});
bank.push( {"word":"כִּי","category":"cj.","frequency":"4487","arr":[["@","that"],["@","because"],["@","when"],["@","indeed"]]});
bank.push( {"word":"הָיָה","category":"vb.","frequency":"3576","arr":[["@","be","become","be(come)"],["@","happen"]]});
bank.push( {"word":"כּ","category":"prp.","frequency":"3053","arr":[["@","like"],["@","as"],["@","according to"],["@","when"]]});
bank.push( {"word":"אֵל / אֱלֹהִים","category":"n.m.","frequency":"2839","arr":[["@","God"],["@","god","gods","god(s)"]]});
bank.push( {"word":"אֵלֶּה","category":"prn.","frequency":"2839","arr":[["@","these"]]});
bank.push( {"word":"עָשָׂה","category":"vb.","frequency":"2632","arr":[["@","do","to do"],["@","make","to make"],["@","perform","to perform"]]});
bank.push( {"word":"בּוֹא","category":"vb.","frequency":"2592","arr":[["@","go in","to go in","come in","to come in","enter","to enter","come to","to come to"]]});
bank.push( {"word":"מֶלֶך","category":"n.m.","frequency":"2530","arr":[["@","king"]]});
bank.push( {"word":"אֶ֫רֶץ","category":"n.f.","frequency":"2505","arr":[["@","land"],["@","earth"],["@","ground"],["@","territory"],["@","region"]]});
bank.push( {"word":"יוֹם","category":"n.m.","frequency":"2301","arr":[["@","day"]]});
bank.push( {"word":"אִישׁ","category":"n.m.","frequency":"2199","arr":[["@","man"],["@","husband"],["@","each"]]});
bank.push( {"word":"פָּנֶה / פָּנִים","category":"n.m./f.","frequency":"2126","arr":[["@","face"]]});
bank.push( {"word":"בַּיִת","category":"n.m.","frequency":"2047","arr":[["@","house"]]});
bank.push( {"word":"נָתַן","category":"vb.","frequency":"2014","arr":[["@","give","to give"],["@","put","to put"],["@","set","to set"],["@","exchange","to exchange"],["@","grant","to grant"],["@","yield","to yield"],["@","dedicate","to dedicate"]]});
bank.push( {"word":"עָם","category":"n.m.","frequency":"1869","arr":[["@","people","a people"]]});
bank.push( {"word":"יָד","category":"n.f.","frequency":"1627","arr":[["@","hand"],["@","power"]]});
bank.push( {"word":"הָלַךְ","category":"vb.","frequency":"1554","arr":[["@","go","to go"],["@","come","to come"],["@","walk","to walk"]]});
bank.push( {"word":"דָּבָר","category":"n.m.","frequency":"1454","arr":[["@","word"],["@","matter"],["@","thing"]]});
bank.push( {"word":"הוּא","category":"prn.","frequency":"1398","arr":[["@","he"]]});
bank.push( {"word":"רָאָה","category":"vb.","frequency":"1311","arr":[["@","see","to see"]]});
bank.push( {"word":"עַד / עֲדֵי־","category":"prp.","frequency":"1263","arr":[["@","as far as"],["@","even to"],["@","until"]]});
bank.push( {"word":"אֲנִי / אָנֹכִי","category":"prn.","frequency":"1233","arr":[["@","I"]]});
bank.push( {"word":"אָב","category":"n.m.","frequency":"1210","arr":[["@","father"]]});
bank.push( {"word":"זֶה","category":"prn.","frequency":"1178","arr":[["@","this","masc. sg. this"]]});
bank.push( {"word":"שָׁמַע","category":"vb.","frequency":"1165","arr":[["@","hear","to hear"],["@","obey","to obey"]]});
bank.push( {"word":"הִנֵּה / הֵן","category":"prt.","frequency":"1147","arr":[["@","look","look!","see here","see here!","take note","take note!"]]});
bank.push( {"word":"דָּבַר","category":"vb.","frequency":"1141","arr":[["@Pi","speak","to speak"]]});
bank.push( {"word":"לִפְנֵי","category":"prp.","frequency":"1126","arr":[["@","before"],["@","in the presence of"]]});
bank.push( {"word":"יָשַׁב","category":"vb.","frequency":"1088","arr":[["@","sit","to sit"],["@","dwell","to dwell"]]});
bank.push( {"word":"עִיר","category":"n.f.","frequency":"1088","arr":[["@","city"]]} );
bank.push( {"word":"עִם","category":"prp.","frequency":"1084","arr":[["@","with"],["@","near"],["@","beside","besides"]]} );
bank.push( {"word":"יָצָא","category":"vb.","frequency":"1076","arr":[["@","go out","to go out","come out","to come out","go","come out","to go","come out"]]});
bank.push( {"word":"שׁוּב","category":"vb.","frequency":"1075","arr":[["@","turn back","to turn back"],["@","return","to return"]]});
bank.push( {"word":"אִם","category":"cj.","frequency":"1070","arr":[["@","if"],["@","when"],["@","or"]]});
bank.push( {"word":"לָקַח","category":"vb.","frequency":"976","arr":[["@","take","to take"],["@","receive","to receive"]]});
bank.push( {"word":"יָדַע","category":"vb.","frequency":"956","arr":[["@","know","to know"]]});
bank.push( {"word":"עַיִן","category":"n.f.","frequency":"900","arr":[["@","eye"],["@","appearance"],["@","spring"]]});
bank.push( {"word":"עָלָה","category":"vb.","frequency":"894","arr":[["@","go up","to go up","ascend","to ascend"]]});
bank.push( {"word":"אֵ֫ת / אֶת־","category":"prp.","frequency":"890","arr":[["@","with"],["@","beside","besides"]]});
bank.push( {"word":"שָׁנָה","category":"n.f.","frequency":"878","arr":[["@","year"]]});
bank.push( {"word":"שֵׁם","category":"n.m.","frequency":"864","arr":[["@","name"]]});
bank.push( {"word":"לֵבָב / לֵב","category":"n.m.","frequency":"854","arr":[["@","mind"],["@","heart"],["@","will"]]});
bank.push( {"word":"שָׁלַח","category":"vb.","frequency":"847","arr":[["@","send","to send"],["@","stretch out","to stretch out"]]});
bank.push( {"word":"מוּת","category":"vb.","frequency":"845","arr":[["@","die","to die"]]});
bank.push( {"word":"שָׁם","category":"adv.","frequency":"835","arr":[["@","there"]]});
bank.push( {"word":"עֶשֶׂר / עָשָׂר","category":"n.m.","frequency":"829","arr":[["@","ten","10"],["@","-teen","x-teen","*-teen","plus ten"],["@plural","twenty","20"]]});
bank.push( {"word":"אָכַל","category":"vb.","frequency":"820","arr":[["@","eat","to eat"]]});
bank.push( {"word":"עֶבֶד","category":"n.m.","frequency":"803","arr":[["@","servant"],["@","slave"]]});
bank.push( {"word":"אֵין / אַיִן","category":"subs.","frequency":"790","arr":[["@","not","there is not"]]});
bank.push( {"word":"אִשָּׁה","category":"n.f.","frequency":"781","arr":[["@","woman"],["@","wife"]]});
bank.push( {"word":"גָּם","category":"adv.","frequency":"769","arr":[["@","also"]]});
bank.push( {"word":"נֶפֶשׁ","category":"n.f.","frequency":"757","arr":[["@","self"],["@","soul"],["@","living being"],["@","breath"],["@","throat"]]});
bank.push( {"word":"כֹּהֵן","category":"n.m.","frequency":"750","arr":[["@","priest"]]});
bank.push( {"word":"אַתָּה","category":"prn.","frequency":"749","arr":[["@","you","masc. sg. you"]]});
bank.push( {"word":"כֵּן","category":"adv.","frequency":"741","arr":[["@","thus"],["@","so"]]});
bank.push( {"word":"קָרָא 1","category":"vb.","frequency":"739","arr":[["@","call","to call"],["@","proclaim","to proclaim"],["@","read aloud","to read aloud"],["@","name","to name"]]});
bank.push( {"word":"אַל","category":"adv.","frequency":"729","arr":[["@","not","no"]]});
bank.push( {"word":"אַחַר / אַחֲרֵי","category":"adv.","frequency":"718","arr":[["@","behind"],["@","after","afterwards","after(wards)","afterward","after(ward)"]]});
bank.push( {"word":"אֶחָד","category":"n.m.","frequency":"713","arr":[["@","one","1"]]});
bank.push( {"word":"דֶּרֶךְ","category":"n.m.","frequency":"712","arr":[["@","way"],["@","road"],["@","manner"]]});
bank.push( {"word":"הֲ / הַ","category":"prt.","frequency":"661","arr":[["@","?"],["@concept","interrogative particle"]]});
bank.push( {"word":"נָשָׂא","category":"vb.","frequency":"659","arr":[["@","lift","to lift"],["@","bear","to bear"],["@","carry","to carry"]]});
bank.push( {"word":"אָח","category":"n.m.","frequency":"629","arr":[["@","brother"]]});
bank.push( {"word":"קוּם","category":"vb.","frequency":"627","arr":[["@","arise","to arise"],["@","rise","to rise"],["@","stand up","to stand up","stand","to stand"]]});
bank.push( {"word":"שָׁלֹשׁ","category":"n.m.","frequency":"606","arr":[["@","three","3"],["@plural","thirty","30"]]});
bank.push( {"word":"זאֹת","category":"prn.","frequency":"605","arr":[["@","this","fem. sg. this"]]});
bank.push( {"word":"רֹאשׁ","category":"n.m.","frequency":"600","arr":[["@","head"],["@","beginning"],["@","chief"]]});
bank.push( {"word":"שִׂים","category":"vb.","frequency":"588","arr":[["@","put","to put"],["@","place","to place"],["@","set","to set"]]});
bank.push( {"word":"בַּת","category":"n.f.","frequency":"587","arr":[["@","daughter","daughter of","daughter (of)"]]});
bank.push( {"word":"מַיִם","category":"n.m.","frequency":"585","arr":[["@","water","waters","water(s)"]]});
bank.push( {"word":"מֵאָה","category":"n.m.","frequency":"583","arr":[["@","hundred","100"]]});
bank.push( {"word":"כֹּה","category":"adv.","frequency":"577","arr":[["@","thus"],["@","here"]]});
bank.push( {"word":"מַה־ ּ/ מָה/ מֶה","category":"prn.","frequency":"571","arr":[["@","what","what?","what!"]]});
bank.push( {"word":"הֵם","category":"prn.","frequency":"565","arr":[["@","they","masc. pl. they"]]});
bank.push( {"word":"גּוֹי","category":"n.m.","frequency":"560","arr":[["@","nation"],["@","people"]]});
bank.push( {"word":"הַר","category":"n.m.","frequency":"558","arr":[["@","mountain"],["@","hill country"]]});
bank.push( {"word":"עָבַר","category":"vb.","frequency":"553","arr":[["@","pass over","to pass over"],["@","pass through","to pass through"],["@","pass by","to pass by"]]});
bank.push( {"word":"אָדָם","category":"n.m.","frequency":"551","arr":[["@","humankind"],["@","man","a man"],["@","person"]]});
bank.push( {"word":"טוֹב","category":"adj.","frequency":"530","arr":[["@","good"]]});
bank.push( {"word":"גָּדוֹל","category":"adj.","frequency":"527","arr":[["@","great"],["@","large"]]});
bank.push( {"word":"עָמַד","category":"vb.","frequency":"524","arr":[["@","stand","to stand"],["@","rise","to rise"]]});
bank.push( {"word":"שְׁנַיִם","category":"n.m.","frequency":"516","arr":[["@","two","2"]]});
bank.push( {"word":"כַּאֲשֶׁר","category":"cj.","frequency":"511","arr":[["@","as"],["@","just as"],["@","according as"],["@","when"]]});
bank.push( {"word":"תַּחַת","category":"prp.","frequency":"510","arr":[["@","below"],["@","under"],["@","instead of"]]});
bank.push( {"word":"חָמֵשׁ","category":"n.m.","frequency":"508","arr":[["@","five","5"],["@plural","fifty","50"]]});
bank.push( {"word":"קוֹל","category":"n.m.","frequency":"505","arr":[["@","voice"],["@","sound"]]});
bank.push( {"word":"נָכָה","category":"vb.","frequency":"501","arr":[["@Ni","be smitten","to be smitten"],["@Hi","smite","to smite"]]});
bank.push( {"word":"יָלַד","category":"vb.","frequency":"499","arr":[["@","bear","to bear","bear a child","to bear a child","bear (a child)","to bear (a child)"],["@","bring forth","to bring forth"]]});
bank.push( {"word":"פֶּה","category":"n.m.","frequency":"498","arr":[["@","mouth"]]});
bank.push( {"word":"אֶלֶף","category":"n.m.","frequency":"496","arr":[["@","thousand","1000"],["@","cattle"]]});
bank.push( {"word":"צָוַה","category":"vb.","frequency":"496","arr":[["@Pi","order","to order"],["@Pi","command","to command"],["@Pi","charge","to charge"]]});
bank.push( {"word":"הִיא","category":"prn.","frequency":"491","arr":[["@","she"]]});
bank.push( {"word":"עוֹד / עֹד","category":"adv.","frequency":"491","arr":[["@","yet"],["@","still"],["@","again"],["@concept","continuance"]]});
bank.push( {"word":"שֶׁבַע","category":"n.m.","frequency":"490","arr":[["@","seven","7"],["@plural","seventy","70"]]});
bank.push( {"word":"צָבָא","category":"n.m.","frequency":"487","arr":[["@","army"],["@","host"],["@","warfare"],["@","service"]]});
bank.push( {"word":"קֹדֶשׁ","category":"n.m.","frequency":"470","arr":[["@","holiness"],["@","sacredness"]]});
bank.push( {"word":"שָׁמַר","category":"vb.","frequency":"469","arr":[["@","guard","to guard"],["@","watch","to watch"],["@","keep","to keep"]]});
bank.push( {"word":"אַרְבַּע","category":"n.m.","frequency":"466","arr":[["@","four","4"],["@plural","forty","40"]]});
bank.push( {"word":"מָצָא","category":"vb.","frequency":"457","arr":[["@","find","to find"]]});
bank.push( {"word":"עוֹלָם","category":"n.m.","frequency":"439","arr":[["@","forever"],["@","always"],["@","ancient"]]});
bank.push( {"word":"נָפַל","category":"vb.","frequency":"435","arr":[["@","fall","to fall"],["@","get down","to get down"]]});
bank.push( {"word":"עַתָּה","category":"adv.","frequency":"435","arr":[["@","now"]]});
bank.push( {"word":"מִשְׁפָּט","category":"n.m.","frequency":"425","arr":[["@","law"],["@","custom"],["@","legal claim","legal decision","legal claim/decision","legal decision/claim"]]});
bank.push( {"word":"שָׂר","category":"n.m.","frequency":"425","arr":[["@","chief"],["@","official"],["@","prince"]]});
bank.push( {"word":"מִי","category":"prn.","frequency":"424","arr":[["@","who","who?"]]});
bank.push( {"word":"שָׁמַיִם","category":"n.m.","frequency":"421","arr":[["@","heaven","heavens"],["@","sky"]]});
bank.push( {"word":"תּוֹךְ / תָּ֑וֶךְ","category":"n.m.","frequency":"420","arr":[["@","midst of"]]});
bank.push( {"word":"רַב","category":"adj.","frequency":"419","arr":[["@","many"]]});
bank.push( {"word":"חֶרֶב","category":"n.f.","frequency":"413","arr":[["@","sword"]]});
bank.push( {"word":"בֵּין / בֵּינוֹת","category":"prp.","frequency":"409","arr":[["@","between"],["@concept","interval"]]});
bank.push( {"word":"נָא","category":"prt.","frequency":"405","arr":[["@","please"],["@concept","particle of entreaty","(particle of entreaty)"]]});
bank.push( {"word":"כֶּ֫סֶף","category":"n.m.","frequency":"403","arr":[["@","silver"],["@","money"]]});
bank.push( {"word":"מִזְבֵּחַ","category":"n.m.","frequency":"403","arr":[["@","altar"]]});
bank.push( {"word":"מָקוֹם","category":"n.m.","frequency":"401","arr":[["@","place","standing place","(standing) place"]]});
bank.push( {"word":"יָם","category":"n.m.","frequency":"396","arr":[["@","sea"],["@","west"]]});
bank.push( {"word":"זָהָב","category":"n.m.","frequency":"392","arr":[["@","gold"]]});
bank.push( {"word":"יָרַד","category":"vb.","frequency":"382","arr":[["@","go down","to go down","come down","to come down","go/come down","to go/come down"]]});
bank.push( {"word":"רוּחַ","category":"n.f.","frequency":"378","arr":[["@","spirit"],["@","breath"],["@","wind"]]});
bank.push( {"word":"בָּנָה","category":"vb.","frequency":"377","arr":[["@","build","to build"]]});
bank.push( {"word":"אֵשׁ","category":"n.f./m.","frequency":"376","arr":[["@","fire"]]});
bank.push( {"word":"נְאֻם","category":"n.m.","frequency":"376","arr":[["@","utterance"],["@","declaration"]]});
bank.push( {"word":"שַׁעַר","category":"n.m./f.","frequency":"373","arr":[["@","gate"]]});
bank.push( {"word":"נָגַד","category":"vb.","frequency":"371","arr":[["@Hi","declare","to declare"]]});
bank.push( {"word":"דָּם","category":"n.m.","frequency":"361","arr":[["@","blood"]]});
bank.push( {"word":"רָעָה","category":"n.f.","frequency":"354","arr":[["@","evil"],["@","misery"],["@","distress"]]});
bank.push( {"word":"מָלַךְ","category":"vb.","frequency":"350","arr":[["@","reign","to reign"],["@","be king","to be king","become king","to become king","be(come) king","to be(come) king"]]});
bank.push( {"word":"אֹהֶל","category":"n.m.","frequency":"348","arr":[["@","tent"]]});
bank.push( {"word":"לֶחֶם","category":"n.m.","frequency":"340","arr":[["@","bread"],["@","food"]]});
bank.push( {"word":"סָבִיב","category":"adv.","frequency":"338","arr":[["@","round about"],["@","circuit"]]});
bank.push( {"word":"אָדוֹן","category":"n.m.","frequency":"335","arr":[["@","master"],["@","superior"],["@","lord"]]});
bank.push( {"word":"עֵץ","category":"n.m.","frequency":"330","arr":[["@","tree"],["@","wood","woods","wood(s)"]]});
bank.push( {"word":"שָׂדֶה","category":"n.m.","frequency":"329","arr":[["@","field"]]});
bank.push( {"word":"בָּרַך","category":"vb.","frequency":"327","arr":[["@Pi","bless","to bless"],["@Hi","cause to kneel","to cause to kneel"]]});
bank.push( {"word":"כְּלִי","category":"n.m.","frequency":"325","arr":[["@","utensil"],["@","vessel"],["@","article"]]});
bank.push( {"word":"אוֹ","category":"cj.","frequency":"321","arr":[["@","or"]]});
bank.push( {"word":"מִלְחָמָה","category":"n.f.","frequency":"319","arr":[["@","battle"],["@","war"]]});
bank.push( {"word":"יָרֵא","category":"vb.","frequency":"317","arr":[["@","be afraid","to be afraid"]]});
bank.push( {"word":"נָבִיא","category":"n.m.","frequency":"317","arr":[["@","prophet"]]});
bank.push( {"word":"עָנָה 1","category":"vb.","frequency":"316","arr":[["@","answer","to answer"],["@","respond","to respond"]]});
bank.push( {"word":"רַע","category":"adj.","frequency":"312","arr":[["@","bad"],["@","evil"],["@substantive","distress"],["@substantive","evil"]]});
bank.push( {"word":"מֵעַל","category":"prp.","frequency":"311","arr":[["@","from upon"],["@","from","from beside","from besides","from (beside)","from (besides)"]]});
bank.push( {"word":"מִשְׁפָּחָה","category":"n.f.","frequency":"304","arr":[["@","clan"],["@","family"]]});
bank.push( {"word":"פָּקַד","category":"vb.","frequency":"304","arr":[["@","note","to note"],["@","count","to count"],["@","appoint","to appoint"],["@","attend to","to attend to","inspect","to inspect","punish","to punish","reward","to reward"],["@Hi","appoint","to appoint"],["@Ni","be noticed","to be noticed"],["@Ni","be missed","to be missed"]]});
bank.push( {"word":"מְאֹד","category":"adv.","frequency":"300","arr":[["@","very"],["@","exceedingly"],["@","quite"]]});
bank.push( {"word":"חַטָּאת","category":"n.f.","frequency":"298","arr":[["@","sin"],["@","sin offering"]]});
bank.push( {"word":"סוּר","category":"vb.","frequency":"298","arr":[["@","turn aside","to turn aside"]]});
bank.push( {"word":"עֵת","category":"n.f./m.","frequency":"297","arr":[["@","time"]]});
bank.push( {"word":"חָזַק","category":"vb.","frequency":"290","arr":[["@","be strong","to be strong","become strong","to become strong","be(come) strong","to be(come) strong"],["@","be firm","to be firm","become firm","to become firm","be(come) firm","to be(come) firm"],["@Hi","prevail","to prevail"],["@Hi","seize","to seize"]]});
bank.push( {"word":"כָּרַת","category":"vb.","frequency":"289","arr":[["@","cut","to cut","cut off","to cut off","cut down","to cut down","cut off/down","to cut off/down","cut down/off","to cut down/off"],["@","make a treaty","to make a treaty"]]});
bank.push( {"word":"עָבַד","category":"vb.","frequency":"289","arr":[["@","work","to work"],["@","serve","to serve"]]});
bank.push( {"word":"בְּרִית","category":"n.m.","frequency":"287","arr":[["@","covenant"]]});
bank.push( {"word":"עֹלָה","category":"n.f.","frequency":"286","arr":[["@","whole burnt offering"]]} );
bank.push( {"word":"אֹיֵב","category":"ptc.","frequency":"285","arr":[["@","enemy"]]});
bank.push( {"word":"אַתֶּם","category":"prn.","frequency":"283","arr":[["@","you","masc. pl. you"]]});
bank.push( {"word":"חֹדֶשׁ","category":"n.m.","frequency":"283","arr":[["@","new moon"],["@","month"]]});
bank.push( {"word":"חָיָה","category":"vb.","frequency":"283","arr":[["@","live","to live"]]});
bank.push( {"word":"קָרַב","category":"vb.","frequency":"280","arr":[["@","approach","to approach"],["@","draw near","to draw near"]]});
bank.push( {"word":"אַף 2","category":"n.m.","frequency":"277","arr":[["@","nose"],["@","anger"]]});
bank.push( {"word":"אֶבֶן","category":"n.f.","frequency":"276","arr":[["@","stone"]]});
bank.push( {"word":"פַּרְעֹה","category":"n.m.","frequency":"274","arr":[["@","Pharaoh"],["@","king","Egyptian king","(Egyptian) king"]]});
bank.push( {"word":"צֹאן","category":"n.f.","frequency":"274","arr":[["@","flock","flocks","flock(s)"],["@","small cattle","small cattle (sheep and goats)"]]});
bank.push( {"word":"שֵׁשׁ","category":"n.m.","frequency":"274","arr":[["@","six","6"],["@plural","sixty","60"]]});
bank.push( {"word":"לְמַעַן","category":"cj.","frequency":"272","arr":[["@","in order that"],["@","on account of"]]});
bank.push( {"word":"בָּשָׂר","category":"n.m.","frequency":"270","arr":[["@","flesh"],["@","meat"],["@","food"]]});
bank.push( {"word":"מִדְבָּר","category":"n.m.","frequency":"269","arr":[["@","wilderness"],["@","pasture"],["@","steppe"]]});
bank.push( {"word":"רָשָׁע","category":"adj.","frequency":"264","arr":[["@","wicked"],["@","criminal"],["@","guilty"]]});
bank.push( {"word":"אַחַת","category":"n.f.","frequency":"263","arr":[["@","one","1"]]});
bank.push( {"word":"חַי","category":"adj.","frequency":"254","arr":[["@","alive"]]});
bank.push( {"word":"שְׁתַיִם","category":"n.f.","frequency":"253","arr":[["@","two","2"]]});
bank.push( {"word":"מָטֶּה","category":"n.m.","frequency":"252","arr":[["@","staff"],["@","rod"],["@","branch"],["@","tribe"]]});
bank.push( {"word":"מָלֵא","category":"vb.","frequency":"252","arr":[["@","be full","to be full"]]});
bank.push( {"word":"רֶגֶל","category":"n.f.","frequency":"251","arr":[["@","foot"]]});
bank.push( {"word":"אַמָּה","category":"n.f.","frequency":"249","arr":[["@","cubit"],["@","forearm"]]});
bank.push( {"word":"חֶסֶד","category":"n.m.","frequency":"249","arr":[["@","loyal love"],["@","kindness"]]});
bank.push( {"word":"חַיִל","category":"n.m.","frequency":"246","arr":[["@","strength"],["@","wealth"],["@","army"]]});
bank.push( {"word":"גְּבוּל","category":"n.m.","frequency":"241","arr":[["@","border"]]});
bank.push( {"word":"חָטָא","category":"vb.","frequency":"240","arr":[["@","do wrongly","to do wrongly"],["@","sin","to sin"]]});
bank.push( {"word":"נַעַר","category":"n.m.","frequency":"240","arr":[["@","adolescent"],["@","boy"],["@","attendant"],["@","servant"]]});
bank.push( {"word":"שָׁלוֹם","category":"n.m.","frequency":"237","arr":[["@","health"],["@","wholeness"],["@","intact"],["@","sound"],["@","safety"],["@","deliverance"]]});
bank.push( {"word":"זָכַר","category":"vb.","frequency":"235","arr":[["@","remember","to remember"]]});
bank.push( {"word":"לַ֫יְלָה / לַ֫יִל","category":"n.m.","frequency":"235","arr":[["@","night"]]});
bank.push( {"word":"מַעֲשֶׂה","category":"n.m.","frequency":"235","arr":[["@","deed"],["@","work"]]});
bank.push( {"word":"עָוֹן","category":"n.m.","frequency":"233","arr":[["@","wrongdoing"],["@","guilt","guilt from","guilt (from)"],["@","punishment","punishment for iniquity","punishment (for) iniquity"]]});
bank.push( {"word":"יָרַשׁ","category":"vb.","frequency":"232","arr":[["@","take possession of","to take possession of"],["@","inherit","to inherit"],["@","dispossess","to dispossess"]]});
bank.push( {"word":"זֶרַע","category":"n.m.","frequency":"229","arr":[["@","seed"]]});
bank.push( {"word":"רָבָה","category":"vb.","frequency":"229","arr":[["@","be many","to be many","become many","to become many","be(come) many","to be(come) many"],["@","be great","to be great","become great","to become great","be(come) great","to be(come) great"]]} );
bank.push( {"word":"קֶרֶב","category":"n.m.","frequency":"227","arr":[["@","midst"],["@","inner"],["@","innards"]]});
bank.push( {"word":"בָקַשׁ","category":"vb.","frequency":"225","arr":[["@Pi","seek","to seek"]]} );
bank.push( {"word":"כָּתַב","category":"vb.","frequency":"225","arr":[["@","write","to write"]]} );
bank.push( {"word":"מוֹעֵד","category":"n.m.","frequency":"224","arr":[["@","meeting place"],["@","meeting time"],["@","assembly"],["@","festival"]]} );
bank.push( {"word":"תּוֹרָה","category":"n.f.","frequency":"223","arr":[["@","instruction"],["@","law"]]} );
bank.push( {"word":"אֲדָמָה","category":"n.f.","frequency":"222","arr":[["@","ground"],["@","earth"]]} );
bank.push( {"word":"נַחֲלָה","category":"n.f.","frequency":"222","arr":[["@","possession"],["@","property"]]} );
bank.push( {"word":"אֵם","category":"n.f.","frequency":"220","arr":[["@","mother"]]} );
bank.push( {"word":"כוּן","category":"vb.","frequency":"219","arr":[["@Ni","be firm","to be firm"],["@Ni","be prepared","to be prepared"],["@Ni","be established","to be established"],["@Hi","establish","to establish"],["@Hi","prepare","to prepare"],["@Hi","provide","to provide"]]} );
bank.push( {"word":"אָהֵב","category":"vb.","frequency":"217","arr":[["@","love","to love"]]} );
bank.push( {"word":"שָׁתָה","category":"vb.","frequency":"217","arr":[["@","drink","to drink"]]} );
bank.push( {"word":"בֶּגֶד","category":"n.m.","frequency":"216","arr":[["@","garment"]]} );
bank.push( {"word":"נָטָה","category":"vb.","frequency":"216","arr":[["@","stretch out","to stretch out"],["@","extend","to extend"],["@","bend","to bend"]]} );
bank.push( {"word":"מַחֲנֶה","category":"n.m.","frequency":"215","arr":[["@","camp"],["@","encampment"]]} );
bank.push( {"word":"עָזַב","category":"vb.","frequency":"214","arr":[["@","abandon","to abandon"],["@","forsake","to forsake"],["@","leave","to leave"]]} );
bank.push( {"word":"בֹּקֶר","category":"n.m.","frequency":"213","arr":[["@","morning"]]} );
bank.push( {"word":"יָסַף","category":"vb.","frequency":"213","arr":[["@","add","to add"],["@Hi","add to","to add to"],["@Hi","repeat","to repeat"],["@Hi","increase","to increase"]]} );
bank.push( {"word":"מַלְאָךְ","category":"n.m.","frequency":"213","arr":[["@","messenger"],["@","angel"]]} );
bank.push( {"word":"נָצַל","category":"vb.","frequency":"213","arr":[["@Ni","be delivered","to be delivered"],["@Hi","save","to save"],["@Hi","rescue","to rescue"]]} );
bank.push( {"word":"שָׁכַב","category":"vb.","frequency":"213","arr":[["@","lie down","to lie down"]]} );
bank.push( {"word":"מִנְחָה","category":"n.f.","frequency":"211","arr":[["@","gift"],["@","tribute"],["@","offering"]]} );
bank.push( {"word":"כָּלָה","category":"vb.","frequency":"207","arr":[["@","be complete","to be complete"],["@","be finished","to be finished"]]} );
bank.push( {"word":"צַדִּיק","category":"adj.","frequency":"206","arr":[["@","just"],["@","righteous"]]} );
bank.push( {"word":"יָשַׁע","category":"vb.","frequency":"205","arr":[["@Hi","deliver","to deliver"],["@Ni","be rescued","to be rescued"]]} );
bank.push( {"word":"שָׁפַט","category":"vb.","frequency":"204","arr":[["@","judge","to judge"],["@","give justice","to give justice"]]} );
bank.push( {"word":"אֲרוֹן","category":"n.m./f.","frequency":"202","arr":[["@","ark"],["@","chest"]]} );
bank.push( {"word":"לָכֵן","category":"cj.","frequency":"201","arr":[["@","therefore"]]} );
bank.push( {"word":"אָסַף","category":"vb.","frequency":"200","arr":[["@","gather","to gather"],["@","collect","to collect"],["@","remove","to remove"]]} );
bank.push( {"word":"כָּבוֹד","category":"n.m.","frequency":"200","arr":[["@","honor"],["@","glory"],["@","abundance"]]} );
bank.push( {"word":"רוּם","category":"vb.","frequency":"197","arr":[["@","be high","to be high"],["@","be exalted","to be exalted"]]} );
bank.push( {"word":"כַּף","category":"n.f.","frequency":"195","arr":[["@","palm"],["@","sole"],["@","hollow"],["@","pan"]]} );
bank.push( {"word":"יָכֹל","category":"vb.","frequency":"193","arr":[["@","be able","to be able"],["@","prevail","to prevail"],["@","endure","to endure"]]} );
bank.push( {"word":"שֶׁמֶן","category":"n.m.","frequency":"193","arr":[["@","oil"],["@","fat"]]} );
bank.push( {"word":"חָצֵר","category":"n.m.","frequency":"192","arr":[["@","court"],["@","enclosure"],["@","village"]]} );
bank.push( {"word":"סֵפֶר","category":"n.m.","frequency":"191","arr":[["@","document"],["@","book"],["@","writing"]]} );
bank.push( {"word":"בְּהֵמָה","category":"n.f.","frequency":"190","arr":[["@","beast"],["@","animals"],["@","cattle"]]} );
bank.push( {"word":"שֵׁבֶט","category":"n.m.","frequency":"190","arr":[["@","rod"],["@","tribe"],["@","staff"],["@","scepter"]]} );
bank.push( {"word":"אֹזֶן","category":"n.f.","frequency":"188","arr":[["@","ear"]]} );
bank.push( {"word":"רֵעַ","category":"n.m.","frequency":"188","arr":[["@","friend"],["@","companion"]]} );
bank.push( {"word":"גָּלָה","category":"vb.","frequency":"187","arr":[["@","uncover","to uncover"],["@","depart","to depart","depart into exile","to depart into exile","depart (into exile)","to depart (into exile)"]]} );
bank.push( {"word":"שָׁבַע","category":"vb.","frequency":"186","arr":[["@Ni","swear","to swear"],["@Ni","take an oath","to take an oath"]]} );
bank.push( {"word":"אָבַד","category":"vb.","frequency":"185","arr":[["@","perish","to perish"]]} );
bank.push( {"word":"מִצְוָה","category":"n.f.","frequency":"184","arr":[["@","commandment"]]} );
bank.push( {"word":"בָּקָר","category":"n.m.","frequency":"183","arr":[["@","cattle"],["@","herd"]]} );
bank.push( {"word":"רִאשׁוֹן","category":"adj.","frequency":"182","arr":[["@","former"],["@","first"],["@","formerly"],["@","chief"]]} );
bank.push( {"word":"זָקֵן","category":"adj.","frequency":"180","arr":[["@","old"],["@","elder"]]} );
bank.push( {"word":"מֵאֵת","category":"prp.","frequency":"180","arr":[["@","out of"],["@","from","from beside","from (beside)"]]} );
bank.push( {"word":"לָמָּה / לָמָה","category":"prn.","frequency":"178","arr":[["@","why?","why"]]} );
bank.push( {"word":"שָׂפָה","category":"n.f.","frequency":"178","arr":[["@","lip"],["@","edge"],["@","speech"]]} );
bank.push( {"word":"שָׁאַל","category":"vb.","frequency":"176","arr":[["@","ask","to ask"]]} );
bank.push( {"word":"חָוָה","category":"vb.","frequency":"173","arr":[["@Hishtaphel","bow down","to bow down"],["@Hishtaphel","worship","to worship"]]} );
bank.push( {"word":"בָּחַר","category":"vb.","frequency":"172","arr":[["@","choose","to choose"]]} );
bank.push( {"word":"אַיִל","category":"n.m.","frequency":"171","arr":[["@","ram"]]} );
bank.push( {"word":"בִּין","category":"vb.","frequency":"171","arr":[["@","understand","to understand"],["@","discern","to discern"],["@","perceive","to perceive"]]} );
bank.push( {"word":"לָחַם","category":"vb.","frequency":"@, fight, to fight","arr":[["@Ni","do battle","to do battle"]]} );
bank.push( {"word":"קָדַשׁ","category":"vb.","frequency":"171","arr":[["@","be set apart","to be set apart"],["@","be consecrated","to be consecrated"]]} );
bank.push( {"word":"דּוֹר","category":"n.m.","frequency":"167","arr":[["@","generation"]]} );
bank.push( {"word":"הָרַג","category":"vb.","frequency":"167","arr":[["@","kill","to kill"]]} );
bank.push( {"word":"מְלָאכָה","category":"n.f.","frequency":"167","arr":[["@","work"],["@","wares"],["@","craftsmanship"]]} );
bank.push( {"word":"רָעָה","category":"vb.","frequency":"167","arr":[["@","shepherd","to shepherd"],["@","pasture","to pasture"],["@","feed","to feed"]]} );
bank.push( {"word":"אַחֵר","category":"adj.","frequency":"166","arr":[["@","another"],["@","different"]]} );
bank.push( {"word":"דָּרַשׁ","category":"vb.","frequency":"165","arr":[["@","seek","to seek"],["@","resort to","to resort to"]]} );
bank.push( {"word":"חוּץ","category":"n.m.","frequency":"164","arr":[["@","the outside"],["@","a street"]]} );
bank.push( {"word":"פֶּתַח","category":"n.m.","frequency":"164","arr":[["@","doorway"],["@","opening"],["@","entrance"]]} );
bank.push( {"word":"סָבַב","category":"vb.","frequency":"163","arr":[["@","surround","to surround"],["@","turn","to turn"],["@","go around","to go around"]]} );
bank.push( {"word":"זֶבַח","category":"n.m.","frequency":"162","arr":[["@","sacrifice"]]} );
bank.push( {"word":"טָמֵא","category":"vb.","frequency":"162","arr":[["@","be unclean","to be unclean","become unclean","to become unclean","be(come) unclean","to be(come) unclean"]]} );
bank.push( {"word":"אַךְ","category":"adv.","frequency":"161","arr":[["@","surely"],["@","only"],["@","however"]]} );
bank.push( {"word":"בַּד / לְבַד","category":"n.m.","frequency":"161","arr":[["@","alone"],["@","separate"]]} );
bank.push( {"word":"בַּעַל","category":"n.m.","frequency":"161","arr":[["@","master"],["@","husband"]]} );
bank.push( {"word":"לְבַד / בַּד","category":"n.m.","frequency":"161","arr":[["@","alone"],["@","separate"]]} );
bank.push( {"word":"עַל־כֵּן","category":"cj.","frequency":"161","arr":[["@","therefore"]]} );
bank.push( {"word":"תֵּת","category":"inf.","frequency":"161","arr":[["@","give","to give"]]} );
bank.push( {"word":"גִּבּוֹר","category":"adj.","frequency":"160","arr":[["@","strong"],["@","mighty"]]} );
bank.push( {"word":"נוּס","category":"vb.","frequency":"160","arr":[["@","flee","to flee"],["@","escape","to escape"]]} );
bank.push( {"word":"עֲרָבָה","category":"n.f.","frequency":"160","arr":[["@","desert"],["@","plain"],["@","steppe"]]} );
bank.push( {"word":"צְדָקָה","category":"n.f.","frequency":"159","arr":[["@","righteousness"]]} );
bank.push( {"word":"שֶׁמֶשׁ","category":"n.m.","frequency":"158","arr":[["@","sun"]]} );
bank.push( {"word":"כִּי אִם","category":"cj.","frequency":"156","arr":[["@","except"],["@","but only"]]} );
bank.push( {"word":"שָׂמַח","category":"vb.","frequency":"156","arr":[["@","be glad","to be glad"],["@","rejoice","to rejoice"]]} );
bank.push( {"word":"שֵׁנִי","category":"adj.","frequency":"156","arr":[["@","second"]]} );
bank.push( {"word":"חָכְמָה","category":"n.f.","frequency":"153","arr":[["@","wisdom"]]} );
bank.push( {"word":"כָסָה","category":"vb.","frequency":"153","arr":[["@","cover","to cover"],["@","conceal","to conceal"]]} );
bank.push( {"word":"מָוֶת","category":"n.m.","frequency":"153","arr":[["@","death"]]} );
bank.push( {"word":"צָפוֹן","category":"n.f.","frequency":"153","arr":[["@","north"]]} );
bank.push( {"word":"שָׁחַת","category":"vb.","frequency":"152","arr":[["@Ni","be marred","to be marred"],["@Ni","be spoiled","to be spoiled"],["@Hi","act corruptly","to act corruptly"]]} );
bank.push( {"word":"נֶ֫גֶד","category":"prp.","frequency":"151","arr":[["@","in front of"],["@","opposite of"]]} );
bank.push( {"word":"נָגַע","category":"vb.","frequency":"150","arr":[["@","touch","to touch"],["@","reach","to reach"],["@","strike","to strike"]]} );
bank.push( {"word":"רֹב","category":"n.m.","frequency":"150","arr":[["@","multitude"],["@","abundance"]]} );
bank.push( {"word":"עֵדָה","category":"n.f.","frequency":"149","arr":[["@","congregation"]]} );
bank.push( {"word":"שָׂנֵא","category":"vb.","frequency":"148","arr":[["@","hate","to hate"]]} );
bank.push( {"word":"שָׁבַר","category":"vb.","frequency":"148","arr":[["@","break","to break"],["@Pi","shatter","to shatter"]]} );
bank.push( {"word":"שְׁמֹנֶה","category":"n.m.","frequency":"147","arr":[["@","eight","8"],["@plural","eighty","80"]]} );
bank.push( {"word":"הָלַל","category":"vb.","frequency":"146","arr":[["@","be boastful","to be boastful"],["@Pi","praise","to praise"]]} );
bank.push( {"word":"נָסַע","category":"vb.","frequency":"146","arr":[["@","set out","to set out"],["@","drive","to drive","drive flocks","to drive flocks","drive (flocks)","to drive (flocks)"],["@","journey","to journey"]]} );
bank.push( {"word":"עֲבֹדָה","category":"n.f.","frequency":"145","arr":[["@","service"],["@","labor"],["@","work"]]} );
bank.push( {"word":"רָדַף","category":"vb.","frequency":"144","arr":[["@","pursue","to pursue"],["@","persecute","to persecute"]]} );
bank.push( {"word":"חָנָה","category":"vb.","frequency":"143","arr":[["@","camp","to camp"],["@","bend down","to bend down"]]} );
bank.push( {"word":"שָׁ / שַׁ / שֶׁ","category":"prt.","frequency":"143","arr":[["@","who"],["@","which"],["@","that"]]} );
bank.push( {"word":"אָז","category":"adv.","frequency":"141","arr":[["@","then"],["@","at that time"],["@","thereupon"]]} );
bank.push( {"word":"יַיִן","category":"n.m.","frequency":"141","arr":[["@","wine"]]} );

bank.push( {"word":"יָמִין","category":"n.f.","frequency":"141","arr":[["@","right","right hand","right (hand)"],["@","south"]]} );
bank.push( {"word":"חַיִּים","category":"n.m.","frequency":"140","arr":[["@","life"]]} );
bank.push( {"word":"מַעַל","category":"prp.","frequency":"140","arr":[["@","upwards"],["@","above"]]} );
bank.push( {"word":"נוּחַ","category":"vb.","frequency":"140","arr":[["@","rest","to rest"]]} );
bank.push( {"word":"מִשְׁכָּן","category":"n.m.","frequency":"139","arr":[["@","dwelling","dwelling place","dwelling (place)"],["@","abode"],["@","tabernacle"]]} );
bank.push( {"word":"נְחֹשֶׁת","category":"n.m./f.","frequency":"139","arr":[["@","copper"],["@","bronze"],["@","fetter of","fetter of copper","fetter of bronze","fetter of copper/bronze"]]} );
bank.push( {"word":"חָכָם","category":"adj.","frequency":"138","arr":[["@","wise"]]} );
bank.push( {"word":"יֵשׁ","category":"subs.","frequency":"138","arr":[["@","there is"]]} );
bank.push( {"word":"סוּס","category":"n.m.","frequency":"138","arr":[["@","horse"],["@","stallion"]]} );
bank.push( {"word":"נַחַל","category":"n.m.","frequency":"137","arr":[["@","wadi"],["@","stream"],["@","valley"],["@","trench"]]} );
bank.push( {"word":"לֶכֶת","category":"inf.","frequency":"136","arr":[["@","walk","to walk"]]} );
bank.push( {"word":"פָּתַח","category":"vb.","frequency":"136","arr":[["@","open","to open"]]} );
bank.push( {"word":"קָרָא 2","category":"vb.","frequency":"136","arr":[["@","meet","to meet"],["@","encounter","to encounter"],["@","befall","to befall"],["@","happen","to happen"]]} );
bank.push( {"word":"חָלַל","category":"vb.","frequency":"135","arr":[["@Hi","begin","to begin"],["@Ni","be polluted","to be polluted"],["@Pi","defile","to defile"],["@Pu","be profaned","to be profaned"]]} );
bank.push( {"word":"כִּסֵּא","category":"n.m.","frequency":"135","arr":[["@","throne"],["@","honored seat"]]} );
bank.push( {"word":"זָבַח","category":"vb.","frequency":"134","arr":[["@","slaughter","to slaughter"],["@Pi","sacrifice","to sacrifice"]]} );
bank.push( {"word":"מִסְפָּר","category":"n.m.","frequency":"134","arr":[["@","number"],["@","recounting","retelling"]]} );
bank.push( {"word":"עֶרֶב","category":"n.m.","frequency":"134","arr":[["@","evening"],["@","night"]]} );
bank.push( {"word":"פָּנָה","category":"vb.","frequency":"134","arr":[["@","turn","to turn"],["@","look","to look"]]} );
bank.push( {"word":"אַף 1","category":"cj.","frequency":"133","arr":[["@","also"],["@","even"],["@","how much more","how much less","how much more/less","how much (more)","how much (less)","how much (more/less)"]]} );
bank.push( {"word":"חֹומָה","category":"n.f.","frequency":"133","arr":[["@","wall"]]} );
bank.push( {"word":"פֶּן","category":"cj.","frequency":"133","arr":[["@","lest"]]} );
bank.push( {"word":"פַּר","category":"n.m.","frequency":"133","arr":[["@","young bull"],["@","steer"]]} );
bank.push( {"word":"קָבַר","category":"vb.","frequency":"133","arr":[["@","bury","to bury"]]} );
bank.push( {"word":"שָׁאַר","category":"vb.","frequency":"133","arr":[["@Ni","remain","to remain"],["@Ni","be left over","to be left over"],["@Hi","leave over","to leave over"],["@Hi","spare","to spare"]]} );
bank.push( {"word":"חֹק","category":"n.m.","frequency":"131","arr":[["@","statute"],["@","decree"]]} );
bank.push( {"word":"נָשִׂיא","category":"n.m.","frequency":"130","arr":[["@","chief"],["@","prince"]]} );
bank.push( {"word":"שָׁכַן","category":"vb.","frequency":"130","arr":[["@","dwell","to dwell"],["@","settle","to settle"]]} );
bank.push( {"word":"אֱמֶת","category":"n.f.","frequency":"127","arr":[["@","truth"],["@","reliability"],["@","firmness"]]} );
bank.push( {"word":"קָבַץ","category":"vb.","frequency":"127","arr":[["@","gather","to gather"],["@","collect","to collect"],["@","assemble","to assemble"]]} );
bank.push( {"word":"כֹּחַ","category":"n.m.","frequency":"126","arr":[["@","strength"],["@","power"]]} );
bank.push( {"word":"עֶצֶם","category":"n.f.","frequency":"126","arr":[["@","bone"],["@","self"]]} );
bank.push( {"word":"בּוֹשׁ","category":"vb.","frequency":"125","arr":[["@","be ashamed","to be ashamed"]]} );
bank.push( {"word":"חֵמָה","category":"n.f.","frequency":"125","arr":[["@","heat"],["@","rage"],["@","venom"]]} );
bank.push( {"word":"חֲצִי־ / חֵצִי","category":"n.m.","frequency":"125","arr":[["@","half"]]} );
bank.push( {"word":"נָגַשׁ","category":"vb.","frequency":"125","arr":[["@","draw near","to draw near"],["@","approach","to approach"]]} );
bank.push( {"word":"שָׁלַךְ","category":"vb.","frequency":"125","arr":[["@Hi","throw","to throw"]]} );
bank.push( {"word":"חָשַׁב","category":"vb.","frequency":"124","arr":[["@","reckon","to reckon"],["@","account","to account"]]} );
bank.push( {"word":"צדֶק","category":"n.m.","frequency":"123","arr":[["@","rightness"],["@","righteousness"],["@","justice"],["@","integrity"]]} );


bank.push( {"word":"נָחַם", "category":"vb. ", "frequency":"108", "arr":[["@Ni", "be sorry", "to be sorry"],["@Ni", "to change one’s mind", "change one’s mind"],["@Pi", "to comfort", "comfort"]] } ); 

bank.push( {"word":"חַיָּה", "category":"n.f. ", "frequency":"107", "arr":[["@", "animal (living thing)"],["@", "life"]] } ); 

bank.push( {"word":"כֶּבֶשׂ", "category":"n.m. ", "frequency":"107", "arr":[["@", "lamb"]] } ); 

bank.push( {"word":"סָפַר", "category":"vb. ", "frequency":"107", "arr":[["@", "to count", "count"],["@Pi", "to recount", "recount"],["@Pi", "declare", "to declare"],["@Pi", "report", "to report"]] } ); 

bank.push( {"word":"שֹׁמֵר", "category":"ptc. ", "frequency":"107", "arr":[["@", "watchman"],["@", "watch"],["@", "guard"],["@", "keeping"]] } ); 

bank.push( {"word":"בָּמָה", "category":"n.f. ", "frequency":"106", "arr":[["@", "high place"]] } ); 

bank.push( {"word":"יָתַר", "category":"vb. ", "frequency":"106", "arr":[["@Ni", "to remain", "remain"],["@Ni", "be left over", "to be left over"],["@Hi", "to leave", "leave"],["@Hi", "leave over", "to leave over"]] } ); 










