
console.log('wordbank2.js at your service.');

var bank = [];

bank.push( {"word":"וְ/ וּ / וָ","category":"cj.","frequency":"50524","arr":[["@","and"]]});
bank.push( {"word":" ּהַ","category":"art.","frequency":"24058","arr":[["@","the"]]});
bank.push( {"word":"ל","category":"prp.","frequency":"20321","arr":[["@","to"],["@","for"],["@","regarding"],["@","belonging to"]]});
bank.push( {"word":"בּ","category":"prp.","frequency":"15559","arr":[["@","in"],["@","with"],["@","by"],["@","at"],["@","among"],["@","into"],["@","when"]]});
bank.push( {"word":"אֵ֫ת / אֶת־","category":"prt.","frequency":"10987","arr":[["@concept","direct object particle","particle indicating direct object","definite direct object marker","DDOM","ddom","D.D.O.M.","d.d.o.m."]]});
bank.push( {"word":" ּמִן / מִ","category":"prp.","frequency":"7529","arr":[["@","from"],["@","out of"],["@","since"],["@","than","more than","(more) than"]]});
bank.push( {"word":"עַל","category":"prp.","frequency":"5777","arr":[["@","on"],["@","over"],["@","against"],["@","on account of"],["@","to"]]});
bank.push( {"word":"אֶל","category":"prp.","frequency":"5518","arr":[["@","to"],["@","toward"],["@","against"],["@","at"],["@","unto"],["@","concerning"]]});
bank.push( {"word":"אֲשֶׁר","category":"prt.","frequency":"5503","arr":[["@","who"],["@","which"],["@","that"]]});
bank.push( {"word":"כֹּל","category":"n.m.","frequency":"5415","arr":[["@","all"],["@","every"],["@","whole"],["@","any"]]});
bank.push( {"word":"אָמַר","category":"vb.","frequency":"5316","arr":[["@","to say","say"]]});
bank.push( {"word":"לֹא / לוֹא","category":"prt.","frequency":"5193","arr":[["@","not","no"]]});
bank.push( {"word":"בֵּן / בֶּן","category":"n.m.","frequency":"4941","arr":[["@","son","son of","son (of)"]]});
bank.push( {"word":"כִּי","category":"cj.","frequency":"4487","arr":[["@","that"],["@","because"],["@","when"],["@","indeed"]]});
bank.push( {"word":"הָיָה","category":"vb.","frequency":"3576","arr":[["@","be","become","be(come)"],["@","happen"]]});
bank.push( {"word":"כּ","category":"prp.","frequency":"3053","arr":[["@","like"],["@","as"],["@","according to"],["@","when"]]});
bank.push( {"word":"אֵל / אֱלֹהִים","category":"n.m.","frequency":"2839","arr":[["@","God"],["@","god","gods","god(s)"]]});
bank.push( {"word":"אֵלֶּה","category":"prn.","frequency":"2839","arr":[["@","these"]]});
bank.push( {"word":"עָשָׂה","category":"vb.","frequency":"2632","arr":[["@","do","to do"],["@","make","to make"],["@","perform","to perform"]]});
bank.push( {"word":"בּוֹא","category":"vb.","frequency":"2592","arr":[["@","go in","to go in","come in","to come in","enter","to enter","come to","to come to"]]});
bank.push( {"word":"מֶלֶך","category":"n.m.","frequency":"2530","arr":[["@","king"]]});
bank.push( {"word":"אֶ֫רֶץ","category":"n.f.","frequency":"2505","arr":[["@","land"],["@","earth"],["@","ground"],["@","territory"],["@","region"]]});
bank.push( {"word":"יוֹם","category":"n.m.","frequency":"2301","arr":[["@","day"]]});
bank.push( {"word":"אִישׁ","category":"n.m.","frequency":"2199","arr":[["@","man"],["@","husband"],["@","each"]]});
bank.push( {"word":"פָּנֶה / פָּנִים","category":"n.m./f.","frequency":"2126","arr":[["@","face"]]});
bank.push( {"word":"בַּיִת","category":"n.m.","frequency":"2047","arr":[["@","house"]]});
bank.push( {"word":"נָתַן","category":"vb.","frequency":"2014","arr":[["@","give","to give"],["@","put","to put"],["@","set","to set"],["@","exchange","to exchange"],["@","grant","to grant"],["@","yield","to yield"],["@","dedicate","to dedicate"]]});
bank.push( {"word":"עָם","category":"n.m.","frequency":"1869","arr":[["@","people","a people"]]});
bank.push( {"word":"יָד","category":"n.f.","frequency":"1627","arr":[["@","hand"],["@","power"]]});
bank.push( {"word":"הָלַךְ","category":"vb.","frequency":"1554","arr":[["@","go","to go"],["@","come","to come"],["@","walk","to walk"]]});
bank.push( {"word":"דָּבָר","category":"n.m.","frequency":"1454","arr":[["@","word"],["@","matter"],["@","thing"]]});
bank.push( {"word":"הוּא","category":"prn.","frequency":"1398","arr":[["@","he"]]});
bank.push( {"word":"רָאָה","category":"vb.","frequency":"1311","arr":[["@","see","to see"]]});
bank.push( {"word":"עַד / עֲדֵי־","category":"prp.","frequency":"1263","arr":[["@","as far as"],["@","even to"],["@","until"]]});
bank.push( {"word":"אֲנִי / אָנֹכִי","category":"prn.","frequency":"1233","arr":[["@","I"]]});
bank.push( {"word":"אָב","category":"n.m.","frequency":"1210","arr":[["@","father"]]});
bank.push( {"word":"זֶה","category":"prn.","frequency":"1178","arr":[["@","this","masc. sg. this"]]});
bank.push( {"word":"שָׁמַע","category":"vb.","frequency":"1165","arr":[["@","hear","to hear"],["@","obey","to obey"]]});
bank.push( {"word":"הִנֵּה / הֵן","category":"prt.","frequency":"1147","arr":[["@","look","look!","see here","see here!","take note","take note!"]]});
bank.push( {"word":"דָּבַר","category":"vb.","frequency":"1141","arr":[["@Pi","speak","to speak"]]});
bank.push( {"word":"לִפְנֵי","category":"prp.","frequency":"1126","arr":[["@","before"],["@","in the presence of"]]});
bank.push( {"word":"יָשַׁב","category":"vb.","frequency":"1088","arr":[["@","sit","to sit"],["@","dwell","to dwell"]]});
bank.push( {"word":"עִיר","category":"n.f.","frequency":"1088","arr":[["@","city"]]} );
bank.push( {"word":"עִם","category":"prp.","frequency":"1084","arr":[["@","with"],["@","near"],["@","beside","besides"]]} );
bank.push( {"word":"יָצָא","category":"vb.","frequency":"1076","arr":[["@","go out","to go out","come out","to come out","go","come out","to go","come out"]]});
bank.push( {"word":"שׁוּב","category":"vb.","frequency":"1075","arr":[["@","turn back","to turn back"],["@","return","to return"]]});
bank.push( {"word":"אִם","category":"cj.","frequency":"1070","arr":[["@","if"],["@","when"],["@","or"]]});
bank.push( {"word":"לָקַח","category":"vb.","frequency":"976","arr":[["@","take","to take"],["@","receive","to receive"]]});
bank.push( {"word":"יָדַע","category":"vb.","frequency":"956","arr":[["@","know","to know"]]});
bank.push( {"word":"עַיִן","category":"n.f.","frequency":"900","arr":[["@","eye"],["@","appearance"],["@","spring"]]});
bank.push( {"word":"עָלָה","category":"vb.","frequency":"894","arr":[["@","go up","to go up","ascend","to ascend"]]});
bank.push( {"word":"אֵ֫ת / אֶת־","category":"prp.","frequency":"890","arr":[["@","with"],["@","beside","besides"]]});
bank.push( {"word":"שָׁנָה","category":"n.f.","frequency":"878","arr":[["@","year"]]});
bank.push( {"word":"שֵׁם","category":"n.m.","frequency":"864","arr":[["@","name"]]});
bank.push( {"word":"לֵבָב / לֵב","category":"n.m.","frequency":"854","arr":[["@","mind"],["@","heart"],["@","will"]]});
bank.push( {"word":"שָׁלַח","category":"vb.","frequency":"847","arr":[["@","send","to send"],["@","stretch out","to stretch out"]]});
bank.push( {"word":"מוּת","category":"vb.","frequency":"845","arr":[["@","die","to die"]]});
bank.push( {"word":"שָׁם","category":"adv.","frequency":"835","arr":[["@","there"]]});
bank.push( {"word":"עֶשֶׂר / עָשָׂר","category":"n.m.","frequency":"829","arr":[["@","ten","10"],["@","-teen","x-teen","*-teen","plus ten"],["@plural","twenty","20"]]});
bank.push( {"word":"אָכַל","category":"vb.","frequency":"820","arr":[["@","eat","to eat"]]});
bank.push( {"word":"עֶבֶד","category":"n.m.","frequency":"803","arr":[["@","servant"],["@","slave"]]});
bank.push( {"word":"אֵין / אַיִן","category":"subs.","frequency":"790","arr":[["@","not","there is not"]]});
bank.push( {"word":"אִשָּׁה","category":"n.f.","frequency":"781","arr":[["@","woman"],["@","wife"]]});
bank.push( {"word":"גָּם","category":"adv.","frequency":"769","arr":[["@","also"]]});
bank.push( {"word":"נֶפֶשׁ","category":"n.f.","frequency":"757","arr":[["@","self"],["@","soul"],["@","living being"],["@","breath"],["@","throat"]]});
bank.push( {"word":"כֹּהֵן","category":"n.m.","frequency":"750","arr":[["@","priest"]]});
bank.push( {"word":"אַתָּה","category":"prn.","frequency":"749","arr":[["@","you","masc. sg. you"]]});
bank.push( {"word":"כֵּן","category":"adv.","frequency":"741","arr":[["@","thus"],["@","so"]]});
bank.push( {"word":"קָרָא 1","category":"vb.","frequency":"739","arr":[["@","call","to call"],["@","proclaim","to proclaim"],["@","read aloud","to read aloud"],["@","name","to name"]]});
bank.push( {"word":"אַל","category":"adv.","frequency":"729","arr":[["@","not","no"]]});
bank.push( {"word":"אַחַר / אַחֲרֵי","category":"adv.","frequency":"718","arr":[["@","behind"],["@","after","afterwards","after(wards)","afterward","after(ward)"]]});
bank.push( {"word":"אֶחָד","category":"n.m.","frequency":"713","arr":[["@","one","1"]]});
bank.push( {"word":"דֶּרֶךְ","category":"n.m.","frequency":"712","arr":[["@","way"],["@","road"],["@","manner"]]});
bank.push( {"word":"הֲ / הַ","category":"prt.","frequency":"661","arr":[["@","?"],["@concept","interrogative particle"]]});
bank.push( {"word":"נָשָׂא","category":"vb.","frequency":"659","arr":[["@","lift","to lift"],["@","bear","to bear"],["@","carry","to carry"]]});
bank.push( {"word":"אָח","category":"n.m.","frequency":"629","arr":[["@","brother"]]});
bank.push( {"word":"קוּם","category":"vb.","frequency":"627","arr":[["@","arise","to arise"],["@","rise","to rise"],["@","stand up","to stand up","stand","to stand"]]});
bank.push( {"word":"שָׁלֹשׁ","category":"n.m.","frequency":"606","arr":[["@","three","3"],["@plural","thirty","30"]]});
bank.push( {"word":"זאֹת","category":"prn.","frequency":"605","arr":[["@","this","fem. sg. this"]]});
bank.push( {"word":"רֹאשׁ","category":"n.m.","frequency":"600","arr":[["@","head"],["@","beginning"],["@","chief"]]});
bank.push( {"word":"שִׂים","category":"vb.","frequency":"588","arr":[["@","put","to put"],["@","place","to place"],["@","set","to set"]]});
bank.push( {"word":"בַּת","category":"n.f.","frequency":"587","arr":[["@","daughter","daughter of","daughter (of)"]]});
bank.push( {"word":"מַיִם","category":"n.m.","frequency":"585","arr":[["@","water","waters","water(s)"]]});
bank.push( {"word":"מֵאָה","category":"n.m.","frequency":"583","arr":[["@","hundred","100"]]});
bank.push( {"word":"כֹּה","category":"adv.","frequency":"577","arr":[["@","thus"],["@","here"]]});
bank.push( {"word":"מַה־ ּ/ מָה/ מֶה","category":"prn.","frequency":"571","arr":[["@","what","what?","what!"]]});
bank.push( {"word":"הֵם","category":"prn.","frequency":"565","arr":[["@","they","masc. pl. they"]]});
bank.push( {"word":"גּוֹי","category":"n.m.","frequency":"560","arr":[["@","nation"],["@","people"]]});
bank.push( {"word":"הַר","category":"n.m.","frequency":"558","arr":[["@","mountain"],["@","hill country"]]});
bank.push( {"word":"עָבַר","category":"vb.","frequency":"553","arr":[["@","pass over","to pass over"],["@","pass through","to pass through"],["@","pass by","to pass by"]]});
bank.push( {"word":"אָדָם","category":"n.m.","frequency":"551","arr":[["@","humankind"],["@","man","a man"],["@","person"]]});
bank.push( {"word":"טוֹב","category":"adj.","frequency":"530","arr":[["@","good"]]});
bank.push( {"word":"גָּדוֹל","category":"adj.","frequency":"527","arr":[["@","great"],["@","large"]]});
bank.push( {"word":"עָמַד","category":"vb.","frequency":"524","arr":[["@","stand","to stand"],["@","rise","to rise"]]});
bank.push( {"word":"שְׁנַיִם","category":"n.m.","frequency":"516","arr":[["@","two","2"]]});
bank.push( {"word":"כַּאֲשֶׁר","category":"cj.","frequency":"511","arr":[["@","as"],["@","just as"],["@","according as"],["@","when"]]});
bank.push( {"word":"תַּחַת","category":"prp.","frequency":"510","arr":[["@","below"],["@","under"],["@","instead of"]]});
bank.push( {"word":"חָמֵשׁ","category":"n.m.","frequency":"508","arr":[["@","five","5"],["@plural","fifty","50"]]});
bank.push( {"word":"קוֹל","category":"n.m.","frequency":"505","arr":[["@","voice"],["@","sound"]]});
bank.push( {"word":"נָכָה","category":"vb.","frequency":"501","arr":[["@Ni","be smitten","to be smitten"],["@Hi","smite","to smite"]]});
bank.push( {"word":"יָלַד","category":"vb.","frequency":"499","arr":[["@","bear","to bear","bear a child","to bear a child","bear (a child)","to bear (a child)"],["@","bring forth","to bring forth"]]});
bank.push( {"word":"פֶּה","category":"n.m.","frequency":"498","arr":[["@","mouth"]]});
bank.push( {"word":"אֶלֶף","category":"n.m.","frequency":"496","arr":[["@","thousand","1000"],["@","cattle"]]});
bank.push( {"word":"צָוַה","category":"vb.","frequency":"496","arr":[["@Pi","order","to order"],["@Pi","command","to command"],["@Pi","charge","to charge"]]});
bank.push( {"word":"הִיא","category":"prn.","frequency":"491","arr":[["@","she"]]});
bank.push( {"word":"עוֹד / עֹד","category":"adv.","frequency":"491","arr":[["@","yet"],["@","still"],["@","again"],["@concept","continuance"]]});
bank.push( {"word":"שֶׁבַע","category":"n.m.","frequency":"490","arr":[["@","seven","7"],["@plural","seventy","70"]]});
bank.push( {"word":"צָבָא","category":"n.m.","frequency":"487","arr":[["@","army"],["@","host"],["@","warfare"],["@","service"]]});
bank.push( {"word":"קֹדֶשׁ","category":"n.m.","frequency":"470","arr":[["@","holiness"],["@","sacredness"]]});
bank.push( {"word":"שָׁמַר","category":"vb.","frequency":"469","arr":[["@","guard","to guard"],["@","watch","to watch"],["@","keep","to keep"]]});
bank.push( {"word":"אַרְבַּע","category":"n.m.","frequency":"466","arr":[["@","four","4"],["@plural","forty","40"]]});
bank.push( {"word":"מָצָא","category":"vb.","frequency":"457","arr":[["@","find","to find"]]});
bank.push( {"word":"עוֹלָם","category":"n.m.","frequency":"439","arr":[["@","forever"],["@","always"],["@","ancient"]]});
bank.push( {"word":"נָפַל","category":"vb.","frequency":"435","arr":[["@","fall","to fall"],["@","get down","to get down"]]});
bank.push( {"word":"עַתָּה","category":"adv.","frequency":"435","arr":[["@","now"]]});
bank.push( {"word":"מִשְׁפָּט","category":"n.m.","frequency":"425","arr":[["@","law"],["@","custom"],["@","legal claim","legal decision","legal claim/decision","legal decision/claim"]]});
bank.push( {"word":"שָׂר","category":"n.m.","frequency":"425","arr":[["@","chief"],["@","official"],["@","prince"]]});
bank.push( {"word":"מִי","category":"prn.","frequency":"424","arr":[["@","who","who?"]]});
bank.push( {"word":"שָׁמַיִם","category":"n.m.","frequency":"421","arr":[["@","heaven","heavens"],["@","sky"]]});
bank.push( {"word":"תּוֹךְ / תָּ֑וֶךְ","category":"n.m.","frequency":"420","arr":[["@","midst of"]]});
bank.push( {"word":"רַב","category":"adj.","frequency":"419","arr":[["@","many"]]});
bank.push( {"word":"חֶרֶב","category":"n.f.","frequency":"413","arr":[["@","sword"]]});
bank.push( {"word":"בֵּין / בֵּינוֹת","category":"prp.","frequency":"409","arr":[["@","between"],["@concept","interval"]]});
bank.push( {"word":"נָא","category":"prt.","frequency":"405","arr":[["@","please"],["@concept","particle of entreaty","(particle of entreaty)"]]});
bank.push( {"word":"כֶּ֫סֶף","category":"n.m.","frequency":"403","arr":[["@","silver"],["@","money"]]});
bank.push( {"word":"מִזְבֵּחַ","category":"n.m.","frequency":"403","arr":[["@","altar"]]});
bank.push( {"word":"מָקוֹם","category":"n.m.","frequency":"401","arr":[["@","place","standing place","(standing) place"]]});
bank.push( {"word":"יָם","category":"n.m.","frequency":"396","arr":[["@","sea"],["@","west"]]});
bank.push( {"word":"זָהָב","category":"n.m.","frequency":"392","arr":[["@","gold"]]});
bank.push( {"word":"יָרַד","category":"vb.","frequency":"382","arr":[["@","go down","to go down","come down","to come down","go/come down","to go/come down"]]});
bank.push( {"word":"רוּחַ","category":"n.f.","frequency":"378","arr":[["@","spirit"],["@","breath"],["@","wind"]]});
bank.push( {"word":"בָּנָה","category":"vb.","frequency":"377","arr":[["@","build","to build"]]});
bank.push( {"word":"אֵשׁ","category":"n.f./m.","frequency":"376","arr":[["@","fire"]]});
bank.push( {"word":"נְאֻם","category":"n.m.","frequency":"376","arr":[["@","utterance"],["@","declaration"]]});
bank.push( {"word":"שַׁעַר","category":"n.m./f.","frequency":"373","arr":[["@","gate"]]});
bank.push( {"word":"נָגַד","category":"vb.","frequency":"371","arr":[["@Hi","declare","to declare"]]});
bank.push( {"word":"דָּם","category":"n.m.","frequency":"361","arr":[["@","blood"]]});
bank.push( {"word":"רָעָה","category":"n.f.","frequency":"354","arr":[["@","evil"],["@","misery"],["@","distress"]]});
bank.push( {"word":"מָלַךְ","category":"vb.","frequency":"350","arr":[["@","reign","to reign"],["@","be king","to be king","become king","to become king","be(come) king","to be(come) king"]]});
bank.push( {"word":"אֹהֶל","category":"n.m.","frequency":"348","arr":[["@","tent"]]});
bank.push( {"word":"לֶחֶם","category":"n.m.","frequency":"340","arr":[["@","bread"],["@","food"]]});
bank.push( {"word":"סָבִיב","category":"adv.","frequency":"338","arr":[["@","round about"],["@","circuit"]]});
bank.push( {"word":"אָדוֹן","category":"n.m.","frequency":"335","arr":[["@","master"],["@","superior"],["@","lord"]]});
bank.push( {"word":"עֵץ","category":"n.m.","frequency":"330","arr":[["@","tree"],["@","wood","woods","wood(s)"]]});
bank.push( {"word":"שָׂדֶה","category":"n.m.","frequency":"329","arr":[["@","field"]]});
bank.push( {"word":"בָּרַך","category":"vb.","frequency":"327","arr":[["@Pi","bless","to bless"],["@Hi","cause to kneel","to cause to kneel"]]});
bank.push( {"word":"כְּלִי","category":"n.m.","frequency":"325","arr":[["@","utensil"],["@","vessel"],["@","article"]]});
bank.push( {"word":"אוֹ","category":"cj.","frequency":"321","arr":[["@","or"]]});
bank.push( {"word":"מִלְחָמָה","category":"n.f.","frequency":"319","arr":[["@","battle"],["@","war"]]});
bank.push( {"word":"יָרֵא","category":"vb.","frequency":"317","arr":[["@","be afraid","to be afraid"]]});
bank.push( {"word":"נָבִיא","category":"n.m.","frequency":"317","arr":[["@","prophet"]]});
bank.push( {"word":"עָנָה 1","category":"vb.","frequency":"316","arr":[["@","answer","to answer"],["@","respond","to respond"]]});
bank.push( {"word":"רַע","category":"adj.","frequency":"312","arr":[["@","bad"],["@","evil"],["@substantive","distress"],["@substantive","evil"]]});
bank.push( {"word":"מֵעַל","category":"prp.","frequency":"311","arr":[["@","from upon"],["@","from","from beside","from besides","from (beside)","from (besides)"]]});
bank.push( {"word":"מִשְׁפָּחָה","category":"n.f.","frequency":"304","arr":[["@","clan"],["@","family"]]});
bank.push( {"word":"פָּקַד","category":"vb.","frequency":"304","arr":[["@","note","to note"],["@","count","to count"],["@","appoint","to appoint"],["@","attend to","to attend to","inspect","to inspect","punish","to punish","reward","to reward"],["@Hi","appoint","to appoint"],["@Ni","be noticed","to be noticed"],["@Ni","be missed","to be missed"]]});
bank.push( {"word":"מְאֹד","category":"adv.","frequency":"300","arr":[["@","very"],["@","exceedingly"],["@","quite"]]});
bank.push( {"word":"חַטָּאת","category":"n.f.","frequency":"298","arr":[["@","sin"],["@","sin offering"]]});
bank.push( {"word":"סוּר","category":"vb.","frequency":"298","arr":[["@","turn aside","to turn aside"]]});
bank.push( {"word":"עֵת","category":"n.f./m.","frequency":"297","arr":[["@","time"]]});
bank.push( {"word":"חָזַק","category":"vb.","frequency":"290","arr":[["@","be strong","to be strong","become strong","to become strong","be(come) strong","to be(come) strong"],["@","be firm","to be firm","become firm","to become firm","be(come) firm","to be(come) firm"],["@Hi","prevail","to prevail"],["@Hi","seize","to seize"]]});
bank.push( {"word":"כָּרַת","category":"vb.","frequency":"289","arr":[["@","cut","to cut","cut off","to cut off","cut down","to cut down","cut off/down","to cut off/down","cut down/off","to cut down/off"],["@","make a treaty","to make a treaty"]]});
bank.push( {"word":"עָבַד","category":"vb.","frequency":"289","arr":[["@","work","to work"],["@","serve","to serve"]]});
bank.push( {"word":"בְּרִית","category":"n.m.","frequency":"287","arr":[["@","covenant"]]});
bank.push( {"word":"עֹלָה","category":"n.f.","frequency":"286","arr":[["@","whole burnt offering"]]} );
bank.push( {"word":"אֹיֵב","category":"ptc.","frequency":"285","arr":[["@","enemy"]]});
bank.push( {"word":"אַתֶּם","category":"prn.","frequency":"283","arr":[["@","you","masc. pl. you"]]});
bank.push( {"word":"חֹדֶשׁ","category":"n.m.","frequency":"283","arr":[["@","new moon"],["@","month"]]});
bank.push( {"word":"חָיָה","category":"vb.","frequency":"283","arr":[["@","live","to live"]]});
bank.push( {"word":"קָרַב","category":"vb.","frequency":"280","arr":[["@","approach","to approach"],["@","draw near","to draw near"]]});
bank.push( {"word":"אַף 2","category":"n.m.","frequency":"277","arr":[["@","nose"],["@","anger"]]});
bank.push( {"word":"אֶבֶן","category":"n.f.","frequency":"276","arr":[["@","stone"]]});
bank.push( {"word":"פַּרְעֹה","category":"n.m.","frequency":"274","arr":[["@","Pharaoh"],["@","king","Egyptian king","(Egyptian) king"]]});
bank.push( {"word":"צֹאן","category":"n.f.","frequency":"274","arr":[["@","flock","flocks","flock(s)"],["@","small cattle","small cattle (sheep and goats)"]]});
bank.push( {"word":"שֵׁשׁ","category":"n.m.","frequency":"274","arr":[["@","six","6"],["@plural","sixty","60"]]});
bank.push( {"word":"לְמַעַן","category":"cj.","frequency":"272","arr":[["@","in order that"],["@","on account of"]]});
bank.push( {"word":"בָּשָׂר","category":"n.m.","frequency":"270","arr":[["@","flesh"],["@","meat"],["@","food"]]});
bank.push( {"word":"מִדְבָּר","category":"n.m.","frequency":"269","arr":[["@","wilderness"],["@","pasture"],["@","steppe"]]});
bank.push( {"word":"רָשָׁע","category":"adj.","frequency":"264","arr":[["@","wicked"],["@","criminal"],["@","guilty"]]});
bank.push( {"word":"אַחַת","category":"n.f.","frequency":"263","arr":[["@","one","1"]]});
bank.push( {"word":"חַי","category":"adj.","frequency":"254","arr":[["@","alive"]]});
bank.push( {"word":"שְׁתַיִם","category":"n.f.","frequency":"253","arr":[["@","two","2"]]});
bank.push( {"word":"מָטֶּה","category":"n.m.","frequency":"252","arr":[["@","staff"],["@","rod"],["@","branch"],["@","tribe"]]});
bank.push( {"word":"מָלֵא","category":"vb.","frequency":"252","arr":[["@","be full","to be full"]]});
bank.push( {"word":"רֶגֶל","category":"n.f.","frequency":"251","arr":[["@","foot"]]});
bank.push( {"word":"אַמָּה","category":"n.f.","frequency":"249","arr":[["@","cubit"],["@","forearm"]]});
bank.push( {"word":"חֶסֶד","category":"n.m.","frequency":"249","arr":[["@","loyal love"],["@","kindness"]]});
bank.push( {"word":"חַיִל","category":"n.m.","frequency":"246","arr":[["@","strength"],["@","wealth"],["@","army"]]});
bank.push( {"word":"גְּבוּל","category":"n.m.","frequency":"241","arr":[["@","border"]]});
bank.push( {"word":"חָטָא","category":"vb.","frequency":"240","arr":[["@","do wrongly","to do wrongly"],["@","sin","to sin"]]});
bank.push( {"word":"נַעַר","category":"n.m.","frequency":"240","arr":[["@","adolescent"],["@","boy"],["@","attendant"],["@","servant"]]});
bank.push( {"word":"שָׁלוֹם","category":"n.m.","frequency":"237","arr":[["@","health"],["@","wholeness"],["@","intact"],["@","sound"],["@","safety"],["@","deliverance"]]});
bank.push( {"word":"זָכַר","category":"vb.","frequency":"235","arr":[["@","remember","to remember"]]});
bank.push( {"word":"לַ֫יְלָה / לַ֫יִל","category":"n.m.","frequency":"235","arr":[["@","night"]]});
bank.push( {"word":"מַעֲשֶׂה","category":"n.m.","frequency":"235","arr":[["@","deed"],["@","work"]]});
bank.push( {"word":"עָוֹן","category":"n.m.","frequency":"233","arr":[["@","wrongdoing"],["@","guilt","guilt from","guilt (from)"],["@","punishment","punishment for iniquity","punishment (for) iniquity"]]});
bank.push( {"word":"יָרַשׁ","category":"vb.","frequency":"232","arr":[["@","take possession of","to take possession of"],["@","inherit","to inherit"],["@","dispossess","to dispossess"]]});
bank.push( {"word":"זֶרַע","category":"n.m.","frequency":"229","arr":[["@","seed"]]});
bank.push( {"word":"רָבָה","category":"vb.","frequency":"229","arr":[["@","be many","to be many","become many","to become many","be(come) many","to be(come) many"],["@","be great","to be great","become great","to become great","be(come) great","to be(come) great"]]} );
bank.push( {"word":"קֶרֶב","category":"n.m.","frequency":"227","arr":[["@","midst"],["@","inner"],["@","innards"]]});
bank.push( {"word":"בָקַשׁ","category":"vb.","frequency":"225","arr":[["@Pi","seek","to seek"]]} );
bank.push( {"word":"כָּתַב","category":"vb.","frequency":"225","arr":[["@","write","to write"]]} );
bank.push( {"word":"מוֹעֵד","category":"n.m.","frequency":"224","arr":[["@","meeting place"],["@","meeting time"],["@","assembly"],["@","festival"]]} );
bank.push( {"word":"תּוֹרָה","category":"n.f.","frequency":"223","arr":[["@","instruction"],["@","law"]]} );
bank.push( {"word":"אֲדָמָה","category":"n.f.","frequency":"222","arr":[["@","ground"],["@","earth"]]} );
bank.push( {"word":"נַחֲלָה","category":"n.f.","frequency":"222","arr":[["@","possession"],["@","property"]]} );
bank.push( {"word":"אֵם","category":"n.f.","frequency":"220","arr":[["@","mother"]]} );
bank.push( {"word":"כוּן","category":"vb.","frequency":"219","arr":[["@Ni","be firm","to be firm"],["@Ni","be prepared","to be prepared"],["@Ni","be established","to be established"],["@Hi","establish","to establish"],["@Hi","prepare","to prepare"],["@Hi","provide","to provide"]]} );
bank.push( {"word":"אָהֵב","category":"vb.","frequency":"217","arr":[["@","love","to love"]]} );
bank.push( {"word":"שָׁתָה","category":"vb.","frequency":"217","arr":[["@","drink","to drink"]]} );
bank.push( {"word":"בֶּגֶד","category":"n.m.","frequency":"216","arr":[["@","garment"]]} );
bank.push( {"word":"נָטָה","category":"vb.","frequency":"216","arr":[["@","stretch out","to stretch out"],["@","extend","to extend"],["@","bend","to bend"]]} );
bank.push( {"word":"מַחֲנֶה","category":"n.m.","frequency":"215","arr":[["@","camp"],["@","encampment"]]} );
bank.push( {"word":"עָזַב","category":"vb.","frequency":"214","arr":[["@","abandon","to abandon"],["@","forsake","to forsake"],["@","leave","to leave"]]} );
bank.push( {"word":"בֹּקֶר","category":"n.m.","frequency":"213","arr":[["@","morning"]]} );
bank.push( {"word":"יָסַף","category":"vb.","frequency":"213","arr":[["@","add","to add"],["@Hi","add to","to add to"],["@Hi","repeat","to repeat"],["@Hi","increase","to increase"]]} );
bank.push( {"word":"מַלְאָךְ","category":"n.m.","frequency":"213","arr":[["@","messenger"],["@","angel"]]} );
bank.push( {"word":"נָצַל","category":"vb.","frequency":"213","arr":[["@Ni","be delivered","to be delivered"],["@Hi","save","to save"],["@Hi","rescue","to rescue"]]} );
bank.push( {"word":"שָׁכַב","category":"vb.","frequency":"213","arr":[["@","lie down","to lie down"]]} );
bank.push( {"word":"מִנְחָה","category":"n.f.","frequency":"211","arr":[["@","gift"],["@","tribute"],["@","offering"]]} );
bank.push( {"word":"כָּלָה","category":"vb.","frequency":"207","arr":[["@","be complete","to be complete"],["@","be finished","to be finished"]]} );
bank.push( {"word":"צַדִּיק","category":"adj.","frequency":"206","arr":[["@","just"],["@","righteous"]]} );
bank.push( {"word":"יָשַׁע","category":"vb.","frequency":"205","arr":[["@Hi","deliver","to deliver"],["@Ni","be rescued","to be rescued"]]} );
bank.push( {"word":"שָׁפַט","category":"vb.","frequency":"204","arr":[["@","judge","to judge"],["@","give justice","to give justice"]]} );
bank.push( {"word":"אֲרוֹן","category":"n.m./f.","frequency":"202","arr":[["@","ark"],["@","chest"]]} );
bank.push( {"word":"לָכֵן","category":"cj.","frequency":"201","arr":[["@","therefore"]]} );
bank.push( {"word":"אָסַף","category":"vb.","frequency":"200","arr":[["@","gather","to gather"],["@","collect","to collect"],["@","remove","to remove"]]} );
bank.push( {"word":"כָּבוֹד","category":"n.m.","frequency":"200","arr":[["@","honor"],["@","glory"],["@","abundance"]]} );
bank.push( {"word":"רוּם","category":"vb.","frequency":"197","arr":[["@","be high","to be high"],["@","be exalted","to be exalted"]]} );
bank.push( {"word":"כַּף","category":"n.f.","frequency":"195","arr":[["@","palm"],["@","sole"],["@","hollow"],["@","pan"]]} );
bank.push( {"word":"יָכֹל","category":"vb.","frequency":"193","arr":[["@","be able","to be able"],["@","prevail","to prevail"],["@","endure","to endure"]]} );
bank.push( {"word":"שֶׁמֶן","category":"n.m.","frequency":"193","arr":[["@","oil"],["@","fat"]]} );
bank.push( {"word":"חָצֵר","category":"n.m.","frequency":"192","arr":[["@","court"],["@","enclosure"],["@","village"]]} );
bank.push( {"word":"סֵפֶר","category":"n.m.","frequency":"191","arr":[["@","document"],["@","book"],["@","writing"]]} );
bank.push( {"word":"בְּהֵמָה","category":"n.f.","frequency":"190","arr":[["@","beast"],["@","animals"],["@","cattle"]]} );
bank.push( {"word":"שֵׁבֶט","category":"n.m.","frequency":"190","arr":[["@","rod"],["@","tribe"],["@","staff"],["@","scepter"]]} );
bank.push( {"word":"אֹזֶן","category":"n.f.","frequency":"188","arr":[["@","ear"]]} );
bank.push( {"word":"רֵעַ","category":"n.m.","frequency":"188","arr":[["@","friend"],["@","companion"]]} );
bank.push( {"word":"גָּלָה","category":"vb.","frequency":"187","arr":[["@","uncover","to uncover"],["@","depart","to depart","depart into exile","to depart into exile","depart (into exile)","to depart (into exile)"]]} );
bank.push( {"word":"שָׁבַע","category":"vb.","frequency":"186","arr":[["@Ni","swear","to swear"],["@Ni","take an oath","to take an oath"]]} );
bank.push( {"word":"אָבַד","category":"vb.","frequency":"185","arr":[["@","perish","to perish"]]} );
bank.push( {"word":"מִצְוָה","category":"n.f.","frequency":"184","arr":[["@","commandment"]]} );
bank.push( {"word":"בָּקָר","category":"n.m.","frequency":"183","arr":[["@","cattle"],["@","herd"]]} );
bank.push( {"word":"רִאשׁוֹן","category":"adj.","frequency":"182","arr":[["@","former"],["@","first"],["@","formerly"],["@","chief"]]} );
bank.push( {"word":"זָקֵן","category":"adj.","frequency":"180","arr":[["@","old"],["@","elder"]]} );
bank.push( {"word":"מֵאֵת","category":"prp.","frequency":"180","arr":[["@","out of"],["@","from","from beside","from (beside)"]]} );
bank.push( {"word":"לָמָּה / לָמָה","category":"prn.","frequency":"178","arr":[["@","why?","why"]]} );
bank.push( {"word":"שָׂפָה","category":"n.f.","frequency":"178","arr":[["@","lip"],["@","edge"],["@","speech"]]} );
bank.push( {"word":"שָׁאַל","category":"vb.","frequency":"176","arr":[["@","ask","to ask"]]} );
bank.push( {"word":"חָוָה","category":"vb.","frequency":"173","arr":[["@Hishtaphel","bow down","to bow down"],["@Hishtaphel","worship","to worship"]]} );
bank.push( {"word":"בָּחַר","category":"vb.","frequency":"172","arr":[["@","choose","to choose"]]} );
bank.push( {"word":"אַיִל","category":"n.m.","frequency":"171","arr":[["@","ram"]]} );
bank.push( {"word":"בִּין","category":"vb.","frequency":"171","arr":[["@","understand","to understand"],["@","discern","to discern"],["@","perceive","to perceive"]]} );
bank.push( {"word":"לָחַם","category":"vb.","frequency":"@, fight, to fight","arr":[["@Ni","do battle","to do battle"]]} );
bank.push( {"word":"קָדַשׁ","category":"vb.","frequency":"171","arr":[["@","be set apart","to be set apart"],["@","be consecrated","to be consecrated"]]} );
bank.push( {"word":"דּוֹר","category":"n.m.","frequency":"167","arr":[["@","generation"]]} );
bank.push( {"word":"הָרַג","category":"vb.","frequency":"167","arr":[["@","kill","to kill"]]} );
bank.push( {"word":"מְלָאכָה","category":"n.f.","frequency":"167","arr":[["@","work"],["@","wares"],["@","craftsmanship"]]} );
bank.push( {"word":"רָעָה","category":"vb.","frequency":"167","arr":[["@","shepherd","to shepherd"],["@","pasture","to pasture"],["@","feed","to feed"]]} );
bank.push( {"word":"אַחֵר","category":"adj.","frequency":"166","arr":[["@","another"],["@","different"]]} );
bank.push( {"word":"דָּרַשׁ","category":"vb.","frequency":"165","arr":[["@","seek","to seek"],["@","resort to","to resort to"]]} );
bank.push( {"word":"חוּץ","category":"n.m.","frequency":"164","arr":[["@","the outside"],["@","a street"]]} );
bank.push( {"word":"פֶּתַח","category":"n.m.","frequency":"164","arr":[["@","doorway"],["@","opening"],["@","entrance"]]} );
bank.push( {"word":"סָבַב","category":"vb.","frequency":"163","arr":[["@","surround","to surround"],["@","turn","to turn"],["@","go around","to go around"]]} );
bank.push( {"word":"זֶבַח","category":"n.m.","frequency":"162","arr":[["@","sacrifice"]]} );
bank.push( {"word":"טָמֵא","category":"vb.","frequency":"162","arr":[["@","be unclean","to be unclean","become unclean","to become unclean","be(come) unclean","to be(come) unclean"]]} );
bank.push( {"word":"אַךְ","category":"adv.","frequency":"161","arr":[["@","surely"],["@","only"],["@","however"]]} );
bank.push( {"word":"בַּד / לְבַד","category":"n.m.","frequency":"161","arr":[["@","alone"],["@","separate"]]} );
bank.push( {"word":"בַּעַל","category":"n.m.","frequency":"161","arr":[["@","master"],["@","husband"]]} );
bank.push( {"word":"לְבַד / בַּד","category":"n.m.","frequency":"161","arr":[["@","alone"],["@","separate"]]} );
bank.push( {"word":"עַל־כֵּן","category":"cj.","frequency":"161","arr":[["@","therefore"]]} );
bank.push( {"word":"תֵּת","category":"inf.","frequency":"161","arr":[["@","give","to give"]]} );
bank.push( {"word":"גִּבּוֹר","category":"adj.","frequency":"160","arr":[["@","strong"],["@","mighty"]]} );
bank.push( {"word":"נוּס","category":"vb.","frequency":"160","arr":[["@","flee","to flee"],["@","escape","to escape"]]} );
bank.push( {"word":"עֲרָבָה","category":"n.f.","frequency":"160","arr":[["@","desert"],["@","plain"],["@","steppe"]]} );
bank.push( {"word":"צְדָקָה","category":"n.f.","frequency":"159","arr":[["@","righteousness"]]} );
bank.push( {"word":"שֶׁמֶשׁ","category":"n.m.","frequency":"158","arr":[["@","sun"]]} );
bank.push( {"word":"כִּי אִם","category":"cj.","frequency":"156","arr":[["@","except"],["@","but only"]]} );
bank.push( {"word":"שָׂמַח","category":"vb.","frequency":"156","arr":[["@","be glad","to be glad"],["@","rejoice","to rejoice"]]} );
bank.push( {"word":"שֵׁנִי","category":"adj.","frequency":"156","arr":[["@","second"]]} );
bank.push( {"word":"חָכְמָה","category":"n.f.","frequency":"153","arr":[["@","wisdom"]]} );
bank.push( {"word":"כָסָה","category":"vb.","frequency":"153","arr":[["@","cover","to cover"],["@","conceal","to conceal"]]} );
bank.push( {"word":"מָוֶת","category":"n.m.","frequency":"153","arr":[["@","death"]]} );
bank.push( {"word":"צָפוֹן","category":"n.f.","frequency":"153","arr":[["@","north"]]} );
bank.push( {"word":"שָׁחַת","category":"vb.","frequency":"152","arr":[["@Ni","be marred","to be marred"],["@Ni","be spoiled","to be spoiled"],["@Hi","act corruptly","to act corruptly"]]} );
bank.push( {"word":"נֶ֫גֶד","category":"prp.","frequency":"151","arr":[["@","in front of"],["@","opposite of"]]} );
bank.push( {"word":"נָגַע","category":"vb.","frequency":"150","arr":[["@","touch","to touch"],["@","reach","to reach"],["@","strike","to strike"]]} );
bank.push( {"word":"רֹב","category":"n.m.","frequency":"150","arr":[["@","multitude"],["@","abundance"]]} );
bank.push( {"word":"עֵדָה","category":"n.f.","frequency":"149","arr":[["@","congregation"]]} );
bank.push( {"word":"שָׂנֵא","category":"vb.","frequency":"148","arr":[["@","hate","to hate"]]} );
bank.push( {"word":"שָׁבַר","category":"vb.","frequency":"148","arr":[["@","break","to break"],["@Pi","shatter","to shatter"]]} );
bank.push( {"word":"שְׁמֹנֶה","category":"n.m.","frequency":"147","arr":[["@","eight","8"],["@plural","eighty","80"]]} );
bank.push( {"word":"הָלַל","category":"vb.","frequency":"146","arr":[["@","be boastful","to be boastful"],["@Pi","praise","to praise"]]} );
bank.push( {"word":"נָסַע","category":"vb.","frequency":"146","arr":[["@","set out","to set out"],["@","drive","to drive","drive flocks","to drive flocks","drive (flocks)","to drive (flocks)"],["@","journey","to journey"]]} );
bank.push( {"word":"עֲבֹדָה","category":"n.f.","frequency":"145","arr":[["@","service"],["@","labor"],["@","work"]]} );
bank.push( {"word":"רָדַף","category":"vb.","frequency":"144","arr":[["@","pursue","to pursue"],["@","persecute","to persecute"]]} );
bank.push( {"word":"חָנָה","category":"vb.","frequency":"143","arr":[["@","camp","to camp"],["@","bend down","to bend down"]]} );
bank.push( {"word":"שָׁ / שַׁ / שֶׁ","category":"prt.","frequency":"143","arr":[["@","who"],["@","which"],["@","that"]]} );
bank.push( {"word":"אָז","category":"adv.","frequency":"141","arr":[["@","then"],["@","at that time"],["@","thereupon"]]} );
bank.push( {"word":"יַיִן","category":"n.m.","frequency":"141","arr":[["@","wine"]]} );
bank.push( {"word":"יָמִין","category":"n.f.","frequency":"141","arr":[["@","right","right hand","right (hand)"],["@","south"]]} );
bank.push( {"word":"חַיִּים","category":"n.m.","frequency":"140","arr":[["@","life"]]} );
bank.push( {"word":"מַעַל","category":"prp.","frequency":"140","arr":[["@","upwards"],["@","above"]]} );
bank.push( {"word":"נוּחַ","category":"vb.","frequency":"140","arr":[["@","rest","to rest"]]} );
bank.push( {"word":"מִשְׁכָּן","category":"n.m.","frequency":"139","arr":[["@","dwelling","dwelling place","dwelling (place)"],["@","abode"],["@","tabernacle"]]} );
bank.push( {"word":"נְחֹשֶׁת","category":"n.m./f.","frequency":"139","arr":[["@","copper"],["@","bronze"],["@","fetter of","fetter of copper","fetter of bronze","fetter of copper/bronze"]]} );
bank.push( {"word":"חָכָם","category":"adj.","frequency":"138","arr":[["@","wise"]]} );
bank.push( {"word":"יֵשׁ","category":"subs.","frequency":"138","arr":[["@","there is"]]} );
bank.push( {"word":"סוּס","category":"n.m.","frequency":"138","arr":[["@","horse"],["@","stallion"]]} );
bank.push( {"word":"נַחַל","category":"n.m.","frequency":"137","arr":[["@","wadi"],["@","stream"],["@","valley"],["@","trench"]]} );
bank.push( {"word":"לֶכֶת","category":"inf.","frequency":"136","arr":[["@","walk","to walk"]]} );
bank.push( {"word":"פָּתַח","category":"vb.","frequency":"136","arr":[["@","open","to open"]]} );
bank.push( {"word":"קָרָא 2","category":"vb.","frequency":"136","arr":[["@","meet","to meet"],["@","encounter","to encounter"],["@","befall","to befall"],["@","happen","to happen"]]} );
bank.push( {"word":"חָלַל","category":"vb.","frequency":"135","arr":[["@Hi","begin","to begin"],["@Ni","be polluted","to be polluted"],["@Pi","defile","to defile"],["@Pu","be profaned","to be profaned"]]} );
bank.push( {"word":"כִּסֵּא","category":"n.m.","frequency":"135","arr":[["@","throne"],["@","honored seat"]]} );
bank.push( {"word":"זָבַח","category":"vb.","frequency":"134","arr":[["@","slaughter","to slaughter"],["@Pi","sacrifice","to sacrifice"]]} );
bank.push( {"word":"מִסְפָּר","category":"n.m.","frequency":"134","arr":[["@","number"],["@","recounting","retelling"]]} );
bank.push( {"word":"עֶרֶב","category":"n.m.","frequency":"134","arr":[["@","evening"],["@","night"]]} );
bank.push( {"word":"פָּנָה","category":"vb.","frequency":"134","arr":[["@","turn","to turn"],["@","look","to look"]]} );
bank.push( {"word":"אַף 1","category":"cj.","frequency":"133","arr":[["@","also"],["@","even"],["@","how much more","how much less","how much more/less","how much (more)","how much (less)","how much (more/less)"]]} );
bank.push( {"word":"חֹומָה","category":"n.f.","frequency":"133","arr":[["@","wall"]]} );
bank.push( {"word":"פֶּן","category":"cj.","frequency":"133","arr":[["@","lest"]]} );
bank.push( {"word":"פַּר","category":"n.m.","frequency":"133","arr":[["@","young bull"],["@","steer"]]} );
bank.push( {"word":"קָבַר","category":"vb.","frequency":"133","arr":[["@","bury","to bury"]]} );
bank.push( {"word":"שָׁאַר","category":"vb.","frequency":"133","arr":[["@Ni","remain","to remain"],["@Ni","be left over","to be left over"],["@Hi","leave over","to leave over"],["@Hi","spare","to spare"]]} );
bank.push( {"word":"חֹק","category":"n.m.","frequency":"131","arr":[["@","statute"],["@","decree"]]} );
bank.push( {"word":"נָשִׂיא","category":"n.m.","frequency":"130","arr":[["@","chief"],["@","prince"]]} );
bank.push( {"word":"שָׁכַן","category":"vb.","frequency":"130","arr":[["@","dwell","to dwell"],["@","settle","to settle"]]} );
bank.push( {"word":"אֱמֶת","category":"n.f.","frequency":"127","arr":[["@","truth"],["@","reliability"],["@","firmness"]]} );
bank.push( {"word":"קָבַץ","category":"vb.","frequency":"127","arr":[["@","gather","to gather"],["@","collect","to collect"],["@","assemble","to assemble"]]} );
bank.push( {"word":"כֹּחַ","category":"n.m.","frequency":"126","arr":[["@","strength"],["@","power"]]} );
bank.push( {"word":"עֶצֶם","category":"n.f.","frequency":"126","arr":[["@","bone"],["@","self"]]} );
bank.push( {"word":"בּוֹשׁ","category":"vb.","frequency":"125","arr":[["@","be ashamed","to be ashamed"]]} );
bank.push( {"word":"חֵמָה","category":"n.f.","frequency":"125","arr":[["@","heat"],["@","rage"],["@","venom"]]} );
bank.push( {"word":"חֲצִי־ / חֵצִי","category":"n.m.","frequency":"125","arr":[["@","half"]]} );
bank.push( {"word":"נָגַשׁ","category":"vb.","frequency":"125","arr":[["@","draw near","to draw near"],["@","approach","to approach"]]} );
bank.push( {"word":"שָׁלַךְ","category":"vb.","frequency":"125","arr":[["@Hi","throw","to throw"]]} );
bank.push( {"word":"חָשַׁב","category":"vb.","frequency":"124","arr":[["@","reckon","to reckon"],["@","account","to account"]]} );
bank.push( {"word":"צֶדֶק", "category":"n.m. ", "frequency":"123", "arr":[["@", "rightness"],["@", "righteousness"],["@", "justice"],["@", "integrity"]] } ); 
bank.push( {"word":"קָהָל", "category":"n.m. ", "frequency":"123", "arr":[["@", "assembly"],["@", "company"],["@", "congregation"]] } ); 
bank.push( {"word":"אֲנַחְנוּ", "category":"prn. ", "frequency":"121", "arr":[["@", "we"]] } ); 
bank.push( {"word":"לָכַד", "category":"vb. ", "frequency":"121", "arr":[["@", "to capture", "capture"],["@", "seize", "to seize"],["@", "take", "to take"]] } ); 
bank.push( {"word":"אוֹר", "category":"n.f. ", "frequency":"120", "arr":[["@", "light"]] } ); 
bank.push( {"word":"בָּטַח", "category":"vb. ", "frequency":"120", "arr":[["@", "to trust", "trust"],["@", "be confident in", "to be confident in"]] } ); 
bank.push( {"word":"בְּכוֹר", "category":"n.m. ", "frequency":"120", "arr":[["@", "firstborn"]] } ); 
bank.push( {"word":"רֶכֶב", "category":"n.m. ", "frequency":"120", "arr":[["@", "chariot"],["@", "chariotry"],["@", "upper millstone"]] } ); 
bank.push( {"word":"אָחוֹת", "category":"n.f. ", "frequency":"119", "arr":[["@", "sister"]] } ); 
bank.push( {"word":"יָשָׁר", "category":"adj. ", "frequency":"119", "arr":[["@", "straight"],["@", "right"]] } ); 
bank.push( {"word":"נָהָר", "category":"n.m. ", "frequency":"119", "arr":[["@", "stream"],["@", "river"]] } ); 
bank.push( {"word":"פְּרִי", "category":"n.m. ", "frequency":"119", "arr":[["@", "fruit"]] } ); 
bank.push( {"word":"פַּעַם", "category":"n.f. ", "frequency":"118", "arr":[["@", "step"],["@", "pace"],["@", "once"],["@", "occasion"]] } ); 
bank.push( {"word":"תּוֹעֵבָה", "category":"n.f. ", "frequency":"118", "arr":[["@", "abhorrence"],["@", "disgust"],["@", "abomination"]] } ); 
bank.push( {"word":"גָּדַל", "category":"vb. ", "frequency":"117", "arr":[["@", "to grow", "grow"],["@", "become great", "to become great"]] } ); 
bank.push( {"word":"יָטַב", "category":"vb. ", "frequency":"117", "arr":[["@", "be good", "to be good"],["@", "be pleasing", "to be pleasing"]] } ); 
bank.push( {"word":"לָשׁוֹן", "category":"n.m/f. ", "frequency":"117", "arr":[["@", "tongue"],["@", "language"]] } ); 
bank.push( {"word":"מַמְלָכָה", "category":"n.f. ", "frequency":"117", "arr":[["@", "kingdom"],["@", "dominion"]] } ); 
bank.push( {"word":"קָדוֹשׁ", "category":"adj. ", "frequency":"117", "arr":[["@", "holy"]] } ); 
bank.push( {"word":"שָׂרַף", "category":"vb. ", "frequency":"117", "arr":[["@", "to burn", "burn"]] } ); 
bank.push( {"word":"שָׁפַךְ", "category":"vb. ", "frequency":"117", "arr":[["@", "pour", "to pour", "pour out", "to pour out", "pour (out)", "to pour (out)"]] } ); 
bank.push( {"word":"שָׁלַם", "category":"vb. ", "frequency":"116", "arr":[["@", "be complete", "to be complete"],["@", "be sound", "to be sound"]] } ); 
bank.push( {"word":"נָבַא", "category":"vb. ", "frequency":"115", "arr":[["@Ni", "to prophesy", "prophesy"],["@Hi", "to prophesy", "prophesy"]] } ); 
bank.push( {"word":"קָטַר", "category":"vb. ", "frequency":"115", "arr":[["@Pi", "to make a sacrifice", "make a sacrifice"],["@Pi", "to make go up in smoke", "make go up in smoke"]] } ); 
bank.push( {"word":"בָּכָה", "category":"vb. ", "frequency":"114", "arr":[["@", "to weep", "weep"]] } ); 
bank.push( {"word":"כָּבֵד", "category":"vb. ", "frequency":"114", "arr":[["@", "be honored", "to be honored"],["@", "be heavy", "to be heavy"],["@", "be weighty", "to be weighty"]] } ); 
bank.push( {"word":"מִגְרָשׁ", "category":"n.m. ", "frequency":"114", "arr":[["@", "pastureland"],["@", "outskirts"]] } ); 
bank.push( {"word":"שֶׁקֶר", "category":"n.m. ", "frequency":"113", "arr":[["@", "deception"],["@", "falsehood"]] } ); 
bank.push( {"word":"בִּלְתִּי", "category":"adv. ", "frequency":"112", "arr":[["@", "except"],["@", "not"],["@", "so as not to"]] } ); 
bank.push( {"word":"לָבַשׁ", "category":"vb. ", "frequency":"112", "arr":[["@", "to put on", "put on"],["@", "wear", "to wear"],["@", "be clothed", "to be clothed"]] } ); 
bank.push( {"word":"נֶגֶב", "category":"n.m. ", "frequency":"112", "arr":[["@", "south"],["@", "Negev"]] } ); 
bank.push( {"word":"עַמּוּד", "category":"n.m. ", "frequency":"112", "arr":[["@", "pillar"],["@", "column"]] } ); 
bank.push( {"word":"יָדָה", "category":"vb. ", "frequency":"111", "arr":[["@", "to shoot", "shoot"],["@Pi", "to cast", "cast"],["@Hit", "to confess", "confess"],["@Hit", "praise", "to praise"],["@Hi", "to laud", "laud"],["@Hi", "praise", "to praise"]] } ); 
bank.push( {"word":"כָּנָף", "category":"n.f. ", "frequency":"111", "arr":[["@", "wing"],["@", "skirt"],["@", "corner"]] } ); 
bank.push( {"word":"שַׁבָּת", "category":"n.f/m. ", "frequency":"111", "arr":[["@", "rest"],["@", "Sabbath"]] } ); 
bank.push( {"word":"עָפָר", "category":"n.m. ", "frequency":"110", "arr":[["@", "dust"],["@", "dry earth"]] } ); 
bank.push( {"word":"רַק", "category":"adv. ", "frequency":"109", "arr":[["@", "only"],["@", "surely"]] } ); 
bank.push( {"word":"נָחַם", "category":"vb. ", "frequency":"108", "arr":[["@Ni", "be sorry", "to be sorry"],["@Ni", "to change one’s mind", "change one’s mind"],["@Pi", "to comfort", "comfort"]] } ); 
bank.push( {"word":"חַיָּה", "category":"n.f. ", "frequency":"107", "arr":[["@", "animal"],["@", "living thing"],["@", "life"]] } ); 
bank.push( {"word":"כֶּבֶשׂ", "category":"n.m. ", "frequency":"107", "arr":[["@", "lamb"]] } ); 
bank.push( {"word":"סָפַר", "category":"vb. ", "frequency":"107", "arr":[["@", "to count", "count"],["@Pi", "to recount", "recount"],["@Pi", "declare", "to declare"],["@Pi", "report", "to report"]] } ); 
bank.push( {"word":"שֹׁמֵר", "category":"ptc. ", "frequency":"107", "arr":[["@", "watchman"],["@", "watch"],["@", "guard"],["@", "keeping"]] } ); 
bank.push( {"word":"בָּמָה", "category":"n.f. ", "frequency":"106", "arr":[["@", "high place"]] } ); 
bank.push( {"word":"יָתַר", "category":"vb. ", "frequency":"106", "arr":[["@Ni", "to remain", "remain"],["@Ni", "be left over", "to be left over"],["@Hi", "to leave", "leave"],["@Hi", "leave over", "to leave over"]] } ); 
bank.push( {"word":"בְּעַד", "category":"prp. ", "frequency":"104", "arr":[["@", "through"],["@", "on behalf of"],["@", "behind"]] } ); 
bank.push( {"word":"גָּאַל", "category":"vb. ", "frequency":"104", "arr":[["@", "to redeem", "redeem"],["@", "act as kinsman", "to act as kinsman"]] } ); 
bank.push( {"word":"חֻקָּה", "category":"n.f. ", "frequency":"104", "arr":[["@", "statute"],["@", "enactment"]] } ); 
bank.push( {"word":"רוּץ", "category":"vb. ", "frequency":"104", "arr":[["@", "to run", "run"]] } ); 
bank.push( {"word":"תָּמִיד", "category":"n.m. ", "frequency":"104", "arr":[["@", "continually"],["@", "on-going"],["@", "lasting"]] } ); 
bank.push( {"word":"מַרְאֶה", "category":"n.m. ", "frequency":"103", "arr":[["@", "vision"],["@", "appearance"],["@", "sight"]] } ); 
bank.push( {"word":"כָּפַר", "category":"vb. ", "frequency":"102", "arr":[["@", "to cover", "cover"],["@Pi", "to cover over", "cover over"],["@Pi", "pacify", "to pacify"],["@Pi", "atone for", "to atone for"]] } ); 
bank.push( {"word":"שָׁכַח", "category":"vb. ", "frequency":"102", "arr":[["@", "to forget", "forget"]] } ); 
bank.push( {"word":"מְעַט", "category":"subst. ", "frequency":"101", "arr":[["@", "a little"],["@", "small"],["@", "few"]] } ); 
bank.push( {"word":"רֹחַב", "category":"n.m. ", "frequency":"101", "arr":[["@", "breadth"],["@", "width"]] } ); 
bank.push( {"word":"רָעָב", "category":"n.m. ", "frequency":"101", "arr":[["@", "famine"],["@", "hunger"]] } ); 
bank.push( {"word":"יַעַן", "category":"cj. ", "frequency":"100", "arr":[["@", "on account of"]] } ); 
bank.push( {"word":"רֹעֶה", "category":"ptc. ", "frequency":"100", "arr":[["@", "shepherd"]] } ); 
bank.push( {"word":"עוֹר", "category":"n.m. ", "frequency":"99", "arr":[["@", "skin"],["@", "hide"],["@", "leather"]] } ); 
bank.push( {"word":"רָעַע", "category":"vb. ", "frequency":"98", "arr":[["@", "be evil", "to be evil"],["@", "do evil", "to do evil"],["@", "be displeasing", "to be displeasing"],["@", "be harmful", "to be harmful"]] } ); 
bank.push( {"word":"שָׁרַת", "category":"vb. ", "frequency":"98", "arr":[["@Pi", "to minister", "minister"],["@Pi", "serve", "to serve"]] } ); 
bank.push( {"word":"אָמַן", "category":"vb. ", "frequency":"97", "arr":[["@Hi", "to believe in", "believe in"],["@Ni", "to prove reliable", "prove reliable"],["@Ni", "prove faithful", "to prove faithful"]] } ); 
bank.push( {"word":"יֶתֶר", "category":"n.m. ", "frequency":"97", "arr":[["@", "remainder"],["@", "excess"]] } ); 
bank.push( {"word":"שָׂבַע", "category":"vb. ", "frequency":"97", "arr":[["@", "be sated", "to be sated"],["@", "be satisfied", "to be satisfied"]] } ); 
bank.push( {"word":"חֲמוֹר", "category":"n.m. ", "frequency":"96", "arr":[["@", "male donkey"]] } ); 
bank.push( {"word":"טָהוֹר", "category":"adj. ", "frequency":"96", "arr":[["@", "clean"],["@", "pure"]] } ); 
bank.push( {"word":"יַחְדָּו", "category":"adv. ", "frequency":"96", "arr":[["@", "together"]] } ); 
bank.push( {"word":"אֹרֶךְ", "category":"n.m. ", "frequency":"95", "arr":[["@", "length"]] } ); 
bank.push( {"word":"הָפַךְ", "category":"vb. ", "frequency":"95", "arr":[["@", "to turn", "turn"],["@", "overturn", "to overturn"],["@", "change", "to change"]] } ); 
bank.push( {"word":"חָלָל", "category":"adj. ", "frequency":"94", "arr":[["@", "pierced"],["@", "fatally wounded"],["@", "slain"]] } ); 
bank.push( {"word":"טָהֵר", "category":"vb. ", "frequency":"94", "arr":[["@", "be clean", "to be clean"],["@", "be pure", "to be pure"]] } ); 
bank.push( {"word":"כֶּרֶם", "category":"n.m/f. ", "frequency":"94", "arr":[["@", "vineyard"]] } ); 
bank.push( {"word":"מָלַט", "category":"vb. ", "frequency":"94", "arr":[["@Ni", "to escape", "escape"],["@Ni", "be delivered", "to be delivered"],["@Hi", "to deliver", "deliver"],["@Hi", "to birth", "birth"]] } ); 
bank.push( {"word":"שִׂמְחָה", "category":"n.f. ", "frequency":"94", "arr":[["@", "joy"],["@", "gladness"]] } ); 
bank.push( {"word":"חָרָה", "category":"vb. ", "frequency":"93", "arr":[["@", "to burn", "burn"],["@", "be kindled", "to be kindled"],["@", "be angry", "to be angry"],["@", "be upset", "to be upset"]] } ); 
bank.push( {"word":"פֶּשַׁע", "category":"n.m. ", "frequency":"93", "arr":[["@", "violation"],["@", "transgression"],["@", "guilt of transgression","punishment for transgression","offering for transgression"]] } ); 
bank.push( {"word":"גֵּר", "category":"n.m. ", "frequency":"92", "arr":[["@", "sojourner"]] } ); 
bank.push( {"word":"חֵלֶב", "category":"n.m. ", "frequency":"92", "arr":[["@", "fat"]] } ); 
bank.push( {"word":"עֵבֶר", "category":"n.m. ", "frequency":"92", "arr":[["@", "side"],["@", "edge"],["@", "area on the other side"]] } ); 
bank.push( {"word":"קָצֶה", "category":"n.m. ", "frequency":"92", "arr":[["@", "end"],["@", "edge"]] } ); 
bank.push( {"word":"שָׁמַד", "category":"vb. ", "frequency":"92", "arr":[["@Ni", "to be destroyed", "be destroyed"],["@Ni", "be exterminated", "to be exterminated"]] } ); 
bank.push( {"word":"שָׁמֵם", "category":"vb. ", "frequency":"92", "arr":[["@", "be devastated", "to be devastated"],["@", "be appalled", "to be appalled"],["@", "be desolated", "to be desolated"]] } ); 
bank.push( {"word":"זְרוֹעַ", "category":"n.m. ", "frequency":"91", "arr":[["@", "arm"],["@", "shoulder"],["@", "strength"]] } ); 
bank.push( {"word":"כְּרוּב", "category":"n.m. ", "frequency":"91", "arr":[["@", "cherub"]] } ); 
bank.push( {"word":"מַלְכּוּת", "category":"n.f. ", "frequency":"91", "arr":[["@", "reign"],["@", "kingdom"],["@", "royalty"]] } ); 
bank.push( {"word":"סָגַר", "category":"vb. ", "frequency":"91", "arr":[["@", "to shut", "shut"],["@", "close", "to close"],["@Pi", "to deliver up", "deliver up"],["@Hi", "to deliver up", "deliver up"]] } ); 
bank.push( {"word":"תָּמִים", "category":"adj. ", "frequency":"91", "arr":[["@", "complete"],["@", "whole"],["@", "wholesome"]] } ); 
bank.push( {"word":"יֶלֶד", "category":"n.m. ", "frequency":"89", "arr":[["@", "child"],["@", "son"],["@", "youth"]] } ); 
bank.push( {"word":"דֶּלֶת", "category":"n.f. ", "frequency":"88", "arr":[["@", "door"]] } ); 
bank.push( {"word":"דַּעַת", "category":"n.f. ", "frequency":"88", "arr":[["@", "knowledge"]] } ); 
bank.push( {"word":"טָמֵא", "category":"adj. ", "frequency":"88", "arr":[["@", "unclean"]] } ); 
bank.push( {"word":"שִׁיר", "category":"vb. ", "frequency":"88", "arr":[["@", "to sing", "sing"]] } ); 
bank.push( {"word":"שֶׁקֶל", "category":"n.m. ", "frequency":"88", "arr":[["@", "shekel"],["@", "piece of money"]] } ); 
bank.push( {"word":"בָּעַר", "category":"vb. ", "frequency":"87", "arr":[["@", "to burn", "burn"],["@", "purge", "to purge"]] } ); 
bank.push( {"word":"לָמַד", "category":"vb. ", "frequency":"87", "arr":[["@", "to learn", "learn"],["@", "train in", "to train in"]] } ); 
bank.push( {"word":"עָנָן", "category":"n.m. ", "frequency":"87", "arr":[["@", "cloud"],["@", "cloud-mass"]] } ); 
bank.push( {"word":"עֵצָה", "category":"n.f. ", "frequency":"87", "arr":[["@", "counsel"],["@", "advice"]] } ); 
bank.push( {"word":"שֶׁלֶם", "category":"n.m. ", "frequency":"87", "arr":[["@", "peace offering"]] } ); 
bank.push( {"word":"הָמוֹן", "category":"n.m/f. ", "frequency":"86", "arr":[["@", "sound"],["@", "murmur"],["@", "tumult"]] } ); 
bank.push( {"word":"פֵּאָה", "category":"n.f. ", "frequency":"86", "arr":[["@", "corner"],["@", "side"]] } ); 
bank.push( {"word":"שִׁית", "category":"vb. ", "frequency":"86", "arr":[["@", "to put", "put"],["@", "set", "to set"],["@", "fix", "to fix"],["@", "set up as", "to set up as"],["@", "ordain", "to ordain"]] } ); 
bank.push( {"word":"קָנָה", "category":"vb. ", "frequency":"85", "arr":[["@", "to acquire", "acquire"],["@", "buy", "to buy"],["@", "get", "to get"]] } ); 
bank.push( {"word":"פָּלַל", "category":"vb. ", "frequency":"84", "arr":[["@Hit", "to pray", "pray"],["@Pi", "to mediate", "mediate"],["@Pi", "arbitrate", "to arbitrate"]] } ); 
bank.push( {"word":"רָחוֹק", "category":"adj. ", "frequency":"84", "arr":[["@", "distant"],["@", "far"]] } ); 
bank.push( {"word":"1 גּוּר", "category":"vb. ", "frequency":"82", "arr":[["@", "to sojourn", "sojourn"]] } ); 
bank.push( {"word":"זָכָר", "category":"n.m. ", "frequency":"82", "arr":[["@", "male"]] } ); 
bank.push( {"word":"סָתַר", "category":"vb. ", "frequency":"82", "arr":[["@Hi", "to hide", "hide"],["@Hi", "conceal", "to conceal"],["@Ni", "be hidden", "to be hidden"],["@Ni", "hide oneself", "to hide oneself"]] } ); 
bank.push( {"word":"עָזַר", "category":"vb. ", "frequency":"82", "arr":[["@", "to help", "help"],["@", "aid", "to aid"]] } ); 
bank.push( {"word":"פֹּה", "category":"adv. ", "frequency":"82", "arr":[["@", "here"]] } ); 
bank.push( {"word":"קָלַל", "category":"vb. ", "frequency":"82", "arr":[["@", "be small", "to be small"],["@", "be insignificant", "to be insignificant"],["@", "be swift", "to be swift"]] } ); 
bank.push( {"word":"אָוֶן", "category":"n.m. ", "frequency":"81", "arr":[["@", "trouble"],["@", "deception"],["@", "wickedness"],["@", "false cult"]] } ); 
bank.push( {"word":"מָהַר", "category":"vb. ", "frequency":"81", "arr":[["@Pi", "to hurry", "hurry"],["@Pi", "hasten", "to hasten"]] } ); 
bank.push( {"word":"מָשַׁל", "category":"vb. ", "frequency":"81", "arr":[["@", "to rule", "rule"]] } ); 
bank.push( {"word":"שָׁחַט", "category":"vb. ", "frequency":"81", "arr":[["@", "to slaughter", "slaughter"],["@", "beat", "to beat"]] } ); 
bank.push( {"word":"הֵיכָל", "category":"n.m. ", "frequency":"80", "arr":[["@", "palace"],["@", "temple"]] } ); 
bank.push( {"word":"חֹשֶׁךְ", "category":"n.m. ", "frequency":"80", "arr":[["@", "dark", "darkness", "dark(ness)"]] } ); 
bank.push( {"word":"יָעַץ", "category":"vb. ", "frequency":"80", "arr":[["@", "to advise", "advise"],["@", "counsel", "to counsel"]] } ); 
bank.push( {"word":"מָכַר", "category":"vb. ", "frequency":"80", "arr":[["@", "to sell", "sell"]] } ); 
bank.push( {"word":"עוֹר", "category":"vb. ", "frequency":"80", "arr":[["@", "to wake up", "wake up"],["@", "rouse oneself", "to rouse oneself"]] } ); 
bank.push( {"word":"עָנִי", "category":"adj. ", "frequency":"80", "arr":[["@", "poor"],["@", "afflicted"],["@", "humble"]] } ); 
bank.push( {"word":"קָרְבָּן", "category":"n.m. ", "frequency":"80", "arr":[["@", "offering"],["@", "gift"]] } ); 
bank.push( {"word":"אוֹצָר", "category":"n.m. ", "frequency":"79", "arr":[["@", "treasury"],["@", "storehouse"]] } ); 
bank.push( {"word":"אוֹת", "category":"n.m. ", "frequency":"79", "arr":[["@", "sign"],["@", "symbol"],["@", "pledge"],["@", "omen"]] } ); 
bank.push( {"word":"2 עָנָה", "category":"vb. ", "frequency":"79", "arr":[["@", "to be oppressed", "be oppressed"],["@", "be humble", "to be humble"]] } ); 
bank.push( {"word":"שׁוֹר", "category":"n.m. ", "frequency":"79", "arr":[["@", "a head of cattle"],["@", "ox"]] } ); 
bank.push( {"word":"יְשׁוּעָה", "category":"n.f. ", "frequency":"78", "arr":[["@", "salvation"]] } ); 
bank.push( {"word":"מִשְׁמֶרֶת", "category":"n.f. ", "frequency":"78", "arr":[["@", "guard"],["@", "watch"],["@", "obligation"],["@", "duty"]] } ); 
bank.push( {"word":"נֶגַע", "category":"n.m. ", "frequency":"78", "arr":[["@", "stroke"],["@", "plague"],["@", "spot"],["@", "mark"]] } ); 
bank.push( {"word":"רָכַב", "category":"vb. ", "frequency":"78", "arr":[["@", "to ride", "ride"],["@", "mount", "to mount"]] } ); 
bank.push( {"word":"שִׁיר", "category":"n.m. ", "frequency":"78", "arr":[["@", "song"]] } ); 
bank.push( {"word":"תֵּ֫שַׁע", "category":"n.m. ", "frequency":"78", "arr":[["@", "nine", "90"],["@plural", "ninety", "90"]] } ); 
bank.push( {"word":"גּוֹרָל", "category":"n.m. ", "frequency":"77", "arr":[["@", "lot"]] } ); 
bank.push( {"word":"חָנַן", "category":"vb. ", "frequency":"77", "arr":[["@", "to show favor", "show favor"],["@", "be gracious", "to be gracious"]] } ); 
bank.push( {"word":"תְּפִלָּה", "category":"n.f. ", "frequency":"77", "arr":[["@", "prayer"]] } ); 
bank.push( {"word":"בַּרְזֶל", "category":"n.m. ", "frequency":"76", "arr":[["@", "iron"]] } ); 
bank.push( {"word":"מִקְנֶה", "category":"n.m. ", "frequency":"76", "arr":[["@", "cattle"]] } ); 
bank.push( {"word":"נַעֲרָה", "category":"n.f. ", "frequency":"76", "arr":[["@", "young unmarried girl"],["@", "attendant"]] } ); 
bank.push( {"word":"עֹז", "category":"n.m. ", "frequency":"76", "arr":[["@", "strength"],["@", "might"],["@", "fortified"]] } ); 
bank.push( {"word":"קֶרֶן", "category":"n.f. ", "frequency":"76", "arr":[["@", "horn"]] } ); 
bank.push( {"word":"קֶשֶׁת", "category":"n.f. ", "frequency":"76", "arr":[["@", "bow"]] } ); 
bank.push( {"word":"שָׁלָל", "category":"n.m. ", "frequency":"74", "arr":[["@", "plunder"],["@", "booty"],["@", "spoil"]] } ); 
bank.push( {"word":"תְּרוּמָה", "category":"n.f. ", "frequency":"76", "arr":[["@", "contribution"],["@", "offering"]] } ); 
bank.push( {"word":"חָלָה", "category":"vb. ", "frequency":"75", "arr":[["@", "be sick", "to be sick"],["@", "be weak", "to be weak"],["@Pi", "to entreat", "entreat"]] } ); 
bank.push( {"word":"מִקְדָּשׁ", "category":"n.m. ", "frequency":"75", "arr":[["@", "sanctuary"]] } ); 
bank.push( {"word":"עָרַךְ", "category":"vb. ", "frequency":"75", "arr":[["@", "to prepare", "prepare"],["@", "set in order", "to set in order"],["@", "compare", "to compare"],["@", "arrange", "to arrange"],["@", "confront", "to confront"]] } ); 
bank.push( {"word":"קָרוֹב", "category":"adj. ", "frequency":"75", "arr":[["@", "near"]] } ); 
bank.push( {"word":"חָפֵץ", "category":"vb. ", "frequency":"74", "arr":[["@", "to delight in", "delight in"]] } ); 
bank.push( {"word":"מָאַס", "category":"vb. ", "frequency":"74", "arr":[["@", "to reject", "reject"],["@", "refuse", "to refuse"],["@", "despise", "to despise"]] } ); 
bank.push( {"word":"מִזְרָח", "category":"n.m. ", "frequency":"74", "arr":[["@", "sunrise"],["@", "east", "the east"]] } ); 
bank.push( {"word":"נָצַב", "category":"vb. ", "frequency":"74", "arr":[["@Ni", "to take one's stand", "take one's stand"],["@Hi", "to station", "station"],["@Hi", "set up", "to set up"]] } ); 
bank.push( {"word":"סֶלָה", "category":"prt. ", "frequency":"74", "arr":[["@concept", "musical term", "a musical term", "musical term of uncertain meaning"]] } ); 
bank.push( {"word":"עֵז", "category":"n.f. ", "frequency":"74", "arr":[["@", "she-goat"],["@", "goat hair"]] } ); 
bank.push( {"word":"קָטֹן", "category":"adj. ", "frequency":"74", "arr":[["@", "small"],["@", "insignificant"],["@verb", "be small", "to be small"]] } ); 
bank.push( {"word":"אָסַר", "category":"vb. ", "frequency":"73", "arr":[["@", "to bind", "bind"],["@", "tie", "to tie"],["@", "harness", "to harness"]] } ); 
bank.push( {"word":"אֶרֶז", "category":"n.m. ", "frequency":"73", "arr":[["@", "cedar"]] } ); 
bank.push( {"word":"בַּל", "category":"adv. ", "frequency":"73", "arr":[["@", "not"],["@", "no"]] } ); 
bank.push( {"word":"הֶבֶל", "category":"n.m/f. ", "frequency":"73", "arr":[["@", "futility"],["@", "vapor"]] } ); 
bank.push( {"word":"זָעַק", "category":"vb. ", "frequency":"73", "arr":[["@", "to cry out", "cry out"],["@", "call", "to call"]] } ); 
bank.push( {"word":"חֶרְפָּה", "category":"n.f. ", "frequency":"73", "arr":[["@", "reproach"]] } ); 
bank.push( {"word":"צוּר", "category":"n.m. ", "frequency":"73", "arr":[["@", "rock"],["@", "cliff"]] } ); 
bank.push( {"word":"צַר", "category":"n.m. ", "frequency":"73", "arr":[["@", "adversary"]] } ); 
bank.push( {"word":"קִיר", "category":"n.m. ", "frequency":"73", "arr":[["@", "wall"]] } ); 
bank.push( {"word":"בֶּטֶן", "category":"n.m. ", "frequency":"72", "arr":[["@", "womb"],["@", "belly"]] } ); 
bank.push( {"word":"גִּבְעָה", "category":"n.f. ", "frequency":"72", "arr":[["@", "hill"]] } ); 
bank.push( {"word":"מָדוּעַ", "category":"adv. ", "frequency":"72", "arr":[["@", "why"]] } ); 
bank.push( {"word":"רָחַץ", "category":"vb. ", "frequency":"72", "arr":[["@", "to wash", "wash"]] } ); 
bank.push( {"word":"רִיב", "category":"vb. ", "frequency":"72", "arr":[["@", "to contend", "contend"],["@", "strive", "to strive"]] } ); 
bank.push( {"word":"שׁוֹפָר", "category":"n.m. ", "frequency":"72", "arr":[["@", "ram's horn"]] } ); 
bank.push( {"word":"לִין/לוּן", "category":"vb. ", "frequency":"71", "arr":[["@", "to lodge", "lodge"]] } ); 
bank.push( {"word":"עוֹף", "category":"n.m. ", "frequency":"71", "arr":[["@", "birds"],["@", "flying insects"]] } ); 
bank.push( {"word":"פָּלָא", "category":"vb. ", "frequency":"71", "arr":[["@Ni", "be extraordinary", "to be extraordinary"],["@Ni ptc.", "miracles", "to miracles"],["@Hi", "to do wondrously", "do wondrously"]] } ); 
bank.push( {"word":"שָׁבַת", "category":"vb. ", "frequency":"71", "arr":[["@", "to cease", "cease"],["@", "desist", "to desist"],["@", "rest", "to rest"]] } ); 
bank.push( {"word":"שֻׁלְחָן", "category":"n.m. ", "frequency":"71", "arr":[["@", "table"]] } ); 
bank.push( {"word":"זָר", "category":"ptc. ", "frequency":"70", "arr":[["@", "strange"],["@", "stranger"],["@", "foreign"],["@", "outsider"],["@", "another"]] } ); 
bank.push( {"word":"כְּסִיל", "category":"n.m. ", "frequency":"70", "arr":[["@", "fool"]] } ); 
bank.push( {"word":"מָשַׁח", "category":"vb. ", "frequency":"70", "arr":[["@", "to anoint", "anoint"],["@", "smear", "to smear"]] } ); 
bank.push( {"word":"נָבַט", "category":"vb. ", "frequency":"70", "arr":[["@Pi", "to look at", "look at"],["@Pi", "regard", "to regard"],["@Hi", "to look at", "look at"],["@Hi", "regard", "to regard"]] } ); 
bank.push( {"word":"עֵמֶק", "category":"n.m. ", "frequency":"70", "arr":[["@", "valley"],["@", "lowland"]] } ); 
bank.push( {"word":"צָרָה", "category":"n.f. ", "frequency":"70", "arr":[["@", "distress"],["@", "straits"]] } ); 
bank.push( {"word":"תָּקַע", "category":"vb. ", "frequency":"70", "arr":[["@", "to give a blow", "give a blow", "to give a blow on a horn", "give a blow on a horn", "give a blast", "to give a blast", "give a blast on a horn", "to give a blast on a horn", "give a blast (on a horn)", "to give a blast (on a horn)"],["@", "clap", "to clap"],["@", "thrust", "to thrust"],["@", "drive", "to drive"]] } ); 
bank.push( {"word":"בְּרָכָה", "category":"n.f. ", "frequency":"69", "arr":[["@", "blessing"]] } ); 
bank.push( {"word":"חֵן", "category":"n.m. ", "frequency":"69", "arr":[["@", "favor"],["@", "grace"]] } ); 
bank.push( {"word":"עֵד", "category":"n.m. ", "frequency":"69", "arr":[["@", "witness"]] } ); 
bank.push( {"word":"קָדִים", "category":"n.m. ", "frequency":"69", "arr":[["@", "east"],["@", "east wind"]] } ); 
bank.push( {"word":"רָפָא", "category":"vb. ", "frequency":"69", "arr":[["@", "to heal", "heal"]] } ); 
bank.push( {"word":"כִּכָּר", "category":"n.f. ", "frequency":"68", "arr":[["@", "round thing"],["@", "loaf"],["@", "valley"],["@", "talent", "talent (e,g of gold)"]] } ); 
bank.push( {"word":"שֹׁפֵט", "category":"ptc. ", "frequency":"68", "arr":[["@", "judge"]] } ); 
bank.push( {"word":"אַתְּ", "category":"prn. ", "frequency":"67", "arr":[["@", "you", "fem. sg. you"]] } ); 
bank.push( {"word":"בּוֹר", "category":"n.m. ", "frequency":"67", "arr":[["@", "pit"],["@", "cistern"],["@", "well"],["@fig.", "grave", "the grave"]] } ); 
bank.push( {"word":"כָּתֵף", "category":"n.f. ", "frequency":"67", "arr":[["@", "shoulder"],["@", "shoulder blade"],["@", "support"]] } ); 
bank.push( {"word":"פָּרַשׂ", "category":"vb. ", "frequency":"67", "arr":[["@", "to spread out", "spread out"]] } ); 
bank.push( {"word":"קֶבֶר", "category":"n.m. ", "frequency":"67", "arr":[["@", "grave"],["@", "tomb"]] } ); 
bank.push( {"word":"קֵץ", "category":"n.m. ", "frequency":"67", "arr":[["@", "end"]] } ); 
bank.push( {"word":"אֲחֻזָּה", "category":"n.f. ", "frequency":"66", "arr":[["@", "possession"]] } ); 
bank.push( {"word":"גֶבֶר", "category":"n.m. ", "frequency":"66", "arr":[["@", "man"]] } ); 
bank.push( {"word":"חֵלֶק", "category":"n.m. ", "frequency":"66", "arr":[["@", "portion"],["@", "tract"],["@", "territory"]] } ); 
bank.push( {"word":"שְׁאֵרִית", "category":"n.f. ", "frequency":"66", "arr":[["@", "remainder"],["@", "the rest"],["@", "remnant"]] } ); 
bank.push( {"word":"אִשֶּׁה", "category":"n.m. ", "frequency":"65", "arr":[["@", "offering made by fire"]] } ); 
bank.push( {"word":"חֲלוֹם", "category":"n.m. ", "frequency":"65", "arr":[["@", "dream"]] } ); 
bank.push( {"word":"יְאֹר", "category":"n.m. ", "frequency":"65", "arr":[["@", "stream"],["@", "canal"],["@", "Nile"],["@", "mineshaft"]] } ); 
bank.push( {"word":"כָּשַׁל", "category":"vb. ", "frequency":"65", "arr":[["@", "to stumble", "stumble"],["@", "stagger", "to stagger"]] } ); 
bank.push( {"word":"פּוּץ", "category":"vb. ", "frequency":"65", "arr":[["@", "be dispersed", "to be dispersed"],["@", "be scattered", "to be scattered"]] } ); 
bank.push( {"word":"צָלַח", "category":"vb. ", "frequency":"65", "arr":[["@", "be successful", "to be successful"],["@", "prosper", "to prosper"]] } ); 
bank.push( {"word":"שְׁאוֹל", "category":"n.f/m. ", "frequency":"65", "arr":[["@", "Sheol"],["@", "netherworld"]] } ); 
bank.push( {"word":"שָׁכַם", "category":"vb. ", "frequency":"65", "arr":[["@Hi", "to rise early", "rise early"]] } ); 
bank.push( {"word":"תָּפַשׂ", "category":"vb. ", "frequency":"65", "arr":[["@", "to seize", "seize"],["@", "grasp", "to grasp"],["@", "wield", "to wield"]] } ); 
bank.push( {"word":"לְמַעְלָה", "category":"sub. ", "frequency":"64", "arr":[["@", "upwards"]] } ); 
bank.push( {"word":"מִחוּץ", "category":"adv. ", "frequency":"64", "arr":[["@", "outside", "on the outside", "(on the) outside"],["@", "around"]] } ); 
bank.push( {"word":"תָּמַם/תַּם", "category":"vb. ", "frequency":"64", "arr":[["@", "be complete", "to be complete"],["@", "be finished", "to be finished"]] } ); 
bank.push( {"word":"אָחַז", "category":"vb. ", "frequency":"63", "arr":[["@", "to grasp", "grasp"],["@", "take hold", "to take hold"]] } ); 
bank.push( {"word":"אָרַר", "category":"vb. ", "frequency":"63", "arr":[["@", "to curse", "curse"]] } ); 
bank.push( {"word":"בָּרַח", "category":"vb. ", "frequency":"63", "arr":[["@", "to flee", "flee"]] } ); 
bank.push( {"word":"דָּרַךְ", "category":"vb. ", "frequency":"63", "arr":[["@", "to tread", "tread"],["@", "march", "to march"],["@", "bend", "to bend", "bend a bow", "to bend a bow", "bend (a bow)", "to bend (a bow)"]] } ); 
bank.push( {"word":"יָצַר", "category":"vb. ", "frequency":"63", "arr":[["@", "to form", "form"],["@", "mold", "to mold", "mold pottery", "to mold pottery", "mold (pottery)", "to mold (pottery)"]] } ); 
bank.push( {"word":"נָצַר", "category":"vb. ", "frequency":"63", "arr":[["@", "to watch over", "watch over"],["@", "protect", "to protect"],["@", "keep", "to keep"]] } ); 
bank.push( {"word":"קָרַע", "category":"vb. ", "frequency":"63", "arr":[["@", "to tear", "tear"],["@", "rend", "to rend"]] } ); 
bank.push( {"word":"שִׁפְחָה", "category":"n.f. ", "frequency":"63", "arr":[["@", "maidservant"]] } ); 
bank.push( {"word":"אֵצֶל", "category":"prp. ", "frequency":"62", "arr":[["@", "beside"]] } ); 
bank.push( {"word":"גְּבוּרָה", "category":"n.f. ", "frequency":"62", "arr":[["@", "strength"]] } ); 
bank.push( {"word":"חָג", "category":"n.m. ", "frequency":"62", "arr":[["@", "festival"],["@", "feast"]] } ); 
bank.push( {"word":"קָנֶה", "category":"n.m. ", "frequency":"62", "arr":[["@", "reed"],["@", "reed's length", "6 cubits"],["@", "humerus bone"]] } ); 
bank.push( {"word":"רִיב", "category":"n.m. ", "frequency":"62", "arr":[["@", "strife"],["@", "dispute"]] } ); 
bank.push( {"word":"שָׁקָה", "category":"vb. ", "frequency":"62", "arr":[["@", "to drink", "drink"]] } ); 
bank.push( {"word":"אֶבְיוֹן", "category":"adj. ", "frequency":"61", "arr":[["@", "needy"],["@", "poor"]] } ); 
bank.push( {"word":"אַחֲרִית", "category":"n.f. ", "frequency":"61", "arr":[["@", "hind part"],["@", "latter part"],["@", "end"],["@", "following"]] } ); 
bank.push( {"word":"אֵיךְ", "category":"adv. ", "frequency":"61", "arr":[["@", "how"]] } ); 
bank.push( {"word":"דּוֹד", "category":"n.m. ", "frequency":"61", "arr":[["@", "beloved"],["@", "uncle"]] } ); 
bank.push( {"word":"מָלֵא", "category":"adj. ", "frequency":"61", "arr":[["@", "full"]] } ); 
bank.push( {"word":"עֵדוּת", "category":"n.f. ", "frequency":"61", "arr":[["@", "testimony"]] } ); 
bank.push( {"word":"קֶדֶם", "category":"n.m. ", "frequency":"61", "arr":[["@", "front"],["@", "east"],["@", "of old"],["@", "beginning"],["@", "ancient"]] } ); 
bank.push( {"word":"אַלּוּף", "category":"n.m. ", "frequency":"60", "arr":[["@", "chief", "tribal chief", "(tribal) chief"],["@", "commander", "commander of 1000 soldiers", "commander (of 1000 soldiers)"]] } ); 
bank.push( {"word":"זָנָה", "category":"vb. ", "frequency":"60", "arr":[["@", "to fornicate", "fornicate"],["@", "be a harlot", "to be a harlot"]] } ); 
bank.push( {"word":"חָמָס", "category":"n.m. ", "frequency":"60", "arr":[["@", "violence"],["@", "wrong"]] } ); 
bank.push( {"word":"מָגֵן", "category":"n.m. ", "frequency":"60", "arr":[["@", "shield"]] } ); 
bank.push( {"word":"נֶדֶר", "category":"n.m. ", "frequency":"60", "arr":[["@", "vow"]] } ); 
bank.push( {"word":"נֶסֶךְ", "category":"n.m. ", "frequency":"60", "arr":[["@", "drink offering"],["@", "molten image"]] } ); 
bank.push( {"word":"פָּדָה", "category":"vb. ", "frequency":"60", "arr":[["@", "to ransom", "ransom"]] } ); 
bank.push( {"word":"קְטֹרֶת", "category":"n.f. ", "frequency":"60", "arr":[["@", "incense"],["@", "sacrificial smoke"]] } ); 
bank.push( {"word":"שָׂכַל", "category":"vb. ", "frequency":"60", "arr":[["@", "be prudent", "to be prudent"]] } ); 
bank.push( {"word":"אֹרַח", "category":"n.m. ", "frequency":"59", "arr":[["@", "way"],["@", "path"]] } ); 
bank.push( {"word":"יָבֵשׁ", "category":"vb. ", "frequency":"59", "arr":[["@", "be dry", "to be dry"],["@", "be dried up", "to be dried up"]] } ); 
bank.push( {"word":"יָכַח", "category":"vb. ", "frequency":"59", "arr":[["@Hi", "to decide", "decide"],["@Hi", "judge", "to judge"],["@Hi", "rebuke", "to rebuke"],["@Ni", "to reason", "reason", "reason together", "to reason together", "reason (together)", "to reason (together)"],["@Hit", "to argue", "argue"]] } ); 
bank.push( {"word":"מְנַצֵּחַ", "category":"ptc. ", "frequency":"59", "arr":[["@", "musical director", "(musical) director"]] } ); 
bank.push( {"word":"נָחַל", "category":"vb. ", "frequency":"59", "arr":[["@", "to get possession", "get possession", "to take possession", "take possession"]] } ); 
bank.push( {"word":"נָטָע", "category":"vb. ", "frequency":"59", "arr":[["@", "to plant", "plant"]] } ); 
bank.push( {"word":"רָחַק", "category":"vb. ", "frequency":"59", "arr":[["@", "be far", "to be far", "become far", "to become far", "be(come) far", "to be(come) far"],["@", "be distant", "to be distant", "become distant", "to become distant", "be(come) distant", "to be(come) distant"]] } ); 
bank.push( {"word":"שָׁדַד", "category":"vb. ", "frequency":"59", "arr":[["@", "to devastate", "devastate"],["@", "despoil", "to despoil"],["@", "ruin", "to ruin"]] } ); 
bank.push( {"word":"סֶלַע", "category":"n.m. ", "frequency":"58", "arr":[["@", "rock"],["@", "cliff"],["@", "crag"]] } ); 
bank.push( {"word":"פָּעַל", "category":"vb. ", "frequency":"58", "arr":[["@", "to do", "do"],["@", "make", "to make"]] } ); 
bank.push( {"word":"רֵיחַ", "category":"n.m. ", "frequency":"58", "arr":[["@", "scent"],["@", "odor"]] } ); 
bank.push( {"word":"תְּהִלָּה", "category":"n.f. ", "frequency":"58", "arr":[["@", "praise", "song of praise", "(song of) praise"],["@", "fame"]] } ); 
bank.push( {"word":"אֶדֶן", "category":"n.m. ", "frequency":"57", "arr":[["@", "pedestal"],["@", "base"],["@", "socket"]] } ); 
bank.push( {"word":"חָזָק", "category":"adj. ", "frequency":"57", "arr":[["@", "strong"],["@", "mighty"]] } ); 
bank.push( {"word":"יַעַר", "category":"n.m. ", "frequency":"57", "arr":[["@", "forest"],["@", "wood"]] } ); 
bank.push( {"word":"מִזְמוֹר", "category":"n.m. ", "frequency":"57", "arr":[["@", "melody"],["@", "psalm"]] } ); 
bank.push( {"word":"פָּרָשׁ", "category":"n.m. ", "frequency":"57", "arr":[["@", "horseman"],["@", "charioteer"],["@", "horse team"]] } ); 
bank.push( {"word":"אָמָה", "category":"n.f. ", "frequency":"56", "arr":[["@", "maidservant"]] } ); 
bank.push( {"word":"זָרַע", "category":"vb. ", "frequency":"56", "arr":[["@", "to sow", "sow"],["@", "scatter seed", "to scatter seed"]] } ); 
bank.push( {"word":"מַחֲשָׁבָה", "category":"n.f. ", "frequency":"56", "arr":[["@", "thought"],["@", "device"]] } ); 
bank.push( {"word":"מִתַּחַת", "category":"prp. ", "frequency":"56", "arr":[["@", "beneath", "from beneath", "(from) beneath"],["@", "under", "from under", "(from) under"]] } ); 
bank.push( {"word":"רָצוֹן", "category":"n.m. ", "frequency":"56", "arr":[["@", "favor"],["@", "will"],["@", "pleasing"]] } ); 
bank.push( {"word":"שְׁמָמָה", "category":"n.f. ", "frequency":"56", "arr":[["@", "devastation"],["@", "waste"]] } ); 
bank.push( {"word":"אַלְמָנָה", "category":"n.f. ", "frequency":"55", "arr":[["@", "widow"]] } ); 
bank.push( {"word":"גֶּפֶן", "category":"n.f. ", "frequency":"55", "arr":[["@", "vine"]] } ); 
bank.push( {"word":"דָּבַק", "category":"vb. ", "frequency":"55", "arr":[["@", "to cling", "cling"],["@", "keep", "to keep"]] } ); 
bank.push( {"word":"חָדַל", "category":"vb. ", "frequency":"55", "arr":[["@", "to cease", "cease"]] } ); 
bank.push( {"word":"חָזָה", "category":"vb. ", "frequency":"55", "arr":[["@", "to gaze", "gaze"],["@", "see", "to see"]] } ); 
bank.push( {"word":"חָלַק", "category":"vb. ", "frequency":"55", "arr":[["@", "to divide", "divide"],["@", "share", "to share"]] } ); 
bank.push( {"word":"חֵץ", "category":"n.m. ", "frequency":"55", "arr":[["@", "arrow"]] } ); 
bank.push( {"word":"חָתַת", "category":"vb. ", "frequency":"55", "arr":[["@", "be shattered", "to be shattered"],["@", "be dismayed", "to be dismayed"]] } ); 
bank.push( {"word":"כָּעַס", "category":"vb. ", "frequency":"55", "arr":[["@", "be vexed", "to be vexed"],["@", "be angry", "to be angry"]] } ); 
bank.push( {"word":"מִדָּה", "category":"n.f. ", "frequency":"55", "arr":[["@", "measure", "measurement", "measure(ment)"],["@", "garment"]] } ); 
bank.push( {"word":"צָעַק", "category":"vb. ", "frequency":"55", "arr":[["@", "to cry out", "cry out"]] } ); 
bank.push( {"word":"שֵׁן", "category":"n.f. ", "frequency":"55", "arr":[["@", "tooth"],["@", "ivory"]] } ); 
bank.push( {"word":"אָבָה", "category":"vb. ", "frequency":"54", "arr":[["@", "be willing", "to be willing"],["@", "consent", "to consent"]] } ); 
bank.push( {"word":"גָּמָל", "category":"n.m. ", "frequency":"54", "arr":[["@", "camel"]] } ); 
bank.push( {"word":"דְּבַשׁ", "category":"n.m. ", "frequency":"54", "arr":[["@", "honey"]] } ); 
bank.push( {"word":"יְרִיעָה", "category":"n.f. ", "frequency":"54", "arr":[["@", "curtain"]] } ); 
bank.push( {"word":"מָרוֹם", "category":"n.m. ", "frequency":"54", "arr":[["@", "height"]] } ); 
bank.push( {"word":"סֹפֵר/סוֹפֵר", "category":"n.m. ", "frequency":"54", "arr":[["@", "scribe"],["@", "secretary"]] } ); 
bank.push( {"word":"עָמָל", "category":"n.m. ", "frequency":"54", "arr":[["@", "trouble"],["@", "anxiety"],["@", "toil"],["@", "misery"],["@", "work"],["@", "worker"]] } ); 
bank.push( {"word":"עֶרְוָה", "category":"n.f. ", "frequency":"54", "arr":[["@", "nakedness"]] } ); 
bank.push( {"word":"שְׂמֹאל", "category":"n.m. ", "frequency":"54", "arr":[["@", "left"],["@", "north"]] } ); 
bank.push( {"word":"שָׁוְא", "category":"n.m. ", "frequency":"54", "arr":[["@", "emptiness"],["@", "vanity"]] } ); 
bank.push( {"word":"חָדָשׁ", "category":"adj. ", "frequency":"53", "arr":[["@", "new"]] } ); 
bank.push( {"word":"יוֹמָם", "category":"adv. ", "frequency":"53", "arr":[["@", "daytime"],["@", "daily"]] } ); 
bank.push( {"word":"יָצַק", "category":"vb. ", "frequency":"53", "arr":[["@", "to pour", "pour"],["@", "cast out", "to cast out"]] } ); 
bank.push( {"word":"מְדִינָה", "category":"n.f. ", "frequency":"53", "arr":[["@", "province"],["@", "district"]] } ); 
bank.push( {"word":"מַצָּה", "category":"n.f. ", "frequency":"53", "arr":[["@", "unleavened bread"]] } ); 
bank.push( {"word":"סֹלֶת", "category":"n.f. ", "frequency":"53", "arr":[["@", "fine flour"]] } ); 
bank.push( {"word":"צֵל", "category":"n.m. ", "frequency":"53", "arr":[["@", "shadow"],["@", "shade"],["@", "protection"]] } ); 
bank.push( {"word":"רָנַן", "category":"vb. ", "frequency":"53", "arr":[["@", "to give ringing cry", "give ringing cry", "to give a ringing cry", "give a ringing cry"]] } ); 
bank.push( {"word":"אַיֵּה", "category":"adv. ", "frequency":"52", "arr":[["@", "where?", "where"]] } ); 
bank.push( {"word":"מָדַד", "category":"vb. ", "frequency":"52", "arr":[["@", "to measure", "measure"]] } ); 
bank.push( {"word":"מָחָר", "category":"n.m./adv. ", "frequency":"52", "arr":[["@", "tomorrow"],["@", "in the future"]] } ); 
bank.push( {"word":"שָׂעִיר", "category":"n.m. ", "frequency":"52", "arr":[["@", "he-goat"]] } ); 
bank.push( {"word":"אַחֲרוֹן", "category":"adj. ", "frequency":"51", "arr":[["@", "behind"],["@", "after"],["@", "later"],["@", "latter"],["@", "last"]] } ); 
bank.push( {"word":"בָּקַע", "category":"vb. ", "frequency":"51", "arr":[["@", "to cleave", "cleave"],["@", "split open", "to split open"]] } ); 
bank.push( {"word":"דַּעַת", "category":"inf. ", "frequency":"51", "arr":[["@", "to know"]] } ); 
bank.push( {"word":"הוֹי", "category":"prt. ", "frequency":"51", "arr":[["@", "alas!", "alas"],["@", "woe!", "woe"]] } ); 
bank.push( {"word":"כָבַס", "category":"vb. ", "frequency":"51", "arr":[["@Pi", "to wash", "wash"],["@participle", "washer"],["@participle", "fuller"]] } ); 
bank.push( {"word":"קֶרֶשׁ", "category":"n.m. ", "frequency":"51", "arr":[["@", "board", "boards"],["@", "plank", "planks"]] } ); 
bank.push( {"word":"רֵאשִׁית", "category":"n.f. ", "frequency":"51", "arr":[["@", "beginning"],["@", "first"],["@", "chief"]] } ); 
bank.push( {"word":"בְּתוּלָה", "category":"n.f. ", "frequency":"50", "arr":[["@", "virgin"]] } ); 
bank.push( {"word":"חָרַם", "category":"vb. ", "frequency":"50", "arr":[["@", "to ban", "ban"],["@", "devote", "to devote"],["@", "destroy", "to destroy"]] } ); 
bank.push( {"word":"טַבַּעַת", "category":"n.f. ", "frequency":"50", "arr":[["@", "ring"]] } ); 
bank.push( {"word":"מוּסָר", "category":"n.m. ", "frequency":"50", "arr":[["@", "discipline"],["@", "instruction"]] } ); 
bank.push( {"word":"נָכַר", "category":"vb. ", "frequency":"50", "arr":[["@Hi", "to recognize", "recognize"],["@Hi", "regard", "to regard"]] } ); 
bank.push( {"word":"נָשַׂג", "category":"vb. ", "frequency":"50", "arr":[["@", "to reach", "reach"],["@", "overtake", "to overtake"]] } ); 
bank.push( {"word":"קַחַת", "category":"inf. ", "frequency":"49", "arr":[["@", "to take"],["@", "to receive"]] } ); 
bank.push( {"word":"כָּבֵד", "category":"adj. ", "frequency":"41", "arr":[["@", "heavy"],["@", "honorable"]] } ); 
bank.push( {"word":"גָּנַב", "category":"vb. ", "frequency":"40", "arr":[["@", "to steal", "steal"]] } ); 
bank.push( {"word":"מַלְכָּה", "category":"n.f. ", "frequency":"35", "arr":[["@", "queen"]] } ); 
bank.push( {"word":"הֵנָּה", "category":"prn. ", "frequency":"31", "arr":[["@", "they", "fem. pl. they"]] } ); 
bank.push( {"word":"קָטָן", "category":"adj. ", "frequency":"27", "arr":[["@", "small"],["@", "young"]] } ); 
bank.push( {"word":"אַתֵּנָה", "category":"prn. ", "frequency":"4", "arr":[["@", "you", "fem. pl. you"]] } ); 





















