
console.log('wordbank3.js at your service.');

var bank = [

    {"word":"וְ/ וּ / וָ","category":"cj.","frequency":"50524","arr":[["@","and"]]},
    {"word":" ּהַ","category":"art.","frequency":"24058","arr":[["@","the"]]},
    {"word":"ל","category":"prp.","frequency":"20321","arr":[["@","to"],["@","for"],["@","regarding"],["@","belonging to"]]},
    {"word":"בּ","category":"prp.","frequency":"15559","arr":[["@","in"],["@","with"],["@","by"],["@","at"],["@","among"],["@","into"],["@","when"]]},
    {"word":"אֵ֫ת / אֶת־","category":"prt.","frequency":"10987","arr":[["@concept","direct object particle","particle indicating direct object","definite direct object marker","DDOM","ddom","D.D.O.M.","d.d.o.m."]]},
    {"word":" ּמִן / מִ","category":"prp.","frequency":"7529","arr":[["@","from"],["@","out of"],["@","since"],["@","than","more than","(more) than"]]},
    {"word":"עַל","category":"prp.","frequency":"5777","arr":[["@","on"],["@","over"],["@","against"],["@","on account of"],["@","to"]]},
    {"word":"אֶל","category":"prp.","frequency":"5518","arr":[["@","to"],["@","toward"],["@","against"],["@","at"],["@","unto"],["@","concerning"]]},
    {"word":"אֲשֶׁר","category":"prt.","frequency":"5503","arr":[["@","who"],["@","which"],["@","that"]]},
    {"word":"כֹּל","category":"n.m.","frequency":"5415","arr":[["@","all"],["@","every"],["@","whole"],["@","any"]]},
    {"word":"אָמַר","category":"vb.","frequency":"5316","arr":[["@","to say","say"]]},
    {"word":"לֹא / לוֹא","category":"prt.","frequency":"5193","arr":[["@","not","no"]]},
    {"word":"בֵּן / בֶּן","category":"n.m.","frequency":"4941","arr":[["@","son","son of","son (of)"]]},
    {"word":"כִּי","category":"cj.","frequency":"4487","arr":[["@","that"],["@","because"],["@","when"],["@","indeed"]]},
    {"word":"הָיָה","category":"vb.","frequency":"3576","arr":[["@","be","become","be(come)"],["@","happen"]]},
    {"word":"כּ","category":"prp.","frequency":"3053","arr":[["@","like"],["@","as"],["@","according to"],["@","when"]]},
    {"word":"אֵל / אֱלֹהִים","category":"n.m.","frequency":"2839","arr":[["@","God"],["@","god","gods","god(s)"]]},
    {"word":"אֵלֶּה","category":"prn.","frequency":"2839","arr":[["@","these"]]},
    {"word":"עָשָׂה","category":"vb.","frequency":"2632","arr":[["@","do","to do"],["@","make","to make"],["@","perform","to perform"]]},
    {"word":"בּוֹא","category":"vb.","frequency":"2592","arr":[["@","go in","to go in","come in","to come in","enter","to enter","come to","to come to"]]},
    {"word":"מֶלֶך","category":"n.m.","frequency":"2530","arr":[["@","king"]]},
    {"word":"אֶ֫רֶץ","category":"n.f.","frequency":"2505","arr":[["@","land"],["@","earth"],["@","ground"],["@","territory"],["@","region"]]},
    {"word":"יוֹם","category":"n.m.","frequency":"2301","arr":[["@","day"]]},
    {"word":"אִישׁ","category":"n.m.","frequency":"2199","arr":[["@","man"],["@","husband"],["@","each"]]},
    {"word":"פָּנֶה / פָּנִים","category":"n.m./f.","frequency":"2126","arr":[["@","face"]]},
    {"word":"בַּיִת","category":"n.m.","frequency":"2047","arr":[["@","house"]]},
    {"word":"נָתַן","category":"vb.","frequency":"2014","arr":[["@","give","to give"],["@","put","to put"],["@","set","to set"],["@","exchange","to exchange"],["@","grant","to grant"],["@","yield","to yield"],["@","dedicate","to dedicate"]]},
    {"word":"עָם","category":"n.m.","frequency":"1869","arr":[["@","people","a people"]]},
    {"word":"יָד","category":"n.f.","frequency":"1627","arr":[["@","hand"],["@","power"]]},
    {"word":"הָלַךְ","category":"vb.","frequency":"1554","arr":[["@","go","to go"],["@","come","to come"],["@","walk","to walk"]]},
    {"word":"דָּבָר","category":"n.m.","frequency":"1454","arr":[["@","word"],["@","matter"],["@","thing"]]},
    {"word":"הוּא","category":"prn.","frequency":"1398","arr":[["@","he"]]},
    {"word":"רָאָה","category":"vb.","frequency":"1311","arr":[["@","see","to see"]]},
    {"word":"עַד / עֲדֵי־","category":"prp.","frequency":"1263","arr":[["@","as far as"],["@","even to"],["@","until"]]},
    {"word":"אֲנִי / אָנֹכִי","category":"prn.","frequency":"1233","arr":[["@","I"]]},
    {"word":"אָב","category":"n.m.","frequency":"1210","arr":[["@","father"]]},
    {"word":"זֶה","category":"prn.","frequency":"1178","arr":[["@","this","masc. sg. this"]]},
    {"word":"שָׁמַע","category":"vb.","frequency":"1165","arr":[["@","hear","to hear"],["@","obey","to obey"]]},
    {"word":"הִנֵּה / הֵן","category":"prt.","frequency":"1147","arr":[["@","look","look!","see here","see here!","take note","take note!"]]},
    {"word":"דָּבַר","category":"vb.","frequency":"1141","arr":[["@Pi","speak","to speak"]]},
    {"word":"לִפְנֵי","category":"prp.","frequency":"1126","arr":[["@","before"],["@","in the presence of"]]},
    {"word":"יָשַׁב","category":"vb.","frequency":"1088","arr":[["@","sit","to sit"],["@","dwell","to dwell"]]},
    {"word":"עִיר","category":"n.f.","frequency":"1088","arr":[["@","city"]]} ,
    {"word":"עִם","category":"prp.","frequency":"1084","arr":[["@","with"],["@","near"],["@","beside","besides"]]} ,
    {"word":"יָצָא","category":"vb.","frequency":"1076","arr":[["@","go out","to go out","come out","to come out","go","come out","to go","come out"]]},
    {"word":"שׁוּב","category":"vb.","frequency":"1075","arr":[["@","turn back","to turn back"],["@","return","to return"]]},
    {"word":"אִם","category":"cj.","frequency":"1070","arr":[["@","if"],["@","when"],["@","or"]]},
    {"word":"לָקַח","category":"vb.","frequency":"976","arr":[["@","take","to take"],["@","receive","to receive"]]},
    {"word":"יָדַע","category":"vb.","frequency":"956","arr":[["@","know","to know"]]},
    {"word":"עַיִן","category":"n.f.","frequency":"900","arr":[["@","eye"],["@","appearance"],["@","spring"]]},
    {"word":"עָלָה","category":"vb.","frequency":"894","arr":[["@","go up","to go up","ascend","to ascend"]]},
    {"word":"אֵ֫ת / אֶת־","category":"prp.","frequency":"890","arr":[["@","with"],["@","beside","besides"]]},
    {"word":"שָׁנָה","category":"n.f.","frequency":"878","arr":[["@","year"]]},
    {"word":"שֵׁם","category":"n.m.","frequency":"864","arr":[["@","name"]]},
    {"word":"לֵבָב / לֵב","category":"n.m.","frequency":"854","arr":[["@","mind"],["@","heart"],["@","will"]]},
    {"word":"שָׁלַח","category":"vb.","frequency":"847","arr":[["@","send","to send"],["@","stretch out","to stretch out"]]},
    {"word":"מוּת","category":"vb.","frequency":"845","arr":[["@","die","to die"]]},
    {"word":"שָׁם","category":"adv.","frequency":"835","arr":[["@","there"]]},
    {"word":"עֶשֶׂר / עָשָׂר","category":"n.m.","frequency":"829","arr":[["@","ten","10"],["@","-teen","x-teen","*-teen","plus ten"],["@plural","twenty","20"]]},
    {"word":"אָכַל","category":"vb.","frequency":"820","arr":[["@","eat","to eat"]]},
    {"word":"עֶבֶד","category":"n.m.","frequency":"803","arr":[["@","servant"],["@","slave"]]},
    {"word":"אֵין / אַיִן","category":"subs.","frequency":"790","arr":[["@","not","there is not"]]},
    {"word":"אִשָּׁה","category":"n.f.","frequency":"781","arr":[["@","woman"],["@","wife"]]},
    {"word":"גָּם","category":"adv.","frequency":"769","arr":[["@","also"]]},
    {"word":"נֶפֶשׁ","category":"n.f.","frequency":"757","arr":[["@","self"],["@","soul"],["@","living being"],["@","breath"],["@","throat"]]},
    {"word":"כֹּהֵן","category":"n.m.","frequency":"750","arr":[["@","priest"]]},
    {"word":"אַתָּה","category":"prn.","frequency":"749","arr":[["@","you","masc. sg. you"]]},
    {"word":"כֵּן","category":"adv.","frequency":"741","arr":[["@","thus"],["@","so"]]},
    {"word":"קָרָא 1","category":"vb.","frequency":"739","arr":[["@","call","to call"],["@","proclaim","to proclaim"],["@","read aloud","to read aloud"],["@","name","to name"]]},
    {"word":"אַל","category":"adv.","frequency":"729","arr":[["@","not","no"]]},
    {"word":"אַחַר / אַחֲרֵי","category":"adv.","frequency":"718","arr":[["@","behind"],["@","after","afterwards","after(wards)","afterward","after(ward)"]]},
    {"word":"אֶחָד","category":"n.m.","frequency":"713","arr":[["@","one","1"]]},
    {"word":"דֶּרֶךְ","category":"n.m.","frequency":"712","arr":[["@","way"],["@","road"],["@","manner"]]},
    {"word":"הֲ / הַ","category":"prt.","frequency":"661","arr":[["@","?"],["@concept","interrogative particle"]]},
    {"word":"נָשָׂא","category":"vb.","frequency":"659","arr":[["@","lift","to lift"],["@","bear","to bear"],["@","carry","to carry"]]},
    {"word":"אָח","category":"n.m.","frequency":"629","arr":[["@","brother"]]},
    {"word":"קוּם","category":"vb.","frequency":"627","arr":[["@","arise","to arise"],["@","rise","to rise"],["@","stand up","to stand up","stand","to stand"]]},
    {"word":"שָׁלֹשׁ","category":"n.m.","frequency":"606","arr":[["@","three","3"],["@plural","thirty","30"]]},
    {"word":"זאֹת","category":"prn.","frequency":"605","arr":[["@","this","fem. sg. this"]]},
    {"word":"רֹאשׁ","category":"n.m.","frequency":"600","arr":[["@","head"],["@","beginning"],["@","chief"]]},
    {"word":"שִׂים","category":"vb.","frequency":"588","arr":[["@","put","to put"],["@","place","to place"],["@","set","to set"]]},
    {"word":"בַּת","category":"n.f.","frequency":"587","arr":[["@","daughter","daughter of","daughter (of)"]]},
    {"word":"מַיִם","category":"n.m.","frequency":"585","arr":[["@","water","waters","water(s)"]]},
    {"word":"מֵאָה","category":"n.m.","frequency":"583","arr":[["@","hundred","100"]]},
    {"word":"כֹּה","category":"adv.","frequency":"577","arr":[["@","thus"],["@","here"]]},
    {"word":"מַה־ ּ/ מָה/ מֶה","category":"prn.","frequency":"571","arr":[["@","what","what?","what!"]]},
    {"word":"הֵם","category":"prn.","frequency":"565","arr":[["@","they","masc. pl. they"]]},
    {"word":"גּוֹי","category":"n.m.","frequency":"560","arr":[["@","nation"],["@","people"]]},
    {"word":"הַר","category":"n.m.","frequency":"558","arr":[["@","mountain"],["@","hill country"]]},
    {"word":"עָבַר","category":"vb.","frequency":"553","arr":[["@","pass over","to pass over"],["@","pass through","to pass through"],["@","pass by","to pass by"]]},
    {"word":"אָדָם","category":"n.m.","frequency":"551","arr":[["@","humankind"],["@","man","a man"],["@","person"]]},
    {"word":"טוֹב","category":"adj.","frequency":"530","arr":[["@","good"]]},
    {"word":"גָּדוֹל","category":"adj.","frequency":"527","arr":[["@","great"],["@","large"]]},
    {"word":"עָמַד","category":"vb.","frequency":"524","arr":[["@","stand","to stand"],["@","rise","to rise"]]},
    {"word":"שְׁנַיִם","category":"n.m.","frequency":"516","arr":[["@","two","2"]]},
    {"word":"כַּאֲשֶׁר","category":"cj.","frequency":"511","arr":[["@","as"],["@","just as"],["@","according as"],["@","when"]]},
    {"word":"תַּחַת","category":"prp.","frequency":"510","arr":[["@","below"],["@","under"],["@","instead of"]]},
    {"word":"חָמֵשׁ","category":"n.m.","frequency":"508","arr":[["@","five","5"],["@plural","fifty","50"]]},
    {"word":"קוֹל","category":"n.m.","frequency":"505","arr":[["@","voice"],["@","sound"]]},
    {"word":"נָכָה","category":"vb.","frequency":"501","arr":[["@Ni","be smitten","to be smitten"],["@Hi","smite","to smite"]]},
    {"word":"יָלַד","category":"vb.","frequency":"499","arr":[["@","bear","to bear","bear a child","to bear a child","bear (a child)","to bear (a child)"],["@","bring forth","to bring forth"]]},
    {"word":"פֶּה","category":"n.m.","frequency":"498","arr":[["@","mouth"]]},
    {"word":"אֶלֶף","category":"n.m.","frequency":"496","arr":[["@","thousand","1000"],["@","cattle"]]},
    {"word":"צָוַה","category":"vb.","frequency":"496","arr":[["@Pi","order","to order"],["@Pi","command","to command"],["@Pi","charge","to charge"]]},
    {"word":"הִיא","category":"prn.","frequency":"491","arr":[["@","she"]]},
    {"word":"עוֹד / עֹד","category":"adv.","frequency":"491","arr":[["@","yet"],["@","still"],["@","again"],["@concept","continuance"]]},
    {"word":"שֶׁבַע","category":"n.m.","frequency":"490","arr":[["@","seven","7"],["@plural","seventy","70"]]},
    {"word":"צָבָא","category":"n.m.","frequency":"487","arr":[["@","army"],["@","host"],["@","warfare"],["@","service"]]},
    {"word":"קֹדֶשׁ","category":"n.m.","frequency":"470","arr":[["@","holiness"],["@","sacredness"]]},
    {"word":"שָׁמַר","category":"vb.","frequency":"469","arr":[["@","guard","to guard"],["@","watch","to watch"],["@","keep","to keep"]]},
    {"word":"אַרְבַּע","category":"n.m.","frequency":"466","arr":[["@","four","4"],["@plural","forty","40"]]},
    {"word":"מָצָא","category":"vb.","frequency":"457","arr":[["@","find","to find"]]},
    {"word":"עוֹלָם","category":"n.m.","frequency":"439","arr":[["@","forever"],["@","always"],["@","ancient"]]},
    {"word":"נָפַל","category":"vb.","frequency":"435","arr":[["@","fall","to fall"],["@","get down","to get down"]]},
    {"word":"עַתָּה","category":"adv.","frequency":"435","arr":[["@","now"]]},
    {"word":"מִשְׁפָּט","category":"n.m.","frequency":"425","arr":[["@","law"],["@","custom"],["@","legal claim","legal decision","legal claim/decision","legal decision/claim"]]},
    {"word":"שָׂר","category":"n.m.","frequency":"425","arr":[["@","chief"],["@","official"],["@","prince"]]},
    {"word":"מִי","category":"prn.","frequency":"424","arr":[["@","who","who?"]]},
    {"word":"שָׁמַיִם","category":"n.m.","frequency":"421","arr":[["@","heaven","heavens"],["@","sky"]]},
    {"word":"תּוֹךְ / תָּ֑וֶךְ","category":"n.m.","frequency":"420","arr":[["@","midst of"]]},
    {"word":"רַב","category":"adj.","frequency":"419","arr":[["@","many"]]},
    {"word":"חֶרֶב","category":"n.f.","frequency":"413","arr":[["@","sword"]]},
    {"word":"בֵּין / בֵּינוֹת","category":"prp.","frequency":"409","arr":[["@","between"],["@concept","interval"]]},
    {"word":"נָא","category":"prt.","frequency":"405","arr":[["@","please"],["@concept","particle of entreaty","(particle of entreaty)"]]},
    {"word":"כֶּ֫סֶף","category":"n.m.","frequency":"403","arr":[["@","silver"],["@","money"]]},
    {"word":"מִזְבֵּחַ","category":"n.m.","frequency":"403","arr":[["@","altar"]]},
    {"word":"מָקוֹם","category":"n.m.","frequency":"401","arr":[["@","place","standing place","(standing) place"]]},
    {"word":"יָם","category":"n.m.","frequency":"396","arr":[["@","sea"],["@","west"]]},
    {"word":"זָהָב","category":"n.m.","frequency":"392","arr":[["@","gold"]]},
    {"word":"יָרַד","category":"vb.","frequency":"382","arr":[["@","go down","to go down","come down","to come down","go/come down","to go/come down"]]},
    {"word":"רוּחַ","category":"n.f.","frequency":"378","arr":[["@","spirit"],["@","breath"],["@","wind"]]},
    {"word":"בָּנָה","category":"vb.","frequency":"377","arr":[["@","build","to build"]]},
    {"word":"אֵשׁ","category":"n.f./m.","frequency":"376","arr":[["@","fire"]]},
    {"word":"נְאֻם","category":"n.m.","frequency":"376","arr":[["@","utterance"],["@","declaration"]]},
    {"word":"שַׁעַר","category":"n.m./f.","frequency":"373","arr":[["@","gate"]]},
    {"word":"נָגַד","category":"vb.","frequency":"371","arr":[["@Hi","declare","to declare"]]},
    {"word":"דָּם","category":"n.m.","frequency":"361","arr":[["@","blood"]]},
    {"word":"רָעָה","category":"n.f.","frequency":"354","arr":[["@","evil"],["@","misery"],["@","distress"]]},
    {"word":"מָלַךְ","category":"vb.","frequency":"350","arr":[["@","reign","to reign"],["@","be king","to be king","become king","to become king","be(come) king","to be(come) king"]]},
    {"word":"אֹהֶל","category":"n.m.","frequency":"348","arr":[["@","tent"]]},
    {"word":"לֶחֶם","category":"n.m.","frequency":"340","arr":[["@","bread"],["@","food"]]},
    {"word":"סָבִיב","category":"adv.","frequency":"338","arr":[["@","round about"],["@","circuit"]]},
    {"word":"אָדוֹן","category":"n.m.","frequency":"335","arr":[["@","master"],["@","superior"],["@","lord"]]},
    {"word":"עֵץ","category":"n.m.","frequency":"330","arr":[["@","tree"],["@","wood","woods","wood(s)"]]},
    {"word":"שָׂדֶה","category":"n.m.","frequency":"329","arr":[["@","field"]]},
    {"word":"בָּרַך","category":"vb.","frequency":"327","arr":[["@Pi","bless","to bless"],["@Hi","cause to kneel","to cause to kneel"]]},
    {"word":"כְּלִי","category":"n.m.","frequency":"325","arr":[["@","utensil"],["@","vessel"],["@","article"]]},
    {"word":"אוֹ","category":"cj.","frequency":"321","arr":[["@","or"]]},
    {"word":"מִלְחָמָה","category":"n.f.","frequency":"319","arr":[["@","battle"],["@","war"]]},
    {"word":"יָרֵא","category":"vb.","frequency":"317","arr":[["@","be afraid","to be afraid"]]},
    {"word":"נָבִיא","category":"n.m.","frequency":"317","arr":[["@","prophet"]]},
    {"word":"עָנָה 1","category":"vb.","frequency":"316","arr":[["@","answer","to answer"],["@","respond","to respond"]]},
    {"word":"רַע","category":"adj.","frequency":"312","arr":[["@","bad"],["@","evil"],["@substantive","distress"],["@substantive","evil"]]},
    {"word":"מֵעַל","category":"prp.","frequency":"311","arr":[["@","from upon"],["@","from","from beside","from besides","from (beside)","from (besides)"]]},
    {"word":"מִשְׁפָּחָה","category":"n.f.","frequency":"304","arr":[["@","clan"],["@","family"]]},
    {"word":"פָּקַד","category":"vb.","frequency":"304","arr":[["@","note","to note"],["@","count","to count"],["@","appoint","to appoint"],["@","attend to","to attend to","inspect","to inspect","punish","to punish","reward","to reward"],["@Hi","appoint","to appoint"],["@Ni","be noticed","to be noticed"],["@Ni","be missed","to be missed"]]},
    {"word":"מְאֹד","category":"adv.","frequency":"300","arr":[["@","very"],["@","exceedingly"],["@","quite"]]},
    {"word":"חַטָּאת","category":"n.f.","frequency":"298","arr":[["@","sin"],["@","sin offering"]]},
    {"word":"סוּר","category":"vb.","frequency":"298","arr":[["@","turn aside","to turn aside"]]},
    {"word":"עֵת","category":"n.f./m.","frequency":"297","arr":[["@","time"]]},
    {"word":"חָזַק","category":"vb.","frequency":"290","arr":[["@","be strong","to be strong","become strong","to become strong","be(come) strong","to be(come) strong"],["@","be firm","to be firm","become firm","to become firm","be(come) firm","to be(come) firm"],["@Hi","prevail","to prevail"],["@Hi","seize","to seize"]]},
    {"word":"כָּרַת","category":"vb.","frequency":"289","arr":[["@","cut","to cut","cut off","to cut off","cut down","to cut down","cut off/down","to cut off/down","cut down/off","to cut down/off"],["@","make a treaty","to make a treaty"]]},
    {"word":"עָבַד","category":"vb.","frequency":"289","arr":[["@","work","to work"],["@","serve","to serve"]]},
    {"word":"בְּרִית","category":"n.m.","frequency":"287","arr":[["@","covenant"]]},
    {"word":"עֹלָה","category":"n.f.","frequency":"286","arr":[["@","whole burnt offering"]]} ,
    {"word":"אֹיֵב","category":"ptc.","frequency":"285","arr":[["@","enemy"]]},
    {"word":"אַתֶּם","category":"prn.","frequency":"283","arr":[["@","you","masc. pl. you"]]},
    {"word":"חֹדֶשׁ","category":"n.m.","frequency":"283","arr":[["@","new moon"],["@","month"]]},
    {"word":"חָיָה","category":"vb.","frequency":"283","arr":[["@","live","to live"]]},
    {"word":"קָרַב","category":"vb.","frequency":"280","arr":[["@","approach","to approach"],["@","draw near","to draw near"]]},
    {"word":"אַף 2","category":"n.m.","frequency":"277","arr":[["@","nose"],["@","anger"]]},
    {"word":"אֶבֶן","category":"n.f.","frequency":"276","arr":[["@","stone"]]},
    {"word":"פַּרְעֹה","category":"n.m.","frequency":"274","arr":[["@","Pharaoh"],["@","king","Egyptian king","(Egyptian) king"]]},
    {"word":"צֹאן","category":"n.f.","frequency":"274","arr":[["@","flock","flocks","flock(s)"],["@","small cattle","small cattle (sheep and goats)"]]},
    {"word":"שֵׁשׁ","category":"n.m.","frequency":"274","arr":[["@","six","6"],["@plural","sixty","60"]]},
    {"word":"לְמַעַן","category":"cj.","frequency":"272","arr":[["@","in order that"],["@","on account of"]]},
    {"word":"בָּשָׂר","category":"n.m.","frequency":"270","arr":[["@","flesh"],["@","meat"],["@","food"]]},
    {"word":"מִדְבָּר","category":"n.m.","frequency":"269","arr":[["@","wilderness"],["@","pasture"],["@","steppe"]]},
    {"word":"רָשָׁע","category":"adj.","frequency":"264","arr":[["@","wicked"],["@","criminal"],["@","guilty"]]},
    {"word":"אַחַת","category":"n.f.","frequency":"263","arr":[["@","one","1"]]},
    {"word":"חַי","category":"adj.","frequency":"254","arr":[["@","alive"]]},
    {"word":"שְׁתַיִם","category":"n.f.","frequency":"253","arr":[["@","two","2"]]},
    {"word":"מָטֶּה","category":"n.m.","frequency":"252","arr":[["@","staff"],["@","rod"],["@","branch"],["@","tribe"]]},
    {"word":"מָלֵא","category":"vb.","frequency":"252","arr":[["@","be full","to be full"]]},
    {"word":"רֶגֶל","category":"n.f.","frequency":"251","arr":[["@","foot"]]},
    {"word":"אַמָּה","category":"n.f.","frequency":"249","arr":[["@","cubit"],["@","forearm"]]},
    {"word":"חֶסֶד","category":"n.m.","frequency":"249","arr":[["@","loyal love"],["@","kindness"]]},
    {"word":"חַיִל","category":"n.m.","frequency":"246","arr":[["@","strength"],["@","wealth"],["@","army"]]},
    {"word":"גְּבוּל","category":"n.m.","frequency":"241","arr":[["@","border"]]},
    {"word":"חָטָא","category":"vb.","frequency":"240","arr":[["@","do wrongly","to do wrongly"],["@","sin","to sin"]]},
    {"word":"נַעַר","category":"n.m.","frequency":"240","arr":[["@","adolescent"],["@","boy"],["@","attendant"],["@","servant"]]},
    {"word":"שָׁלוֹם","category":"n.m.","frequency":"237","arr":[["@","health"],["@","wholeness"],["@","intact"],["@","sound"],["@","safety"],["@","deliverance"]]},
    {"word":"זָכַר","category":"vb.","frequency":"235","arr":[["@","remember","to remember"]]},
    {"word":"לַ֫יְלָה / לַ֫יִל","category":"n.m.","frequency":"235","arr":[["@","night"]]},
    {"word":"מַעֲשֶׂה","category":"n.m.","frequency":"235","arr":[["@","deed"],["@","work"]]},
    {"word":"עָוֹן","category":"n.m.","frequency":"233","arr":[["@","wrongdoing"],["@","guilt","guilt from","guilt (from)"],["@","punishment","punishment for iniquity","punishment (for) iniquity"]]},
    {"word":"יָרַשׁ","category":"vb.","frequency":"232","arr":[["@","take possession of","to take possession of"],["@","inherit","to inherit"],["@","dispossess","to dispossess"]]},
    {"word":"זֶרַע","category":"n.m.","frequency":"229","arr":[["@","seed"]]},
    {"word":"רָבָה","category":"vb.","frequency":"229","arr":[["@","be many","to be many","become many","to become many","be(come) many","to be(come) many"],["@","be great","to be great","become great","to become great","be(come) great","to be(come) great"]]} ,
    {"word":"קֶרֶב","category":"n.m.","frequency":"227","arr":[["@","midst"],["@","inner"],["@","innards"]]},
    {"word":"בָקַשׁ","category":"vb.","frequency":"225","arr":[["@Pi","seek","to seek"]]} ,
    {"word":"כָּתַב","category":"vb.","frequency":"225","arr":[["@","write","to write"]]} ,
    {"word":"מוֹעֵד","category":"n.m.","frequency":"224","arr":[["@","meeting place"],["@","meeting time"],["@","assembly"],["@","festival"]]} ,
    {"word":"תּוֹרָה","category":"n.f.","frequency":"223","arr":[["@","instruction"],["@","law"]]} ,
    {"word":"אֲדָמָה","category":"n.f.","frequency":"222","arr":[["@","ground"],["@","earth"]]} ,
    {"word":"נַחֲלָה","category":"n.f.","frequency":"222","arr":[["@","possession"],["@","property"]]} ,
    {"word":"אֵם","category":"n.f.","frequency":"220","arr":[["@","mother"]]} ,
    {"word":"כוּן","category":"vb.","frequency":"219","arr":[["@Ni","be firm","to be firm"],["@Ni","be prepared","to be prepared"],["@Ni","be established","to be established"],["@Hi","establish","to establish"],["@Hi","prepare","to prepare"],["@Hi","provide","to provide"]]} ,
    {"word":"אָהֵב","category":"vb.","frequency":"217","arr":[["@","love","to love"]]} ,
    {"word":"שָׁתָה","category":"vb.","frequency":"217","arr":[["@","drink","to drink"]]} ,
    {"word":"בֶּגֶד","category":"n.m.","frequency":"216","arr":[["@","garment"]]} ,
    {"word":"נָטָה","category":"vb.","frequency":"216","arr":[["@","stretch out","to stretch out"],["@","extend","to extend"],["@","bend","to bend"]]} ,
    {"word":"מַחֲנֶה","category":"n.m.","frequency":"215","arr":[["@","camp"],["@","encampment"]]} ,
    {"word":"עָזַב","category":"vb.","frequency":"214","arr":[["@","abandon","to abandon"],["@","forsake","to forsake"],["@","leave","to leave"]]} ,
    {"word":"בֹּקֶר","category":"n.m.","frequency":"213","arr":[["@","morning"]]} ,
    {"word":"יָסַף","category":"vb.","frequency":"213","arr":[["@","add","to add"],["@Hi","add to","to add to"],["@Hi","repeat","to repeat"],["@Hi","increase","to increase"]]} ,
    {"word":"מַלְאָךְ","category":"n.m.","frequency":"213","arr":[["@","messenger"],["@","angel"]]} ,
    {"word":"נָצַל","category":"vb.","frequency":"213","arr":[["@Ni","be delivered","to be delivered"],["@Hi","save","to save"],["@Hi","rescue","to rescue"]]} ,
    {"word":"שָׁכַב","category":"vb.","frequency":"213","arr":[["@","lie down","to lie down"]]} ,
    {"word":"מִנְחָה","category":"n.f.","frequency":"211","arr":[["@","gift"],["@","tribute"],["@","offering"]]} ,
    {"word":"כָּלָה","category":"vb.","frequency":"207","arr":[["@","be complete","to be complete"],["@","be finished","to be finished"]]} ,
    {"word":"צַדִּיק","category":"adj.","frequency":"206","arr":[["@","just"],["@","righteous"]]} ,
    {"word":"יָשַׁע","category":"vb.","frequency":"205","arr":[["@Hi","deliver","to deliver"],["@Ni","be rescued","to be rescued"]]} ,
    {"word":"שָׁפַט","category":"vb.","frequency":"204","arr":[["@","judge","to judge"],["@","give justice","to give justice"]]} ,
    {"word":"אֲרוֹן","category":"n.m./f.","frequency":"202","arr":[["@","ark"],["@","chest"]]} ,
    {"word":"לָכֵן","category":"cj.","frequency":"201","arr":[["@","therefore"]]} ,
    {"word":"אָסַף","category":"vb.","frequency":"200","arr":[["@","gather","to gather"],["@","collect","to collect"],["@","remove","to remove"]]} ,
    {"word":"כָּבוֹד","category":"n.m.","frequency":"200","arr":[["@","honor"],["@","glory"],["@","abundance"]]} ,
    {"word":"רוּם","category":"vb.","frequency":"197","arr":[["@","be high","to be high"],["@","be exalted","to be exalted"]]} ,
    {"word":"כַּף","category":"n.f.","frequency":"195","arr":[["@","palm"],["@","sole"],["@","hollow"],["@","pan"]]} ,
    {"word":"יָכֹל","category":"vb.","frequency":"193","arr":[["@","be able","to be able"],["@","prevail","to prevail"],["@","endure","to endure"]]} ,
    {"word":"שֶׁמֶן","category":"n.m.","frequency":"193","arr":[["@","oil"],["@","fat"]]} ,
    {"word":"חָצֵר","category":"n.m.","frequency":"192","arr":[["@","court"],["@","enclosure"],["@","village"]]} ,
    {"word":"סֵפֶר","category":"n.m.","frequency":"191","arr":[["@","document"],["@","book"],["@","writing"]]} ,
    {"word":"בְּהֵמָה","category":"n.f.","frequency":"190","arr":[["@","beast"],["@","animals"],["@","cattle"]]} ,
    {"word":"שֵׁבֶט","category":"n.m.","frequency":"190","arr":[["@","rod"],["@","tribe"],["@","staff"],["@","scepter"]]} ,
    {"word":"אֹזֶן","category":"n.f.","frequency":"188","arr":[["@","ear"]]} ,
    {"word":"רֵעַ","category":"n.m.","frequency":"188","arr":[["@","friend"],["@","companion"]]} ,
    {"word":"גָּלָה","category":"vb.","frequency":"187","arr":[["@","uncover","to uncover"],["@","depart","to depart","depart into exile","to depart into exile","depart (into exile)","to depart (into exile)"]]} ,
    {"word":"שָׁבַע","category":"vb.","frequency":"186","arr":[["@Ni","swear","to swear"],["@Ni","take an oath","to take an oath"]]} ,
    {"word":"אָבַד","category":"vb.","frequency":"185","arr":[["@","perish","to perish"]]} ,
    {"word":"מִצְוָה","category":"n.f.","frequency":"184","arr":[["@","commandment"]]} ,
    {"word":"בָּקָר","category":"n.m.","frequency":"183","arr":[["@","cattle"],["@","herd"]]} ,
    {"word":"רִאשׁוֹן","category":"adj.","frequency":"182","arr":[["@","former"],["@","first"],["@","formerly"],["@","chief"]]} ,
    {"word":"זָקֵן","category":"adj.","frequency":"180","arr":[["@","old"],["@","elder"]]} ,
    {"word":"מֵאֵת","category":"prp.","frequency":"180","arr":[["@","out of"],["@","from","from beside","from (beside)"]]} ,
    {"word":"לָמָּה / לָמָה","category":"prn.","frequency":"178","arr":[["@","why?","why"]]} ,
    {"word":"שָׂפָה","category":"n.f.","frequency":"178","arr":[["@","lip"],["@","edge"],["@","speech"]]} ,
    {"word":"שָׁאַל","category":"vb.","frequency":"176","arr":[["@","ask","to ask"]]} ,
    {"word":"חָוָה","category":"vb.","frequency":"173","arr":[["@Hishtaphel","bow down","to bow down"],["@Hishtaphel","worship","to worship"]]} ,
    {"word":"בָּחַר","category":"vb.","frequency":"172","arr":[["@","choose","to choose"]]} ,
    {"word":"אַיִל","category":"n.m.","frequency":"171","arr":[["@","ram"]]} ,
    {"word":"בִּין","category":"vb.","frequency":"171","arr":[["@","understand","to understand"],["@","discern","to discern"],["@","perceive","to perceive"]]} ,
    {"word":"לָחַם","category":"vb.","frequency":"@, fight, to fight","arr":[["@Ni","do battle","to do battle"]]} ,
    {"word":"קָדַשׁ","category":"vb.","frequency":"171","arr":[["@","be set apart","to be set apart"],["@","be consecrated","to be consecrated"]]} ,
    {"word":"דּוֹר","category":"n.m.","frequency":"167","arr":[["@","generation"]]} ,
    {"word":"הָרַג","category":"vb.","frequency":"167","arr":[["@","kill","to kill"]]} ,
    {"word":"מְלָאכָה","category":"n.f.","frequency":"167","arr":[["@","work"],["@","wares"],["@","craftsmanship"]]} ,
    {"word":"רָעָה","category":"vb.","frequency":"167","arr":[["@","shepherd","to shepherd"],["@","pasture","to pasture"],["@","feed","to feed"]]} ,
    {"word":"אַחֵר","category":"adj.","frequency":"166","arr":[["@","another"],["@","different"]]} ,
    {"word":"דָּרַשׁ","category":"vb.","frequency":"165","arr":[["@","seek","to seek"],["@","resort to","to resort to"]]} ,
    {"word":"חוּץ","category":"n.m.","frequency":"164","arr":[["@","the outside"],["@","a street"]]} ,
    {"word":"פֶּתַח","category":"n.m.","frequency":"164","arr":[["@","doorway"],["@","opening"],["@","entrance"]]} ,
    {"word":"סָבַב","category":"vb.","frequency":"163","arr":[["@","surround","to surround"],["@","turn","to turn"],["@","go around","to go around"]]} ,
    {"word":"זֶבַח","category":"n.m.","frequency":"162","arr":[["@","sacrifice"]]} ,
    {"word":"טָמֵא","category":"vb.","frequency":"162","arr":[["@","be unclean","to be unclean","become unclean","to become unclean","be(come) unclean","to be(come) unclean"]]} ,
    {"word":"אַךְ","category":"adv.","frequency":"161","arr":[["@","surely"],["@","only"],["@","however"]]} ,
    {"word":"בַּד / לְבַד","category":"n.m.","frequency":"161","arr":[["@","alone"],["@","separate"]]} ,
    {"word":"בַּעַל","category":"n.m.","frequency":"161","arr":[["@","master"],["@","husband"]]} ,
    {"word":"לְבַד / בַּד","category":"n.m.","frequency":"161","arr":[["@","alone"],["@","separate"]]} ,
    {"word":"עַל־כֵּן","category":"cj.","frequency":"161","arr":[["@","therefore"]]} ,
    {"word":"תֵּת","category":"inf.","frequency":"161","arr":[["@","give","to give"]]} ,
    {"word":"גִּבּוֹר","category":"adj.","frequency":"160","arr":[["@","strong"],["@","mighty"]]} ,
    {"word":"נוּס","category":"vb.","frequency":"160","arr":[["@","flee","to flee"],["@","escape","to escape"]]} ,
    {"word":"עֲרָבָה","category":"n.f.","frequency":"160","arr":[["@","desert"],["@","plain"],["@","steppe"]]} ,
    {"word":"צְדָקָה","category":"n.f.","frequency":"159","arr":[["@","righteousness"]]} ,
    {"word":"שֶׁמֶשׁ","category":"n.m.","frequency":"158","arr":[["@","sun"]]} ,
    {"word":"כִּי אִם","category":"cj.","frequency":"156","arr":[["@","except"],["@","but only"]]} ,
    {"word":"שָׂמַח","category":"vb.","frequency":"156","arr":[["@","be glad","to be glad"],["@","rejoice","to rejoice"]]} ,
    {"word":"שֵׁנִי","category":"adj.","frequency":"156","arr":[["@","second"]]} ,
    {"word":"חָכְמָה","category":"n.f.","frequency":"153","arr":[["@","wisdom"]]} ,
    {"word":"כָסָה","category":"vb.","frequency":"153","arr":[["@","cover","to cover"],["@","conceal","to conceal"]]} ,
    {"word":"מָוֶת","category":"n.m.","frequency":"153","arr":[["@","death"]]} ,
    {"word":"צָפוֹן","category":"n.f.","frequency":"153","arr":[["@","north"]]} ,
    {"word":"שָׁחַת","category":"vb.","frequency":"152","arr":[["@Ni","be marred","to be marred"],["@Ni","be spoiled","to be spoiled"],["@Hi","act corruptly","to act corruptly"]]} ,
    {"word":"נֶ֫גֶד","category":"prp.","frequency":"151","arr":[["@","in front of"],["@","opposite of"]]} ,
    {"word":"נָגַע","category":"vb.","frequency":"150","arr":[["@","touch","to touch"],["@","reach","to reach"],["@","strike","to strike"]]} ,
    {"word":"רֹב","category":"n.m.","frequency":"150","arr":[["@","multitude"],["@","abundance"]]} ,
    {"word":"עֵדָה","category":"n.f.","frequency":"149","arr":[["@","congregation"]]} ,
    {"word":"שָׂנֵא","category":"vb.","frequency":"148","arr":[["@","hate","to hate"]]} ,
    {"word":"שָׁבַר","category":"vb.","frequency":"148","arr":[["@","break","to break"],["@Pi","shatter","to shatter"]]} ,
    {"word":"שְׁמֹנֶה","category":"n.m.","frequency":"147","arr":[["@","eight","8"],["@plural","eighty","80"]]} ,
    {"word":"הָלַל","category":"vb.","frequency":"146","arr":[["@","be boastful","to be boastful"],["@Pi","praise","to praise"]]} ,
    {"word":"נָסַע","category":"vb.","frequency":"146","arr":[["@","set out","to set out"],["@","drive","to drive","drive flocks","to drive flocks","drive (flocks)","to drive (flocks)"],["@","journey","to journey"]]} ,
    {"word":"עֲבֹדָה","category":"n.f.","frequency":"145","arr":[["@","service"],["@","labor"],["@","work"]]} ,
    {"word":"רָדַף","category":"vb.","frequency":"144","arr":[["@","pursue","to pursue"],["@","persecute","to persecute"]]} ,
    {"word":"חָנָה","category":"vb.","frequency":"143","arr":[["@","camp","to camp"],["@","bend down","to bend down"]]} ,
    {"word":"שָׁ / שַׁ / שֶׁ","category":"prt.","frequency":"143","arr":[["@","who"],["@","which"],["@","that"]]} ,
    {"word":"אָז","category":"adv.","frequency":"141","arr":[["@","then"],["@","at that time"],["@","thereupon"]]} ,
    {"word":"יַיִן","category":"n.m.","frequency":"141","arr":[["@","wine"]]} ,
    {"word":"יָמִין","category":"n.f.","frequency":"141","arr":[["@","right","right hand","right (hand)"],["@","south"]]} ,
    {"word":"חַיִּים","category":"n.m.","frequency":"140","arr":[["@","life"]]} ,
    {"word":"מַעַל","category":"prp.","frequency":"140","arr":[["@","upwards"],["@","above"]]} ,
    {"word":"נוּחַ","category":"vb.","frequency":"140","arr":[["@","rest","to rest"]]} ,
    {"word":"מִשְׁכָּן","category":"n.m.","frequency":"139","arr":[["@","dwelling","dwelling place","dwelling (place)"],["@","abode"],["@","tabernacle"]]} ,
    {"word":"נְחֹשֶׁת","category":"n.m./f.","frequency":"139","arr":[["@","copper"],["@","bronze"],["@","fetter of","fetter of copper","fetter of bronze","fetter of copper/bronze"]]} ,
    {"word":"חָכָם","category":"adj.","frequency":"138","arr":[["@","wise"]]} ,
    {"word":"יֵשׁ","category":"subs.","frequency":"138","arr":[["@","there is"]]} ,
    {"word":"סוּס","category":"n.m.","frequency":"138","arr":[["@","horse"],["@","stallion"]]} ,
    {"word":"נַחַל","category":"n.m.","frequency":"137","arr":[["@","wadi"],["@","stream"],["@","valley"],["@","trench"]]} ,
    {"word":"לֶכֶת","category":"inf.","frequency":"136","arr":[["@","walk","to walk"]]} ,
    {"word":"פָּתַח","category":"vb.","frequency":"136","arr":[["@","open","to open"]]} ,
    {"word":"קָרָא 2","category":"vb.","frequency":"136","arr":[["@","meet","to meet"],["@","encounter","to encounter"],["@","befall","to befall"],["@","happen","to happen"]]} ,
    {"word":"חָלַל","category":"vb.","frequency":"135","arr":[["@Hi","begin","to begin"],["@Ni","be polluted","to be polluted"],["@Pi","defile","to defile"],["@Pu","be profaned","to be profaned"]]} ,
    {"word":"כִּסֵּא","category":"n.m.","frequency":"135","arr":[["@","throne"],["@","honored seat"]]} ,
    {"word":"זָבַח","category":"vb.","frequency":"134","arr":[["@","slaughter","to slaughter"],["@Pi","sacrifice","to sacrifice"]]} ,
    {"word":"מִסְפָּר","category":"n.m.","frequency":"134","arr":[["@","number"],["@","recounting","retelling"]]} ,
    {"word":"עֶרֶב","category":"n.m.","frequency":"134","arr":[["@","evening"],["@","night"]]} ,
    {"word":"פָּנָה","category":"vb.","frequency":"134","arr":[["@","turn","to turn"],["@","look","to look"]]} ,
    {"word":"אַף 1","category":"cj.","frequency":"133","arr":[["@","also"],["@","even"],["@","how much more","how much less","how much more/less","how much (more)","how much (less)","how much (more/less)"]]} ,
    {"word":"חֹומָה","category":"n.f.","frequency":"133","arr":[["@","wall"]]} ,
    {"word":"פֶּן","category":"cj.","frequency":"133","arr":[["@","lest"]]} ,
    {"word":"פַּר","category":"n.m.","frequency":"133","arr":[["@","young bull"],["@","steer"]]} ,
    {"word":"קָבַר","category":"vb.","frequency":"133","arr":[["@","bury","to bury"]]} ,
    {"word":"שָׁאַר","category":"vb.","frequency":"133","arr":[["@Ni","remain","to remain"],["@Ni","be left over","to be left over"],["@Hi","leave over","to leave over"],["@Hi","spare","to spare"]]} ,
    {"word":"חֹק","category":"n.m.","frequency":"131","arr":[["@","statute"],["@","decree"]]} ,
    {"word":"נָשִׂיא","category":"n.m.","frequency":"130","arr":[["@","chief"],["@","prince"]]} ,
    {"word":"שָׁכַן","category":"vb.","frequency":"130","arr":[["@","dwell","to dwell"],["@","settle","to settle"]]} ,
    {"word":"אֱמֶת","category":"n.f.","frequency":"127","arr":[["@","truth"],["@","reliability"],["@","firmness"]]} ,
    {"word":"קָבַץ","category":"vb.","frequency":"127","arr":[["@","gather","to gather"],["@","collect","to collect"],["@","assemble","to assemble"]]} ,
    {"word":"כֹּחַ","category":"n.m.","frequency":"126","arr":[["@","strength"],["@","power"]]} ,
    {"word":"עֶצֶם","category":"n.f.","frequency":"126","arr":[["@","bone"],["@","self"]]} ,
    {"word":"בּוֹשׁ","category":"vb.","frequency":"125","arr":[["@","be ashamed","to be ashamed"]]} ,
    {"word":"חֵמָה","category":"n.f.","frequency":"125","arr":[["@","heat"],["@","rage"],["@","venom"]]} ,
    {"word":"חֲצִי־ / חֵצִי","category":"n.m.","frequency":"125","arr":[["@","half"]]} ,
    {"word":"נָגַשׁ","category":"vb.","frequency":"125","arr":[["@","draw near","to draw near"],["@","approach","to approach"]]} ,
    {"word":"שָׁלַךְ","category":"vb.","frequency":"125","arr":[["@Hi","throw","to throw"]]} ,
    {"word":"חָשַׁב","category":"vb.","frequency":"124","arr":[["@","reckon","to reckon"],["@","account","to account"]]} ,
    {"word":"צֶדֶק", "category":"n.m. ", "frequency":"123", "arr":[["@", "rightness"],["@", "righteousness"],["@", "justice"],["@", "integrity"]] } , 
    {"word":"קָהָל", "category":"n.m. ", "frequency":"123", "arr":[["@", "assembly"],["@", "company"],["@", "congregation"]] } , 
    {"word":"אֲנַחְנוּ", "category":"prn. ", "frequency":"121", "arr":[["@", "we"]] } , 
    {"word":"לָכַד", "category":"vb. ", "frequency":"121", "arr":[["@", "to capture", "capture"],["@", "seize", "to seize"],["@", "take", "to take"]] } , 
    {"word":"אוֹר", "category":"n.f. ", "frequency":"120", "arr":[["@", "light"]] } , 
    {"word":"בָּטַח", "category":"vb. ", "frequency":"120", "arr":[["@", "to trust", "trust"],["@", "be confident in", "to be confident in"]] } , 
    {"word":"בְּכוֹר", "category":"n.m. ", "frequency":"120", "arr":[["@", "firstborn"]] } , 
    {"word":"רֶכֶב", "category":"n.m. ", "frequency":"120", "arr":[["@", "chariot"],["@", "chariotry"],["@", "upper millstone"]] } , 
    {"word":"אָחוֹת", "category":"n.f. ", "frequency":"119", "arr":[["@", "sister"]] } , 
    {"word":"יָשָׁר", "category":"adj. ", "frequency":"119", "arr":[["@", "straight"],["@", "right"]] } , 
    {"word":"נָהָר", "category":"n.m. ", "frequency":"119", "arr":[["@", "stream"],["@", "river"]] } , 
    {"word":"פְּרִי", "category":"n.m. ", "frequency":"119", "arr":[["@", "fruit"]] } , 
    {"word":"פַּעַם", "category":"n.f. ", "frequency":"118", "arr":[["@", "step"],["@", "pace"],["@", "once"],["@", "occasion"]] } , 
    {"word":"תּוֹעֵבָה", "category":"n.f. ", "frequency":"118", "arr":[["@", "abhorrence"],["@", "disgust"],["@", "abomination"]] } , 
    {"word":"גָּדַל", "category":"vb. ", "frequency":"117", "arr":[["@", "to grow", "grow"],["@", "become great", "to become great"]] } , 
    {"word":"יָטַב", "category":"vb. ", "frequency":"117", "arr":[["@", "be good", "to be good"],["@", "be pleasing", "to be pleasing"]] } , 
    {"word":"לָשׁוֹן", "category":"n.m/f. ", "frequency":"117", "arr":[["@", "tongue"],["@", "language"]] } , 
    {"word":"מַמְלָכָה", "category":"n.f. ", "frequency":"117", "arr":[["@", "kingdom"],["@", "dominion"]] } , 
    {"word":"קָדוֹשׁ", "category":"adj. ", "frequency":"117", "arr":[["@", "holy"]] } , 
    {"word":"שָׂרַף", "category":"vb. ", "frequency":"117", "arr":[["@", "to burn", "burn"]] } , 
    {"word":"שָׁפַךְ", "category":"vb. ", "frequency":"117", "arr":[["@", "pour", "to pour", "pour out", "to pour out", "pour (out)", "to pour (out)"]] } , 
    {"word":"שָׁלַם", "category":"vb. ", "frequency":"116", "arr":[["@", "be complete", "to be complete"],["@", "be sound", "to be sound"]] } , 
    {"word":"נָבַא", "category":"vb. ", "frequency":"115", "arr":[["@Ni", "to prophesy", "prophesy"],["@Hi", "to prophesy", "prophesy"]] } , 
    {"word":"קָטַר", "category":"vb. ", "frequency":"115", "arr":[["@Pi", "to make a sacrifice", "make a sacrifice"],["@Pi", "to make go up in smoke", "make go up in smoke"]] } , 
    {"word":"בָּכָה", "category":"vb. ", "frequency":"114", "arr":[["@", "to weep", "weep"]] } , 
    {"word":"כָּבֵד", "category":"vb. ", "frequency":"114", "arr":[["@", "be honored", "to be honored"],["@", "be heavy", "to be heavy"],["@", "be weighty", "to be weighty"]] } , 
    {"word":"מִגְרָשׁ", "category":"n.m. ", "frequency":"114", "arr":[["@", "pastureland"],["@", "outskirts"]] } , 
    {"word":"שֶׁקֶר", "category":"n.m. ", "frequency":"113", "arr":[["@", "deception"],["@", "falsehood"]] } , 
    {"word":"בִּלְתִּי", "category":"adv. ", "frequency":"112", "arr":[["@", "except"],["@", "not"],["@", "so as not to"]] } , 
    {"word":"לָבַשׁ", "category":"vb. ", "frequency":"112", "arr":[["@", "to put on", "put on"],["@", "wear", "to wear"],["@", "be clothed", "to be clothed"]] } , 
    {"word":"נֶגֶב", "category":"n.m. ", "frequency":"112", "arr":[["@", "south"],["@", "Negev"]] } , 
    {"word":"עַמּוּד", "category":"n.m. ", "frequency":"112", "arr":[["@", "pillar"],["@", "column"]] } , 
    {"word":"יָדָה", "category":"vb. ", "frequency":"111", "arr":[["@", "to shoot", "shoot"],["@Pi", "to cast", "cast"],["@Hit", "to confess", "confess"],["@Hit", "praise", "to praise"],["@Hi", "to laud", "laud"],["@Hi", "praise", "to praise"]] } , 
    {"word":"כָּנָף", "category":"n.f. ", "frequency":"111", "arr":[["@", "wing"],["@", "skirt"],["@", "corner"]] } , 
    {"word":"שַׁבָּת", "category":"n.f/m. ", "frequency":"111", "arr":[["@", "rest"],["@", "Sabbath"]] } , 
    {"word":"עָפָר", "category":"n.m. ", "frequency":"110", "arr":[["@", "dust"],["@", "dry earth"]] } , 
    {"word":"רַק", "category":"adv. ", "frequency":"109", "arr":[["@", "only"],["@", "surely"]] } , 
    {"word":"נָחַם", "category":"vb. ", "frequency":"108", "arr":[["@Ni", "be sorry", "to be sorry"],["@Ni", "to change one’s mind", "change one’s mind"],["@Pi", "to comfort", "comfort"]] } , 
    {"word":"חַיָּה", "category":"n.f. ", "frequency":"107", "arr":[["@", "animal"],["@", "living thing"],["@", "life"]] } , 
    {"word":"כֶּבֶשׂ", "category":"n.m. ", "frequency":"107", "arr":[["@", "lamb"]] } , 
    {"word":"סָפַר", "category":"vb. ", "frequency":"107", "arr":[["@", "to count", "count"],["@Pi", "to recount", "recount"],["@Pi", "declare", "to declare"],["@Pi", "report", "to report"]] } , 
    {"word":"שֹׁמֵר", "category":"ptc. ", "frequency":"107", "arr":[["@", "watchman"],["@", "watch"],["@", "guard"],["@", "keeping"]] } , 
    {"word":"בָּמָה", "category":"n.f. ", "frequency":"106", "arr":[["@", "high place"]] } , 
    {"word":"יָתַר", "category":"vb. ", "frequency":"106", "arr":[["@Ni", "to remain", "remain"],["@Ni", "be left over", "to be left over"],["@Hi", "to leave", "leave"],["@Hi", "leave over", "to leave over"]] } , 
    {"word":"בְּעַד", "category":"prp. ", "frequency":"104", "arr":[["@", "through"],["@", "on behalf of"],["@", "behind"]] } , 
    {"word":"גָּאַל", "category":"vb. ", "frequency":"104", "arr":[["@", "to redeem", "redeem"],["@", "act as kinsman", "to act as kinsman"]] } , 
    {"word":"חֻקָּה", "category":"n.f. ", "frequency":"104", "arr":[["@", "statute"],["@", "enactment"]] } , 
    {"word":"רוּץ", "category":"vb. ", "frequency":"104", "arr":[["@", "to run", "run"]] } , 
    {"word":"תָּמִיד", "category":"n.m. ", "frequency":"104", "arr":[["@", "continually"],["@", "on-going"],["@", "lasting"]] } , 
    {"word":"מַרְאֶה", "category":"n.m. ", "frequency":"103", "arr":[["@", "vision"],["@", "appearance"],["@", "sight"]] } , 
    {"word":"כָּפַר", "category":"vb. ", "frequency":"102", "arr":[["@", "to cover", "cover"],["@Pi", "to cover over", "cover over"],["@Pi", "pacify", "to pacify"],["@Pi", "atone for", "to atone for"]] } , 
    {"word":"שָׁכַח", "category":"vb. ", "frequency":"102", "arr":[["@", "to forget", "forget"]] } , 
    {"word":"מְעַט", "category":"subst. ", "frequency":"101", "arr":[["@", "a little"],["@", "small"],["@", "few"]] } , 
    {"word":"רֹחַב", "category":"n.m. ", "frequency":"101", "arr":[["@", "breadth"],["@", "width"]] } , 
    {"word":"רָעָב", "category":"n.m. ", "frequency":"101", "arr":[["@", "famine"],["@", "hunger"]] } , 
    {"word":"יַעַן", "category":"cj. ", "frequency":"100", "arr":[["@", "on account of"]] } , 
    {"word":"רֹעֶה", "category":"ptc. ", "frequency":"100", "arr":[["@", "shepherd"]] } , 
    {"word":"עוֹר", "category":"n.m. ", "frequency":"99", "arr":[["@", "skin"],["@", "hide"],["@", "leather"]] } , 
    {"word":"רָעַע", "category":"vb. ", "frequency":"98", "arr":[["@", "be evil", "to be evil"],["@", "do evil", "to do evil"],["@", "be displeasing", "to be displeasing"],["@", "be harmful", "to be harmful"]] } , 
    {"word":"שָׁרַת", "category":"vb. ", "frequency":"98", "arr":[["@Pi", "to minister", "minister"],["@Pi", "serve", "to serve"]] } , 
    {"word":"אָמַן", "category":"vb. ", "frequency":"97", "arr":[["@Hi", "to believe in", "believe in"],["@Ni", "to prove reliable", "prove reliable"],["@Ni", "prove faithful", "to prove faithful"]] } , 
    {"word":"יֶתֶר", "category":"n.m. ", "frequency":"97", "arr":[["@", "remainder"],["@", "excess"]] } , 
    {"word":"שָׂבַע", "category":"vb. ", "frequency":"97", "arr":[["@", "be sated", "to be sated"],["@", "be satisfied", "to be satisfied"]] } , 
    {"word":"חֲמוֹר", "category":"n.m. ", "frequency":"96", "arr":[["@", "male donkey"]] } , 
    {"word":"טָהוֹר", "category":"adj. ", "frequency":"96", "arr":[["@", "clean"],["@", "pure"]] } , 
    {"word":"יַחְדָּו", "category":"adv. ", "frequency":"96", "arr":[["@", "together"]] } , 
    {"word":"אֹרֶךְ", "category":"n.m. ", "frequency":"95", "arr":[["@", "length"]] } , 
    {"word":"הָפַךְ", "category":"vb. ", "frequency":"95", "arr":[["@", "to turn", "turn"],["@", "overturn", "to overturn"],["@", "change", "to change"]] } , 
    {"word":"חָלָל", "category":"adj. ", "frequency":"94", "arr":[["@", "pierced"],["@", "fatally wounded"],["@", "slain"]] } , 
    {"word":"טָהֵר", "category":"vb. ", "frequency":"94", "arr":[["@", "be clean", "to be clean"],["@", "be pure", "to be pure"]] } , 
    {"word":"כֶּרֶם", "category":"n.m/f. ", "frequency":"94", "arr":[["@", "vineyard"]] } , 
    {"word":"מָלַט", "category":"vb. ", "frequency":"94", "arr":[["@Ni", "to escape", "escape"],["@Ni", "be delivered", "to be delivered"],["@Hi", "to deliver", "deliver"],["@Hi", "to birth", "birth"]] } , 
    {"word":"שִׂמְחָה", "category":"n.f. ", "frequency":"94", "arr":[["@", "joy"],["@", "gladness"]] } , 
    {"word":"חָרָה", "category":"vb. ", "frequency":"93", "arr":[["@", "to burn", "burn"],["@", "be kindled", "to be kindled"],["@", "be angry", "to be angry"],["@", "be upset", "to be upset"]] } , 
    {"word":"פֶּשַׁע", "category":"n.m. ", "frequency":"93", "arr":[["@", "violation"],["@", "transgression"],["@", "guilt of transgression","punishment for transgression","offering for transgression"]] } , 
    {"word":"גֵּר", "category":"n.m. ", "frequency":"92", "arr":[["@", "sojourner"]] } , 
    {"word":"חֵלֶב", "category":"n.m. ", "frequency":"92", "arr":[["@", "fat"]] } , 
    {"word":"עֵבֶר", "category":"n.m. ", "frequency":"92", "arr":[["@", "side"],["@", "edge"],["@", "area on the other side"]] } , 
    {"word":"קָצֶה", "category":"n.m. ", "frequency":"92", "arr":[["@", "end"],["@", "edge"]] } , 
    {"word":"שָׁמַד", "category":"vb. ", "frequency":"92", "arr":[["@Ni", "to be destroyed", "be destroyed"],["@Ni", "be exterminated", "to be exterminated"]] } , 
    {"word":"שָׁמֵם", "category":"vb. ", "frequency":"92", "arr":[["@", "be devastated", "to be devastated"],["@", "be appalled", "to be appalled"],["@", "be desolated", "to be desolated"]] } , 
    {"word":"זְרוֹעַ", "category":"n.m. ", "frequency":"91", "arr":[["@", "arm"],["@", "shoulder"],["@", "strength"]] } , 
    {"word":"כְּרוּב", "category":"n.m. ", "frequency":"91", "arr":[["@", "cherub"]] } , 
    {"word":"מַלְכּוּת", "category":"n.f. ", "frequency":"91", "arr":[["@", "reign"],["@", "kingdom"],["@", "royalty"]] } , 
    {"word":"סָגַר", "category":"vb. ", "frequency":"91", "arr":[["@", "to shut", "shut"],["@", "close", "to close"],["@Pi", "to deliver up", "deliver up"],["@Hi", "to deliver up", "deliver up"]] } , 
    {"word":"תָּמִים", "category":"adj. ", "frequency":"91", "arr":[["@", "complete"],["@", "whole"],["@", "wholesome"]] } , 
    {"word":"יֶלֶד", "category":"n.m. ", "frequency":"89", "arr":[["@", "child"],["@", "son"],["@", "youth"]] } , 
    {"word":"דֶּלֶת", "category":"n.f. ", "frequency":"88", "arr":[["@", "door"]] } , 
    {"word":"דַּעַת", "category":"n.f. ", "frequency":"88", "arr":[["@", "knowledge"]] } , 
    {"word":"טָמֵא", "category":"adj. ", "frequency":"88", "arr":[["@", "unclean"]] } , 
    {"word":"שִׁיר", "category":"vb. ", "frequency":"88", "arr":[["@", "to sing", "sing"]] } , 
    {"word":"שֶׁקֶל", "category":"n.m. ", "frequency":"88", "arr":[["@", "shekel"],["@", "piece of money"]] } , 
    {"word":"בָּעַר", "category":"vb. ", "frequency":"87", "arr":[["@", "to burn", "burn"],["@", "purge", "to purge"]] } , 
    {"word":"לָמַד", "category":"vb. ", "frequency":"87", "arr":[["@", "to learn", "learn"],["@", "train in", "to train in"]] } , 
    {"word":"עָנָן", "category":"n.m. ", "frequency":"87", "arr":[["@", "cloud"],["@", "cloud-mass"]] } , 
    {"word":"עֵצָה", "category":"n.f. ", "frequency":"87", "arr":[["@", "counsel"],["@", "advice"]] } , 
    {"word":"שֶׁלֶם", "category":"n.m. ", "frequency":"87", "arr":[["@", "peace offering"]] } , 
    {"word":"הָמוֹן", "category":"n.m/f. ", "frequency":"86", "arr":[["@", "sound"],["@", "murmur"],["@", "tumult"]] } , 
    {"word":"פֵּאָה", "category":"n.f. ", "frequency":"86", "arr":[["@", "corner"],["@", "side"]] } , 
    {"word":"שִׁית", "category":"vb. ", "frequency":"86", "arr":[["@", "to put", "put"],["@", "set", "to set"],["@", "fix", "to fix"],["@", "set up as", "to set up as"],["@", "ordain", "to ordain"]] } , 
    {"word":"קָנָה", "category":"vb. ", "frequency":"85", "arr":[["@", "to acquire", "acquire"],["@", "buy", "to buy"],["@", "get", "to get"]] } , 
    {"word":"פָּלַל", "category":"vb. ", "frequency":"84", "arr":[["@Hit", "to pray", "pray"],["@Pi", "to mediate", "mediate"],["@Pi", "arbitrate", "to arbitrate"]] } , 
    {"word":"רָחוֹק", "category":"adj. ", "frequency":"84", "arr":[["@", "distant"],["@", "far"]] } , 
    {"word":"1 גּוּר", "category":"vb. ", "frequency":"82", "arr":[["@", "to sojourn", "sojourn"]] } , 
    {"word":"זָכָר", "category":"n.m. ", "frequency":"82", "arr":[["@", "male"]] } , 
    {"word":"סָתַר", "category":"vb. ", "frequency":"82", "arr":[["@Hi", "to hide", "hide"],["@Hi", "conceal", "to conceal"],["@Ni", "be hidden", "to be hidden"],["@Ni", "hide oneself", "to hide oneself"]] } , 
    {"word":"עָזַר", "category":"vb. ", "frequency":"82", "arr":[["@", "to help", "help"],["@", "aid", "to aid"]] } , 
    {"word":"פֹּה", "category":"adv. ", "frequency":"82", "arr":[["@", "here"]] } , 
    {"word":"קָלַל", "category":"vb. ", "frequency":"82", "arr":[["@", "be small", "to be small"],["@", "be insignificant", "to be insignificant"],["@", "be swift", "to be swift"]] } , 
    {"word":"אָוֶן", "category":"n.m. ", "frequency":"81", "arr":[["@", "trouble"],["@", "deception"],["@", "wickedness"],["@", "false cult"]] } , 
    {"word":"מָהַר", "category":"vb. ", "frequency":"81", "arr":[["@Pi", "to hurry", "hurry"],["@Pi", "hasten", "to hasten"]] } , 
    {"word":"מָשַׁל", "category":"vb. ", "frequency":"81", "arr":[["@", "to rule", "rule"]] } , 
    {"word":"שָׁחַט", "category":"vb. ", "frequency":"81", "arr":[["@", "to slaughter", "slaughter"],["@", "beat", "to beat"]] } , 
    {"word":"הֵיכָל", "category":"n.m. ", "frequency":"80", "arr":[["@", "palace"],["@", "temple"]] } , 
    {"word":"חֹשֶׁךְ", "category":"n.m. ", "frequency":"80", "arr":[["@", "dark", "darkness", "dark(ness)"]] } , 
    {"word":"יָעַץ", "category":"vb. ", "frequency":"80", "arr":[["@", "to advise", "advise"],["@", "counsel", "to counsel"]] } , 
    {"word":"מָכַר", "category":"vb. ", "frequency":"80", "arr":[["@", "to sell", "sell"]] } , 
    {"word":"עוֹר", "category":"vb. ", "frequency":"80", "arr":[["@", "to wake up", "wake up"],["@", "rouse oneself", "to rouse oneself"]] } , 
    {"word":"עָנִי", "category":"adj. ", "frequency":"80", "arr":[["@", "poor"],["@", "afflicted"],["@", "humble"]] } , 
    {"word":"קָרְבָּן", "category":"n.m. ", "frequency":"80", "arr":[["@", "offering"],["@", "gift"]] } , 
    {"word":"אוֹצָר", "category":"n.m. ", "frequency":"79", "arr":[["@", "treasury"],["@", "storehouse"]] } , 
    {"word":"אוֹת", "category":"n.m. ", "frequency":"79", "arr":[["@", "sign"],["@", "symbol"],["@", "pledge"],["@", "omen"]] } , 
    {"word":"2 עָנָה", "category":"vb. ", "frequency":"79", "arr":[["@", "to be oppressed", "be oppressed"],["@", "be humble", "to be humble"]] } , 
    {"word":"שׁוֹר", "category":"n.m. ", "frequency":"79", "arr":[["@", "a head of cattle"],["@", "ox"]] } , 
    {"word":"יְשׁוּעָה", "category":"n.f. ", "frequency":"78", "arr":[["@", "salvation"]] } , 
    {"word":"מִשְׁמֶרֶת", "category":"n.f. ", "frequency":"78", "arr":[["@", "guard"],["@", "watch"],["@", "obligation"],["@", "duty"]] } , 
    {"word":"נֶגַע", "category":"n.m. ", "frequency":"78", "arr":[["@", "stroke"],["@", "plague"],["@", "spot"],["@", "mark"]] } , 
    {"word":"רָכַב", "category":"vb. ", "frequency":"78", "arr":[["@", "to ride", "ride"],["@", "mount", "to mount"]] } , 
    {"word":"שִׁיר", "category":"n.m. ", "frequency":"78", "arr":[["@", "song"]] } , 
    {"word":"תֵּ֫שַׁע", "category":"n.m. ", "frequency":"78", "arr":[["@", "nine", "90"],["@plural", "ninety", "90"]] } , 
    {"word":"גּוֹרָל", "category":"n.m. ", "frequency":"77", "arr":[["@", "lot"]] } , 
    {"word":"חָנַן", "category":"vb. ", "frequency":"77", "arr":[["@", "to show favor", "show favor"],["@", "be gracious", "to be gracious"]] } , 
    {"word":"תְּפִלָּה", "category":"n.f. ", "frequency":"77", "arr":[["@", "prayer"]] } , 
    {"word":"בַּרְזֶל", "category":"n.m. ", "frequency":"76", "arr":[["@", "iron"]] } , 
    {"word":"מִקְנֶה", "category":"n.m. ", "frequency":"76", "arr":[["@", "cattle"]] } , 
    {"word":"נַעֲרָה", "category":"n.f. ", "frequency":"76", "arr":[["@", "young unmarried girl"],["@", "attendant"]] } , 
    {"word":"עֹז", "category":"n.m. ", "frequency":"76", "arr":[["@", "strength"],["@", "might"],["@", "fortified"]] } , 
    {"word":"קֶרֶן", "category":"n.f. ", "frequency":"76", "arr":[["@", "horn"]] } , 
    {"word":"קֶשֶׁת", "category":"n.f. ", "frequency":"76", "arr":[["@", "bow"]] } , 
    {"word":"שָׁלָל", "category":"n.m. ", "frequency":"74", "arr":[["@", "plunder"],["@", "booty"],["@", "spoil"]] } , 
    {"word":"תְּרוּמָה", "category":"n.f. ", "frequency":"76", "arr":[["@", "contribution"],["@", "offering"]] } , 
    {"word":"חָלָה", "category":"vb. ", "frequency":"75", "arr":[["@", "be sick", "to be sick"],["@", "be weak", "to be weak"],["@Pi", "to entreat", "entreat"]] } , 
    {"word":"מִקְדָּשׁ", "category":"n.m. ", "frequency":"75", "arr":[["@", "sanctuary"]] } , 
    {"word":"עָרַךְ", "category":"vb. ", "frequency":"75", "arr":[["@", "to prepare", "prepare"],["@", "set in order", "to set in order"],["@", "compare", "to compare"],["@", "arrange", "to arrange"],["@", "confront", "to confront"]] } , 
    {"word":"קָרוֹב", "category":"adj. ", "frequency":"75", "arr":[["@", "near"]] } , 
    {"word":"חָפֵץ", "category":"vb. ", "frequency":"74", "arr":[["@", "to delight in", "delight in"]] } , 
    {"word":"מָאַס", "category":"vb. ", "frequency":"74", "arr":[["@", "to reject", "reject"],["@", "refuse", "to refuse"],["@", "despise", "to despise"]] } , 
    {"word":"מִזְרָח", "category":"n.m. ", "frequency":"74", "arr":[["@", "sunrise"],["@", "east", "the east"]] } , 
    {"word":"נָצַב", "category":"vb. ", "frequency":"74", "arr":[["@Ni", "to take one's stand", "take one's stand"],["@Hi", "to station", "station"],["@Hi", "set up", "to set up"]] } , 
    {"word":"סֶלָה", "category":"prt. ", "frequency":"74", "arr":[["@concept", "musical term", "a musical term", "musical term of uncertain meaning"]] } , 
    {"word":"עֵז", "category":"n.f. ", "frequency":"74", "arr":[["@", "she-goat"],["@", "goat hair"]] } , 
    {"word":"קָטֹן", "category":"adj. ", "frequency":"74", "arr":[["@", "small"],["@", "insignificant"],["@verb", "be small", "to be small"]] } , 
    {"word":"אָסַר", "category":"vb. ", "frequency":"73", "arr":[["@", "to bind", "bind"],["@", "tie", "to tie"],["@", "harness", "to harness"]] } , 
    {"word":"אֶרֶז", "category":"n.m. ", "frequency":"73", "arr":[["@", "cedar"]] } , 
    {"word":"בַּל", "category":"adv. ", "frequency":"73", "arr":[["@", "not"],["@", "no"]] } , 
    {"word":"הֶבֶל", "category":"n.m/f. ", "frequency":"73", "arr":[["@", "futility"],["@", "vapor"]] } , 
    {"word":"זָעַק", "category":"vb. ", "frequency":"73", "arr":[["@", "to cry out", "cry out"],["@", "call", "to call"]] } , 
    {"word":"חֶרְפָּה", "category":"n.f. ", "frequency":"73", "arr":[["@", "reproach"]] } , 
    {"word":"צוּר", "category":"n.m. ", "frequency":"73", "arr":[["@", "rock"],["@", "cliff"]] } , 
    {"word":"צַר", "category":"n.m. ", "frequency":"73", "arr":[["@", "adversary"]] } , 
    {"word":"קִיר", "category":"n.m. ", "frequency":"73", "arr":[["@", "wall"]] } , 
    {"word":"בֶּטֶן", "category":"n.m. ", "frequency":"72", "arr":[["@", "womb"],["@", "belly"]] } , 
    {"word":"גִּבְעָה", "category":"n.f. ", "frequency":"72", "arr":[["@", "hill"]] } , 
    {"word":"מָדוּעַ", "category":"adv. ", "frequency":"72", "arr":[["@", "why"]] } , 
    {"word":"רָחַץ", "category":"vb. ", "frequency":"72", "arr":[["@", "to wash", "wash"]] } , 
    {"word":"רִיב", "category":"vb. ", "frequency":"72", "arr":[["@", "to contend", "contend"],["@", "strive", "to strive"]] } , 
    {"word":"שׁוֹפָר", "category":"n.m. ", "frequency":"72", "arr":[["@", "ram's horn"]] } , 
    {"word":"לִין/לוּן", "category":"vb. ", "frequency":"71", "arr":[["@", "to lodge", "lodge"]] } , 
    {"word":"עוֹף", "category":"n.m. ", "frequency":"71", "arr":[["@", "birds"],["@", "flying insects"]] } , 
    {"word":"פָּלָא", "category":"vb. ", "frequency":"71", "arr":[["@Ni", "be extraordinary", "to be extraordinary"],["@Ni ptc.", "miracles", "to miracles"],["@Hi", "to do wondrously", "do wondrously"]] } , 
    {"word":"שָׁבַת", "category":"vb. ", "frequency":"71", "arr":[["@", "to cease", "cease"],["@", "desist", "to desist"],["@", "rest", "to rest"]] } , 
    {"word":"שֻׁלְחָן", "category":"n.m. ", "frequency":"71", "arr":[["@", "table"]] } , 
    {"word":"זָר", "category":"ptc. ", "frequency":"70", "arr":[["@", "strange"],["@", "stranger"],["@", "foreign"],["@", "outsider"],["@", "another"]] } , 
    {"word":"כְּסִיל", "category":"n.m. ", "frequency":"70", "arr":[["@", "fool"]] } , 
    {"word":"מָשַׁח", "category":"vb. ", "frequency":"70", "arr":[["@", "to anoint", "anoint"],["@", "smear", "to smear"]] } , 
    {"word":"נָבַט", "category":"vb. ", "frequency":"70", "arr":[["@Pi", "to look at", "look at"],["@Pi", "regard", "to regard"],["@Hi", "to look at", "look at"],["@Hi", "regard", "to regard"]] } , 
    {"word":"עֵמֶק", "category":"n.m. ", "frequency":"70", "arr":[["@", "valley"],["@", "lowland"]] } , 
    {"word":"צָרָה", "category":"n.f. ", "frequency":"70", "arr":[["@", "distress"],["@", "straits"]] } , 
    {"word":"תָּקַע", "category":"vb. ", "frequency":"70", "arr":[["@", "to give a blow", "give a blow", "to give a blow on a horn", "give a blow on a horn", "give a blast", "to give a blast", "give a blast on a horn", "to give a blast on a horn", "give a blast (on a horn)", "to give a blast (on a horn)"],["@", "clap", "to clap"],["@", "thrust", "to thrust"],["@", "drive", "to drive"]] } , 
    {"word":"בְּרָכָה", "category":"n.f. ", "frequency":"69", "arr":[["@", "blessing"]] } , 
    {"word":"חֵן", "category":"n.m. ", "frequency":"69", "arr":[["@", "favor"],["@", "grace"]] } , 
    {"word":"עֵד", "category":"n.m. ", "frequency":"69", "arr":[["@", "witness"]] } , 
    {"word":"קָדִים", "category":"n.m. ", "frequency":"69", "arr":[["@", "east"],["@", "east wind"]] } , 
    {"word":"רָפָא", "category":"vb. ", "frequency":"69", "arr":[["@", "to heal", "heal"]] } , 
    {"word":"כִּכָּר", "category":"n.f. ", "frequency":"68", "arr":[["@", "round thing"],["@", "loaf"],["@", "valley"],["@", "talent", "talent (e,g of gold)"]] } , 
    {"word":"שֹׁפֵט", "category":"ptc. ", "frequency":"68", "arr":[["@", "judge"]] } , 
    {"word":"אַתְּ", "category":"prn. ", "frequency":"67", "arr":[["@", "you", "fem. sg. you"]] } , 
    {"word":"בּוֹר", "category":"n.m. ", "frequency":"67", "arr":[["@", "pit"],["@", "cistern"],["@", "well"],["@fig.", "grave", "the grave"]] } , 
    {"word":"כָּתֵף", "category":"n.f. ", "frequency":"67", "arr":[["@", "shoulder"],["@", "shoulder blade"],["@", "support"]] } , 
    {"word":"פָּרַשׂ", "category":"vb. ", "frequency":"67", "arr":[["@", "to spread out", "spread out"]] } , 
    {"word":"קֶבֶר", "category":"n.m. ", "frequency":"67", "arr":[["@", "grave"],["@", "tomb"]] } , 
    {"word":"קֵץ", "category":"n.m. ", "frequency":"67", "arr":[["@", "end"]] } , 
    {"word":"אֲחֻזָּה", "category":"n.f. ", "frequency":"66", "arr":[["@", "possession"]] } , 
    {"word":"גֶבֶר", "category":"n.m. ", "frequency":"66", "arr":[["@", "man"]] } , 
    {"word":"חֵלֶק", "category":"n.m. ", "frequency":"66", "arr":[["@", "portion"],["@", "tract"],["@", "territory"]] } , 
    {"word":"שְׁאֵרִית", "category":"n.f. ", "frequency":"66", "arr":[["@", "remainder"],["@", "the rest"],["@", "remnant"]] } , 
    {"word":"אִשֶּׁה", "category":"n.m. ", "frequency":"65", "arr":[["@", "offering made by fire"]] } , 
    {"word":"חֲלוֹם", "category":"n.m. ", "frequency":"65", "arr":[["@", "dream"]] } , 
    {"word":"יְאֹר", "category":"n.m. ", "frequency":"65", "arr":[["@", "stream"],["@", "canal"],["@", "Nile"],["@", "mineshaft"]] } , 
    {"word":"כָּשַׁל", "category":"vb. ", "frequency":"65", "arr":[["@", "to stumble", "stumble"],["@", "stagger", "to stagger"]] } , 
    {"word":"פּוּץ", "category":"vb. ", "frequency":"65", "arr":[["@", "be dispersed", "to be dispersed"],["@", "be scattered", "to be scattered"]] } , 
    {"word":"צָלַח", "category":"vb. ", "frequency":"65", "arr":[["@", "be successful", "to be successful"],["@", "prosper", "to prosper"]] } , 
    {"word":"שְׁאוֹל", "category":"n.f/m. ", "frequency":"65", "arr":[["@", "Sheol"],["@", "netherworld"]] } , 
    {"word":"שָׁכַם", "category":"vb. ", "frequency":"65", "arr":[["@Hi", "to rise early", "rise early"]] } , 
    {"word":"תָּפַשׂ", "category":"vb. ", "frequency":"65", "arr":[["@", "to seize", "seize"],["@", "grasp", "to grasp"],["@", "wield", "to wield"]] } , 
    {"word":"לְמַעְלָה", "category":"sub. ", "frequency":"64", "arr":[["@", "upwards"]] } , 
    {"word":"מִחוּץ", "category":"adv. ", "frequency":"64", "arr":[["@", "outside", "on the outside", "(on the) outside"],["@", "around"]] } , 
    {"word":"תָּמַם/תַּם", "category":"vb. ", "frequency":"64", "arr":[["@", "be complete", "to be complete"],["@", "be finished", "to be finished"]] } , 
    {"word":"אָחַז", "category":"vb. ", "frequency":"63", "arr":[["@", "to grasp", "grasp"],["@", "take hold", "to take hold"]] } , 
    {"word":"אָרַר", "category":"vb. ", "frequency":"63", "arr":[["@", "to curse", "curse"]] } , 
    {"word":"בָּרַח", "category":"vb. ", "frequency":"63", "arr":[["@", "to flee", "flee"]] } , 
    {"word":"דָּרַךְ", "category":"vb. ", "frequency":"63", "arr":[["@", "to tread", "tread"],["@", "march", "to march"],["@", "bend", "to bend", "bend a bow", "to bend a bow", "bend (a bow)", "to bend (a bow)"]] } , 
    {"word":"יָצַר", "category":"vb. ", "frequency":"63", "arr":[["@", "to form", "form"],["@", "mold", "to mold", "mold pottery", "to mold pottery", "mold (pottery)", "to mold (pottery)"]] } , 
    {"word":"נָצַר", "category":"vb. ", "frequency":"63", "arr":[["@", "to watch over", "watch over"],["@", "protect", "to protect"],["@", "keep", "to keep"]] } , 
    {"word":"קָרַע", "category":"vb. ", "frequency":"63", "arr":[["@", "to tear", "tear"],["@", "rend", "to rend"]] } , 
    {"word":"שִׁפְחָה", "category":"n.f. ", "frequency":"63", "arr":[["@", "maidservant"]] } , 
    {"word":"אֵצֶל", "category":"prp. ", "frequency":"62", "arr":[["@", "beside"]] } , 
    {"word":"גְּבוּרָה", "category":"n.f. ", "frequency":"62", "arr":[["@", "strength"]] } , 
    {"word":"חָג", "category":"n.m. ", "frequency":"62", "arr":[["@", "festival"],["@", "feast"]] } , 
    {"word":"קָנֶה", "category":"n.m. ", "frequency":"62", "arr":[["@", "reed"],["@", "reed's length", "6 cubits"],["@", "humerus bone"]] } , 
    {"word":"רִיב", "category":"n.m. ", "frequency":"62", "arr":[["@", "strife"],["@", "dispute"]] } , 
    {"word":"שָׁקָה", "category":"vb. ", "frequency":"62", "arr":[["@", "to drink", "drink"]] } , 
    {"word":"אֶבְיוֹן", "category":"adj. ", "frequency":"61", "arr":[["@", "needy"],["@", "poor"]] } , 
    {"word":"אַחֲרִית", "category":"n.f. ", "frequency":"61", "arr":[["@", "hind part"],["@", "latter part"],["@", "end"],["@", "following"]] } , 
    {"word":"אֵיךְ", "category":"adv. ", "frequency":"61", "arr":[["@", "how"]] } , 
    {"word":"דּוֹד", "category":"n.m. ", "frequency":"61", "arr":[["@", "beloved"],["@", "uncle"]] } , 
    {"word":"מָלֵא", "category":"adj. ", "frequency":"61", "arr":[["@", "full"]] } , 
    {"word":"עֵדוּת", "category":"n.f. ", "frequency":"61", "arr":[["@", "testimony"]] } , 
    {"word":"קֶדֶם", "category":"n.m. ", "frequency":"61", "arr":[["@", "front"],["@", "east"],["@", "of old"],["@", "beginning"],["@", "ancient"]] } , 
    {"word":"אַלּוּף", "category":"n.m. ", "frequency":"60", "arr":[["@", "chief", "tribal chief", "(tribal) chief"],["@", "commander", "commander of 1000 soldiers", "commander (of 1000 soldiers)"]] } , 
    {"word":"זָנָה", "category":"vb. ", "frequency":"60", "arr":[["@", "to fornicate", "fornicate"],["@", "be a harlot", "to be a harlot"]] } , 
    {"word":"חָמָס", "category":"n.m. ", "frequency":"60", "arr":[["@", "violence"],["@", "wrong"]] } , 
    {"word":"מָגֵן", "category":"n.m. ", "frequency":"60", "arr":[["@", "shield"]] } , 
    {"word":"נֶדֶר", "category":"n.m. ", "frequency":"60", "arr":[["@", "vow"]] } , 
    {"word":"נֶסֶךְ", "category":"n.m. ", "frequency":"60", "arr":[["@", "drink offering"],["@", "molten image"]] } , 
    {"word":"פָּדָה", "category":"vb. ", "frequency":"60", "arr":[["@", "to ransom", "ransom"]] } , 
    {"word":"קְטֹרֶת", "category":"n.f. ", "frequency":"60", "arr":[["@", "incense"],["@", "sacrificial smoke"]] } , 
    {"word":"שָׂכַל", "category":"vb. ", "frequency":"60", "arr":[["@", "be prudent", "to be prudent"]] } , 
    {"word":"אֹרַח", "category":"n.m. ", "frequency":"59", "arr":[["@", "way"],["@", "path"]] } , 
    {"word":"יָבֵשׁ", "category":"vb. ", "frequency":"59", "arr":[["@", "be dry", "to be dry"],["@", "be dried up", "to be dried up"]] } , 
    {"word":"יָכַח", "category":"vb. ", "frequency":"59", "arr":[["@Hi", "to decide", "decide"],["@Hi", "judge", "to judge"],["@Hi", "rebuke", "to rebuke"],["@Ni", "to reason", "reason", "reason together", "to reason together", "reason (together)", "to reason (together)"],["@Hit", "to argue", "argue"]] } , 
    {"word":"מְנַצֵּחַ", "category":"ptc. ", "frequency":"59", "arr":[["@", "musical director", "(musical) director"]] } , 
    {"word":"נָחַל", "category":"vb. ", "frequency":"59", "arr":[["@", "to get possession", "get possession", "to take possession", "take possession"]] } , 
    {"word":"נָטָע", "category":"vb. ", "frequency":"59", "arr":[["@", "to plant", "plant"]] } , 
    {"word":"רָחַק", "category":"vb. ", "frequency":"59", "arr":[["@", "be far", "to be far", "become far", "to become far", "be(come) far", "to be(come) far"],["@", "be distant", "to be distant", "become distant", "to become distant", "be(come) distant", "to be(come) distant"]] } , 
    {"word":"שָׁדַד", "category":"vb. ", "frequency":"59", "arr":[["@", "to devastate", "devastate"],["@", "despoil", "to despoil"],["@", "ruin", "to ruin"]] } , 
    {"word":"סֶלַע", "category":"n.m. ", "frequency":"58", "arr":[["@", "rock"],["@", "cliff"],["@", "crag"]] } , 
    {"word":"פָּעַל", "category":"vb. ", "frequency":"58", "arr":[["@", "to do", "do"],["@", "make", "to make"]] } , 
    {"word":"רֵיחַ", "category":"n.m. ", "frequency":"58", "arr":[["@", "scent"],["@", "odor"]] } , 
    {"word":"תְּהִלָּה", "category":"n.f. ", "frequency":"58", "arr":[["@", "praise", "song of praise", "(song of) praise"],["@", "fame"]] } , 
    {"word":"אֶדֶן", "category":"n.m. ", "frequency":"57", "arr":[["@", "pedestal"],["@", "base"],["@", "socket"]] } , 
    {"word":"חָזָק", "category":"adj. ", "frequency":"57", "arr":[["@", "strong"],["@", "mighty"]] } , 
    {"word":"יַעַר", "category":"n.m. ", "frequency":"57", "arr":[["@", "forest"],["@", "wood"]] } , 
    {"word":"מִזְמוֹר", "category":"n.m. ", "frequency":"57", "arr":[["@", "melody"],["@", "psalm"]] } , 
    {"word":"פָּרָשׁ", "category":"n.m. ", "frequency":"57", "arr":[["@", "horseman"],["@", "charioteer"],["@", "horse team"]] } , 
    {"word":"אָמָה", "category":"n.f. ", "frequency":"56", "arr":[["@", "maidservant"]] } , 
    {"word":"זָרַע", "category":"vb. ", "frequency":"56", "arr":[["@", "to sow", "sow"],["@", "scatter seed", "to scatter seed"]] } , 
    {"word":"מַחֲשָׁבָה", "category":"n.f. ", "frequency":"56", "arr":[["@", "thought"],["@", "device"]] } , 
    {"word":"מִתַּחַת", "category":"prp. ", "frequency":"56", "arr":[["@", "beneath", "from beneath", "(from) beneath"],["@", "under", "from under", "(from) under"]] } , 
    {"word":"רָצוֹן", "category":"n.m. ", "frequency":"56", "arr":[["@", "favor"],["@", "will"],["@", "pleasing"]] } , 
    {"word":"שְׁמָמָה", "category":"n.f. ", "frequency":"56", "arr":[["@", "devastation"],["@", "waste"]] } , 
    {"word":"אַלְמָנָה", "category":"n.f. ", "frequency":"55", "arr":[["@", "widow"]] } , 
    {"word":"גֶּפֶן", "category":"n.f. ", "frequency":"55", "arr":[["@", "vine"]] } , 
    {"word":"דָּבַק", "category":"vb. ", "frequency":"55", "arr":[["@", "to cling", "cling"],["@", "keep", "to keep"]] } , 
    {"word":"חָדַל", "category":"vb. ", "frequency":"55", "arr":[["@", "to cease", "cease"]] } , 
    {"word":"חָזָה", "category":"vb. ", "frequency":"55", "arr":[["@", "to gaze", "gaze"],["@", "see", "to see"]] } , 
    {"word":"חָלַק", "category":"vb. ", "frequency":"55", "arr":[["@", "to divide", "divide"],["@", "share", "to share"]] } , 
    {"word":"חֵץ", "category":"n.m. ", "frequency":"55", "arr":[["@", "arrow"]] } , 
    {"word":"חָתַת", "category":"vb. ", "frequency":"55", "arr":[["@", "be shattered", "to be shattered"],["@", "be dismayed", "to be dismayed"]] } , 
    {"word":"כָּעַס", "category":"vb. ", "frequency":"55", "arr":[["@", "be vexed", "to be vexed"],["@", "be angry", "to be angry"]] } , 
    {"word":"מִדָּה", "category":"n.f. ", "frequency":"55", "arr":[["@", "measure", "measurement", "measure(ment)"],["@", "garment"]] } , 
    {"word":"צָעַק", "category":"vb. ", "frequency":"55", "arr":[["@", "to cry out", "cry out"]] } , 
    {"word":"שֵׁן", "category":"n.f. ", "frequency":"55", "arr":[["@", "tooth"],["@", "ivory"]] } , 
    {"word":"אָבָה", "category":"vb. ", "frequency":"54", "arr":[["@", "be willing", "to be willing"],["@", "consent", "to consent"]] } , 
    {"word":"גָּמָל", "category":"n.m. ", "frequency":"54", "arr":[["@", "camel"]] } , 
    {"word":"דְּבַשׁ", "category":"n.m. ", "frequency":"54", "arr":[["@", "honey"]] } , 
    {"word":"יְרִיעָה", "category":"n.f. ", "frequency":"54", "arr":[["@", "curtain"]] } , 
    {"word":"מָרוֹם", "category":"n.m. ", "frequency":"54", "arr":[["@", "height"]] } , 
    {"word":"סֹפֵר/סוֹפֵר", "category":"n.m. ", "frequency":"54", "arr":[["@", "scribe"],["@", "secretary"]] } , 
    {"word":"עָמָל", "category":"n.m. ", "frequency":"54", "arr":[["@", "trouble"],["@", "anxiety"],["@", "toil"],["@", "misery"],["@", "work"],["@", "worker"]] } , 
    {"word":"עֶרְוָה", "category":"n.f. ", "frequency":"54", "arr":[["@", "nakedness"]] } , 
    {"word":"שְׂמֹאל", "category":"n.m. ", "frequency":"54", "arr":[["@", "left"],["@", "north"]] } , 
    {"word":"שָׁוְא", "category":"n.m. ", "frequency":"54", "arr":[["@", "emptiness"],["@", "vanity"]] } , 
    {"word":"חָדָשׁ", "category":"adj. ", "frequency":"53", "arr":[["@", "new"]] } , 
    {"word":"יוֹמָם", "category":"adv. ", "frequency":"53", "arr":[["@", "daytime"],["@", "daily"]] } , 
    {"word":"יָצַק", "category":"vb. ", "frequency":"53", "arr":[["@", "to pour", "pour"],["@", "cast out", "to cast out"]] } , 
    {"word":"מְדִינָה", "category":"n.f. ", "frequency":"53", "arr":[["@", "province"],["@", "district"]] } , 
    {"word":"מַצָּה", "category":"n.f. ", "frequency":"53", "arr":[["@", "unleavened bread"]] } , 
    {"word":"סֹלֶת", "category":"n.f. ", "frequency":"53", "arr":[["@", "fine flour"]] } , 
    {"word":"צֵל", "category":"n.m. ", "frequency":"53", "arr":[["@", "shadow"],["@", "shade"],["@", "protection"]] } , 
    {"word":"רָנַן", "category":"vb. ", "frequency":"53", "arr":[["@", "to give ringing cry", "give ringing cry", "to give a ringing cry", "give a ringing cry"]] } , 
    {"word":"אַיֵּה", "category":"adv. ", "frequency":"52", "arr":[["@", "where?", "where"]] } , 
    {"word":"מָדַד", "category":"vb. ", "frequency":"52", "arr":[["@", "to measure", "measure"]] } , 
    {"word":"מָחָר", "category":"n.m./adv. ", "frequency":"52", "arr":[["@", "tomorrow"],["@", "in the future"]] } , 
    {"word":"שָׂעִיר", "category":"n.m. ", "frequency":"52", "arr":[["@", "he-goat"]] } , 
    {"word":"אַחֲרוֹן", "category":"adj. ", "frequency":"51", "arr":[["@", "behind"],["@", "after"],["@", "later"],["@", "latter"],["@", "last"]] } , 
    {"word":"בָּקַע", "category":"vb. ", "frequency":"51", "arr":[["@", "to cleave", "cleave"],["@", "split open", "to split open"]] } , 
    {"word":"דַּעַת", "category":"inf. ", "frequency":"51", "arr":[["@", "to know"]] } , 
    {"word":"הוֹי", "category":"prt. ", "frequency":"51", "arr":[["@", "alas!", "alas"],["@", "woe!", "woe"]] } , 
    {"word":"כָבַס", "category":"vb. ", "frequency":"51", "arr":[["@Pi", "to wash", "wash"],["@participle", "washer"],["@participle", "fuller"]] } , 
    {"word":"קֶרֶשׁ", "category":"n.m. ", "frequency":"51", "arr":[["@", "board", "boards"],["@", "plank", "planks"]] } , 
    {"word":"רֵאשִׁית", "category":"n.f. ", "frequency":"51", "arr":[["@", "beginning"],["@", "first"],["@", "chief"]] } , 
    {"word":"בְּתוּלָה", "category":"n.f. ", "frequency":"50", "arr":[["@", "virgin"]] } , 
    {"word":"חָרַם", "category":"vb. ", "frequency":"50", "arr":[["@", "to ban", "ban"],["@", "devote", "to devote"],["@", "destroy", "to destroy"]] } , 
    {"word":"טַבַּעַת", "category":"n.f. ", "frequency":"50", "arr":[["@", "ring"]] } , 
    {"word":"מוּסָר", "category":"n.m. ", "frequency":"50", "arr":[["@", "discipline"],["@", "instruction"]] } , 
    {"word":"נָכַר", "category":"vb. ", "frequency":"50", "arr":[["@Hi", "to recognize", "recognize"],["@Hi", "regard", "to regard"]] } , 
    {"word":"נָשַׂג", "category":"vb. ", "frequency":"50", "arr":[["@", "to reach", "reach"],["@", "overtake", "to overtake"]] } , 
    {"word":"קַחַת", "category":"inf. ", "frequency":"49", "arr":[["@", "to take"],["@", "to receive"]] } , 
    {"word":"כָּבֵד", "category":"adj. ", "frequency":"41", "arr":[["@", "heavy"],["@", "honorable"]] } , 
    {"word":"גָּנַב", "category":"vb. ", "frequency":"40", "arr":[["@", "to steal", "steal"]] } , 
    {"word":"מַלְכָּה", "category":"n.f. ", "frequency":"35", "arr":[["@", "queen"]] } , 
    {"word":"הֵנָּה", "category":"prn. ", "frequency":"31", "arr":[["@", "they", "fem. pl. they"]] } , 
    {"word":"קָטָן", "category":"adj. ", "frequency":"27", "arr":[["@", "small"],["@", "young"]] } , 
    {"word":"אַתֵּנָה", "category":"prn. ", "frequency":"4", "arr":[["@", "you", "fem. pl. you"]] } 

];



















